### ISSUE TITLE
How to monitor compilations which reuse variables

### ISSUE THREAD

**Issue by njaliu** [google/closure-compiler#1014]
I am new to closure compiler. After several trials on it, I found the compilation may reuse variables if possible for better compression. My question is:
Is there some ways that I can control the compilation on reusing variables or not? 
In further, can I do some statistics if I want to count the number of variables which have been reused?

Thanks a lot :)

**Comment by dimvar** [comment]
You cannot control whether the compilation will reuse variables.

To gather the statistics you want, you either have to write your own tool that looks at the output, or modify the compiler's source code, the compiler doesn't provide a tool. The RenameVars pass counts how many references there are to each variable and picks shorter names for the variables that are used more often. You can add some prints there to check what the pass does.

Also, please use
https://groups.google.com/forum/#!forum/closure-compiler-discuss
for questions and use github issues to file bugs.

**Comment by concavelenz** [comment]
The Java API allow fine grain control of many of the compiler optimizations.  The merging of multiple variables (rather than inlining existing values) is done by "coalesce variables".  Which in the CompilerOptions object is controlled by "setCoalesceVariableNames".  I don't recall that it reports any stats.  But it would be easy to write a compiler pass that counted the number of variable declarations with and without (in two separate compilations jobs) or before and after the coalesce variables pass.
