### ISSUE TITLE
lintChecks : WARNING - Optional parameter name opt_arg must be prefixed with opt_

### ISSUE THREAD

**Issue by tdelmas** [google/closure-compiler#1023]
```bash
echo "/** @param {boolean=} opt_arg */ function test(opt_arg) { if (opt_arg) alert('ok'); return 0; }" | java -jar compiler-20150609.jar --jscomp_warning lintChecks --compilation_level ADVANCED
```

>stdin:1: WARNING - Optional parameter name opt_arg must be prefixed with opt_
/** @param {boolean=} opt_arg */ function test(opt_arg) { if (opt_arg) alert('ok'); return 0; }
>
>0 error(s), 1 warning(s)

**Comment by MatrixFrog** [comment]
I suspect this happens if you use a coding convention other than the ClosureCodingConvention.

**Comment by MatrixFrog** [comment]
It's not the ClosureCodingConvention but the GoogleCodingConvention that has the rule that optional params start with `opt_`. Maybe we should move that rule to the ClosureCodingConvention? People using the Closure library are likely to use that style.

**Comment by concavelenz** [comment]
I'm what does the coding convention have to do with the lint check?  Generally, we don't want to add conventions that imply things (like opt_ being optional) as that makes it hard to include code with different conventions.  An example: a leading underscore than means "external" in one file and "private" in another.  That is why they only existing in the GoogleCodingConvention which is basically legacy.

**Comment by MatrixFrog** [comment]
We want to warn if a param is optional (has an `=` in the param annotation) but doesn't start with `opt_`, or vice versa. The GoogleCodingConvention is the thing that knows that optional params are supposed to start with `opt_` so that's why we used it (https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/lint/CheckJSDocStyle.java#L68).

One way to do this might be for CodingConvention to return a tri-state for isOptionalParameter. The GoogleCodingConvention could return true for `opt_` params and false otherwise, while the others would return "unknown" in all cases. And then the lint check would do nothing if it got an unknown.

**Comment by concavelenz** [comment]
It would be easier just to look for "opt_" text, I think. Rather than using the coding convention here but I could see it would be useful if say the Chrome coding convention has a convention for this.
