### ISSUE TITLE
ES6 static methods not playing nicely with subclasses

### ISSUE THREAD

**Issue by shicks** [google/closure-compiler#1305]
```javascript
class A {
  /** @returns {string} */ static foo(/** number */ x) {}
}

class B extends A {
}
```

This should be fine, but produces the rather strange error

```
input0:5: WARNING - assignment to property foo of B
found   : function (number): string
required: function (): string
class B extends A {
^
```

https://closure-compiler-debugger.appspot.com/#input0%3Dclass%2520A%2520%257B%250A%2520%2520%252F**%2520%2540returns%2520%257Bstring%257D%2520*%252F%2520static%2520foo(%252F**%2520number%2520*%252F%2520x)%2520%257B%257D%250A%257D%250A%250Aclass%2520B%2520extends%2520A%2520%257B%250A%257D%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by shicks** [comment]
Defining a static foo in the subclass eliminates the error, but obviously shouldn't be required.

**Comment by MatrixFrog** [comment]
It works if you use a `@param` instead of the inline type. I think I just forgot about inline types when doing this. Should be a pretty easy fix.

https://closure-compiler-debugger.appspot.com/#input0%3Dclass%2520A%2520%257B%250A%2520%2520%252F**%2520%2540param%2520%257Bnumber%257D%2520x%250A%2520%2520%2520%2520%2520%2520%2540return%2520%257Bstring%257D%250A%2520%2520%2520%2520*%252F%2520static%2520foo(%252F**%2520number%2520*%252F%2520x)%2520%257B%257D%250A%257D%250A%250Aclass%2520B%2520extends%2520A%2520%257B%250A%257D%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1
