### ISSUE TITLE
NTI: return statement not found if semicolon is on a new line

### ISSUE THREAD

**Issue by vobruba-martin** [google/closure-compiler#1357]
This is problem when you have your return statement on multiple lines for better readability.

```javascript
/**
 * @returns {boolean}
 */
var a = function() {
	return true
		|| true
	;
};
```
> WARNING - Missing return statement. Function expected to return boolean.
> var a = function() {
>         ^
> 
> 0 error(s), 1 warning(s), 100.0% typed

These examples show no warning:
```javascript
/**
 * @returns {boolean}
 */
var a = function() {
	return true || true;
};
```
```javascript
/**
 * @returns {boolean}
 */
var a = function() {
	return true
		|| true;
};
```
```javascript
/**
 * @returns {boolean}
 */
var a = function() {
	return true
		|| true // no semicolon
};
```

**Comment by dimvar** [comment]
This is working as intended. When you put the semicolon in a new line, because of JS's automatic semicolon insertion, the return statement is not the last one in the function body, there is an empty statement after it. So the type checker says that there is a path to the function exit that doesn't return. (That path is dead code, but we deal with dead code in later passes, we can't have every pass understand everything.)

You can see the AST produced by parsing this code here. Note that there is an EMPTY node after the RETURN node.
http://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%2520%2540returns%2520%257Bboolean%257D%250A%2520*%252F%250Avar%2520a%2520%253D%2520function()%2520%257B%250A%2520%2520%2520%2520return%2520true%250A%2520%2520%2520%2520%2520%2520%2520%2520%257C%257C%2520true%250A%2520%2520%2520%2520%253B%250A%257D%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1
