### ISSUE TITLE
 Output source map does not use input source maps, redux

### ISSUE THREAD

**Issue by rhendric** [google/closure-compiler#1360]
(resurrecting #115)

During an exchange with @ChadKillingsworth over in ChadKillingsworth/closure-compiler-npm#5, he asserted that the Closure compiler ought to take source maps of its inputs into account when generating output source maps, so that those output source maps refer to original inputs instead of intermediate files. It seems that the compiler has interfaces intended for this, but I can't get any of them to work—not with `--json_streams` (for a repro using gulp, see my write-up in ChadKillingsworth/closure-compiler-npm#5), not with `--source_map_input`,

```
lsc -c -m linked foo.ls
java -jar compiler.jar --source_map_input=foo.js\|foo.js.map --create_source_map compiled.js.map foo.js
```

and not with embedded source maps in the inputs.

```
lsc -c -m embedded foo.ls
java -jar compiler.jar --create_source_map compiled.js.map foo.js
```

(These examples use the LiveScript compiler, but any source map-generating transpiler would do.)

In all cases, the produced source map refers to `foo.js` in its `"sources"` attribute, instead of `foo.ls` as I'd want. Is there an alternate way to do this that I'm missing, or are some/all of the above intended to work as I'd imagined?

**Comment by ChadKillingsworth** [comment]
@rhendric Turns out the compiler ONLY supports input sourcemaps to support nicely formatted error messages. The generated sourcemap only applies to the intermediate source. This is more than simply adjusting the file name in the output sourcemap.

However, there is a need to keep the intermediate sourcemap as well (for non trivial transformations it's useful). So for now, we're going to solve this in the gulp plugin.

Sorry for the run around, but I needed to have the conversation with the entire team first.

**Comment by ChadKillingsworth** [comment]
Fixed by ChadKillingsworth/closure-compiler-npm@c16e012b
