### ISSUE TITLE
Add support for destructuring rest parameters

### ISSUE THREAD

**Issue by concavelenz** [google/closure-compiler#1383]
A change we missed to the spec, I noticed in the V8 change log:

https://github.com/v8/v8/commit/dfce900d64f2579607705fd2d94c13f28c2e996f

Here is the a repro case:

```javascript
function f(...[a,b]) {}
```

http://closure-compiler-debugger.appspot.com/#input0%3Dfunction%2520f(...%255Ba%252Cb%255D)%2520%257B%257D%250A%250A%250Avar%2520%255Ba%252Cb%255D%2520%253D%2520%255B1%252C2%255D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by MatrixFrog** [comment]
The final ES6 spec shows the behavior that is currently implemented in Closure Compiler. This is an upcoming change for ES7 if I'm not mistaken.

If we're sure this is going to made it to the ES7 final spec (it seems pretty likely) then we should probably make REST a one-child AST node so that this becomes easier when we start getting serious about ES7 features, but still disallow anything but a NAME as its first child.
