### ISSUE TITLE
Guidance needed on polyfills

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1425]
When using ES6 to ES5 you often are using API as well as language enhancements and need polyfills, e.g. for Array.prototype.find or Map.

Closure Compiler gives you some of these, but not all. It's not clear which are missing, and this is changing as I see frequent new commits adding polyfills. Presumably at some point ES6 will be fully polyfilled, but then there will be ES7.

However the Closure Compiler externs are much more broadly defined, so you can easily compile a project that references a modern API in the externs without warnings, but find at runtime in specific browsers it fails.

I feel that we need some/all of:
1. A brief wiki page which explains the above and gives advice for how to ensure all polyfills needed are present for a given target platform; see https://github.com/google/closure-compiler/issues/1388#issuecomment-171396194;
2. A better externs system (https://github.com/google/closure-compiler/issues/1388#issuecomment-171395445) where perhaps you specify the target environment and the externs subset are chosen correctly, rather than blindly including all externs;
3. A simple JS script that consumes a given externs file, and reports which constructors and prototype properties are missing, which can be run in a given platform/browser to check for missing polyfills.

**Comment by MatrixFrog** [comment]
@shicks has been the primary person working on the compiler polyfills so he may be the best person to do item 1. Item 2 is possible today by passing specific `--externs` flags but I agree this could be improved. 3 would be good too and could probably be totally separate from the compiler itself, so would be a great thing to get from an external contributor.

**Comment by shicks** [comment]
At this point, all the planned polyfills are complete (String, Array, Object, Number, Math, Set, and Map; the others - mainly weak collections, Proxy, and Reflect - are much less feasible and so we're not planning on tackling them at all), though the RewritePolyfills pass is and has been off by default, which means that although they're included in the runtime, they will always be stripped from the output (provided it's using advanced optimizations).  I'm working on turning it on soon, but there are a few wrinkles.  As you pointed out, it's important to prevent surprises, where someone expects something to be polyfilled but it isn't.  The compiler pass has some affordance for this: if it's enabled and it sees a non-polyfilled symbol and the --language_out is too low, then it will emit a warning.  This breaks down in two ways: (1) the compiler doesn't currently support --language_out=ES6 at all, so any use of (e.g.) WeakMap will always warn, and there's not currently any way to say "yes, I said ES5, but I only care about *modern* browsers"; (2) there are some symbols that are technically only introduced in ES6 but it's perfectly reasonable to assume they're available even in many older browsers, such as typed arrays.  I've left these out completely, so they won't be warned on, but I'm not 100% confident about this choice; (3) prototype methods are nearly impossible to statically analyze, so we don't really even try - if anything could possibly be an ES6 prototype method call, we install the polyfill on the native object and leave it at that.

I would like to see a little finer gradation in the --language_out flag, i.e. an "es5+" and/or "es6-" option that would allow us to not warn on typed arrays or WeakMap, but would otherwise behave the same as ES5... but that's a much bigger change.

**Comment by dimvar** [comment]
> I would like to see a little finer gradation in the --language_out flag, i.e. an "es5+" and/or "es6-" option that would allow us to not warn on typed arrays or WeakMap, but would otherwise behave the same as ES5

Can we let the people who want WeakMap in the result use lang_out ES5 and suppress the warning? Having language levels for things that aren't really JS versions seems more confusing.

**Comment by supersteves** [comment]
@shicks wrote:
> they will always be stripped from the output

From what I can see, the polyfills are declared as $jscomp.something, and never take effect (i.e. assigned to global 'something' if not already present in the runtime environment) unless you enable this pass? Hence pruned as unused?

Presumably this pattern is used so that, with the pass enabled, should you not *need* a particular polyfill, CC will automatically prune it. But presumably, even if included in the output, the polyfill will only have an effect for older environments.

So I gather this means all these polyfills have no effect whatsoever unless you enable RewritePolyfills.  

What are the wrinkles with this pass? Can I turn it on for my project?

**Comment by shicks** [comment]
That's exactly true.  We're trying to be cautious in rolling this out because it (obviously) has a high potential to break people.  The internal roll-out strategy was to get all the polyfills in place first and then flip the flag, mainly so that in case there are any breakages we can roll back only the flag switch, rather than having to roll back all the implementations.

The biggest wrinkle with the pass is probably the version logic.  We're keying off of the language_out flag to decide whether to do the rewriting, and that flag isn't fine-grained enough to work as well as it could.  Another issue is that it doesn't play very nicely with other polyfill-like code - for instance, if your code does

    if (typeof Reflect === 'function') { ... }

then this is a sort of attempt at doing your own polyfill, and the pass doesn't know how to interpret it very well.  As such, right now you would need to turn off the whole pass to make this work.  It might be nice to be able to do more fine-grained configuration, but we're hesitant to implement that, since it's a pretty complicated configuration and would therefore be very difficult to test thoroughly.

**Comment by supersteves** [comment]
What about if you load polyfills at runtime, e.g. Babel's polyfills (just the polyfills, nothing else)? Where they overlapped, and with your pass enabled at build time, would the first to load be the version that took effect, or would advanced mode rewrite yours to unrelated functions?

Does your comment about versions relate to the FeatureSet recent commits at all?

**Comment by zloirock** [comment]
Just interesting: why do you wanna write your own polyfills instead of usage `core-js`? :)

**Comment by shicks** [comment]
The build-time pass will rewrite e.g. Map to $jscomp.Map, so you won't get other (e.g. Babel) polyfills.  We like this approach because it makes it very clear that polyfilling has happened, instead of overwriting objects on window and then we have a state where you can't look at the code and reason about the codepath.  That said, prototype methods _are_ written directly onto the native objects because it's a lot less reasonable to rewrite them.

In terms of why we wrote our own, please see the response on https://groups.google.com/forum/#!topic/closure-library-discuss/dosZGv-LIG0.

**Comment by Dominator008** [comment]
@supersteves https://github.com/google/closure-compiler/commit/f2eb08a075c1105423e96cf53c2a0aa1e2f98607 Added the `--rewrite_polyfills` flag.

**Comment by supersteves** [comment]
Thanks!

**Comment by caridy** [comment]
is there a way to rewrite the polyfills without adding the polyfills on every file, but instead having a way to guarantee that `window.$jscomp = $jscomp;` is set once at the page level, and any compiled file loaded in that page reuse `$jscomp`?

**Comment by martine** [comment]
Is there a way to disable the warning about unimplemented Polyfills?

E.g. you get this even if you declare Reflect in an externs.js:
```
t.js:5: WARNING - Built-in 'Reflect' not supported in output version ECMASCRIPT5: set --language_out to at least ECMASCRIPT6
```

**Comment by dimvar** [comment]
You can avoid the warnings by skipping the compiler's rewriting of the polyfills `--rewrite_polyfills=false`. If you want to run the pass and not see the warnings, I think it's not possible at the moment. @shicks can chime in.

**Comment by binarykitchen** [comment]
Is there a trick how to load polyfills dynamically, only when needed? For example `goog.userAgent` says it's IE11.

**Comment by shicks** [comment]
Not that I can think of.  You could disable them from your main binary and make a separate binary with just the polyfills, but the normal use case is to simply include them at the start of your binary, which is going to load them no matter what (even if they do nothing since all the symbols already exist).  That of course gets into questions of how to conditionally load code, and the compiler has no stance on that.
