### ISSUE TITLE
@typedef with 'let'

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1429]
Our large ES6 codebase has an eslint rule "no-var" (to prefer ```let``` over ```var```). Until we started experimenting with NTI we used this pattern:
``` javascript
/** @typedef {{ a: (?string), b: (boolean) }} */
let X;
```

However with NTI the compiler complains:
```
input0:2: WARNING - A typedef variable represents a type name; it cannot be assigned a value.
let X;
```

https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540typedef%2520%257B%257B%2520a%253A%2520(%253Fstring)%252C%2520b%253A%2520(boolean)%2520%257D%257D%2520*%252F%250Alet%2520X%253B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

Presumably this is due to how ```let``` is transpiled. Still, it's a bit misleading. Ideally the compiler would realise this is a typedef and treat it as var.

To my mind it seems to make more sense to write ```const X``` for a typedef but when uncompiled an ES6 runtime would complain about const without a value.

What's the best practice for typedefs? Should they always use ```var``` (and with a linter exclusion for cases like ours)?

They're a bit odd; they appear to be global variables without a defined value (not sure if that has any significance in uncompiled mode). Although in goog.modules presumably they are scoped to the module? And presumably they are stripped in simple and advanced compilation, so what's the recommended way of naming typedefs in a large project?

**Comment by Dominator008** [comment]
It makes more sense to use "var" for typedefs, because these aliases are supposed to be usable before they are declared.
Eg:
http://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540return%2520%257Bnum%257D%2520*%252F%250Afunction%2520f()%2520%257B%250A%2520%2520return%25201%253B%250A%257D%250A%250A%252F**%2520%2540typedef%2520%257Bnumber%257D%2520*%252F%250Avar%2520num%253B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

Using "let" or "const" is a bit odd here since technically they have a "temporal dead zone" before their declarations.

**Comment by supersteves** [comment]
It would be good if the docs at https://developers.google.com/closure/compiler/docs/js-for-compiler had a little more detail on this. Are these open sourced (or can they be)?

**Comment by ChadKillingsworth** [comment]
The documentation is not open source. That is to say that there is not currently a way for external contributors to modify content on developers.google.com. There is a desire to change that, but there is nothing ready on that front right now. We are painfully aware of the state of the documentation.

**Comment by supersteves** [comment]
@ChadKillingsworth Did you mean to close this rather than de-prioritise? Don't you want (e.g. lang in = ES6) to support using "let" for typedefs rather than the pre-ES6 "old school" ```var``` ?

Before NTI I was using typedefs with let, and didn't need hoisting. It seems confusing to *require* the use of var for typedefs.

**Comment by ChadKillingsworth** [comment]
Yes I meant to close.

`var` is not deprecated. As @Dominator008 pointed out, hoisting of typedefs is intentional and `let` doesn't make much sense. We either have to add rules to force typedefs to the top of a scope, or simply use `var`. Since a typedef is a Closure-compiler specific construct and has no use in real world code, I see no reason to do this extra work for a linter.

Other maintainers may disagree and re-open if they choose.
