### ISSUE TITLE
suspicious code warning about "use strict" after comment

### ISSUE THREAD

**Issue by martine** [google/closure-compiler#1495]
In a google-internal app, code like this:

```javascript
// @fileoverview blah blah blah
"use strict";
```

produces 
 WARNING - Suspicious code. Is there a missing '+' on the previous line?
"use strict";
^

This stackoverflow thread (which links to specs) indicates that it's legal to have comments before the "use strict";

http://stackoverflow.com/questions/31412978/can-comments-come-before-use-strict

**Comment by ChadKillingsworth** [comment]
I can't reproduce this.

**Comment by martine** [comment]
I think I confused myself with a different issue.  I'm gonna close this and only reopen it once I have a reproduction case.  Sorry for wasting your time.  :(

**Comment by ChadKillingsworth** [comment]
// @fileoverview blah blah blah

It's possible that the issue is that comment - but having the '+' error with it is very strange. However I would expect a warning along the lines of "attempt to use a JSDoc annotation outside of a JSDoc comment block" as that comment should have started with "/** @fileoverview"

**Comment by MatrixFrog** [comment]
I think we warn if you start your comment with `/*` instead of `/**` but
not if you start it with `//` :(
