### ISSUE TITLE
Function constructor has sideeffects?

### ISSUE THREAD

**Issue by L3P3** [google/closure-compiler#1577]
```javascript
(function(){
 /** @constructor */var A=function(){}
 new A();
})()
```
in ADVANCED gets optimized into
```javascript
new function(){};
```
and after some research, I got out that
```javascript
new Function;
```
does not get optimized further. Why is this so and how can I go arround that?
This really annoys me... :disappointed:

**Comment by L3P3** [comment]
This is what an empty file including a library produces in CC:
```javascript
(function(){function a(a){this.a=a}var b=window;new b.Date;a.prototype={a:!1};new a(!1);new a(!1);new b.ActiveXObject("Scripting.FileSystemObject")})()
```

**Comment by L3P3** [comment]
And that is what it produced using another class defining method (`.prototype.prop=` instead of `.prototype={prop:...}`):
```javascript
(function(){function c(){}function d(a){this.a=a}function b(){}var e=window;new e.Date;var a=function(a){this.a=a;a=(new d(0)).b=new c;a.a=a.b=1}.prototype;a.a=0;a.h=a.i=0;a.c=a.f=40;a.b=g;a.l=20;a.j=!1;a.g=0;a=d.prototype;a.a=0;a.h=a.i=a.j=a.l=0;a.b=a.m=a.g=a.f=a.c=a.o=null;a.u=!1;a.s=null;a.v=1;a=c.prototype;a.c=a.f=a.a=a.b=0;a=function(){}.prototype;a.a=a.b=1;a=function(){}.prototype;a.b=a.a=a.c=1;a=function(a){this.a=a}.prototype;a.a=0;a.g=a.f=a.c=0;a.b=1;a=function(){}.prototype;a.a=a.b=a.c=a.f=a.g=a.h=a.i=a.j=0;a.s=a.u=a.m=a.l=a.o=1;a=function(){}.prototype;a.c=a.a=a.b=0;a=function(){}.prototype;a.b=a.c=a.a=null;a=function(a){this.b=a;f[this.a=f.length]=this;new b;new b;new b}.prototype;a.b=0;a.a=0;a.c=a.f=0;a.g=a.i=a.j=!1;a.h=1;var f=[];new b;new b;new e.ActiveXObject("Scripting.FileSystemObject")})()
```

**Comment by concavelenz** [comment]
(1) The first gets compiled to zero bytes for me:

http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540formatting%2520pretty_print%252Cprint_input_delimiter%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A(function()%257B%250A%2520%252F**%2520%2540constructor%2520*%252Fvar%2520A%253Dfunction()%257B%257D%250A%2520new%2520A()%253B%250A%257D)()%250A%250A

(2) The second "new Function" (which is distinctly different from "new function(){}") has side-effection depending on the strings passed.  Distinctly, it can throw a parse error.

(3) I'm not sure what a "empty file including a library" means.  Which library?  What did the original source look like?  Loading a library has side-effects.  If the library is coded in a straightforward way, and lacks side-effects, it should be removed fully.

However, code such as 'new e.ActiveXObject("Scripting.FileSystemObject")' will never be removed because the sideeffects of the ActiveXObject constructor is unknown.

**Comment by L3P3** [comment]
Thank you for your reply.
My code is very big and complicated and there are already many hacks in
order to get a better output. I had to make many things multiple times...
And the most annoying thing for which I still have no solution, is that I
cannot say CC that a specific object/function has no f* sideeffects.
For example, in my project, the only use for window.ActiveXObject is for
filesystem access. So, creating an AcriveXObject for filesystem doesn't
have any sideeffects. I have an externs file where I tried to declare that
but due to this overwrite rule, I cannot redefine AXO, so I renamed it to
__pseudo__ActiveXObject and made a script in a toolchain to replace all
"__pseudo__" with "".
I hate it when software forbids me to do what I want to do on my pc, so
please add an @overwrite or something, as discussed in other posts.
I think that the content of my library is not important here. (I am even
not allowed to post it because it is a project internal secret!)
I wonder why "new function(){}" now gets optimised to "" – a few days ago,
I got out the same as the input. I will look for that later.

**Comment by concavelenz** [comment]
You can certainly change ActiveXObject to have @nosideeffect, you just need to turn off the default externs, and supply your own copy with whatever changes you want.  

Otherwise without anything specific there is nothing actionable here.
