### ISSUE TITLE
Improve documentation on JS Modules

### ISSUE THREAD

**Issue by juannerito** [google/closure-compiler#1585]
https://github.com/google/closure-compiler/wiki/JS-Modules

The Documentation on importing ES6 modules and requiring Common Js modules appears to be incomplete and ambiguous, especially around importing ES6/CommonJS modules into goog.module modules, specifically this title:

**Importing ES6 Module code from a goog.module**

It seems to me that this should be 

**Importing ES6 Module code _into_ a goog.module**

That's how I read it at least. In addition, adding the sample code, (replaced with my local files) doesn't do anything: 
```js
var MySymbol = require('path/to/es6/module').default;
```

This is the command I'm using to compile:

`java -client -jar /bin/google_closure/compiler.jar --js js/es6/logger.js --js js/app/app.js   --compilation_level=SIMPLE --dependency_mode=STRICT --entry_point=goog:app  --language_in ECMASCRIPT6 --language_out ES5 --js_output_file=static/js/app.js`

**Comment by Dominator008** [comment]
I've changed the "from"s to "into"s. Can you clarify what you mean by "adding the sample code doesn't do anything"?

**Comment by ChadKillingsworth** [comment]
These are incomplete because I wrote the documentation and I don't use goog.modules. 

For your specific case, you need to use the `--process_common_js_modules` flag for the `require` statement to be rewritten.

Once my current set of PRs get's merged, we'll be able to add more clarity around some of these use cases. The documentation is ambiguous because some of the edge cases were not supported (like using an ES6 module as an entry point).

However, feel free to update the documentation to make it clearer.
