### ISSUE TITLE
Polyfills for WeakMap, WeakSet, etc.?

### ISSUE THREAD

**Issue by Dominator008** [google/closure-compiler#1709]
Thanks to @shicks, we are passing quite a few tests from the "Built-ins" group in https://kangax.github.io/compat-table/es6/#closure. However, it seems that our polyfills are still rather incomplete. IIRC there was an internal CL that implemented WeakMap and WeakSet. Do we plan to port that over?

**Comment by dimvar** [comment]
@shicks Maybe you can write a wiki page about the polyfills, what we support (so people know if we don't intend to support something vs if we haven't implemented it yet), and how to use them?

**Comment by MatrixFrog** [comment]
https://github.com/google/closure-library/commit/80ae4692c319936798563a9ae173baf563cbcebd adds a WeakMap in Closure Library but it was rolled back.

**Comment by concavelenz** [comment]
The issue is how to implement a WeakMap polyfill, there are two basic choices: (1) create a weakMap that leaks (doesn't collect with GC) (2) create a WeakMap that adds properties to objects which would fail on sealed objects (a distributed Map).

Both implementations have advantages/disavantages and it is "wrong" (IMHO) to assume you know which is correct for any particular use case.

**Comment by Dominator008** [comment]
@concavelenz Seems like most polyfill implementations go with option 2.

**Comment by shicks** [comment]
We now implement these polyfills (going with option 2, and taking some reasonable measures to prevent breakages due to sealed keys).
