### ISSUE TITLE
[NTI] Variadic params {...T} should infer union types rather than failing

### ISSUE THREAD

**Issue by shicks** [google/closure-compiler#1731]
See [this example](https://closure-compiler-debugger.appspot.com/#input0%3Dsink(Array.of(1%252C%2520'foo'%252C%2520undefined))%253B%26input1%26conformanceConfig%26externs%3Dfunction%2520sink(arg)%2520%257B%257D%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1).

`Array.of` is typed as `@param {...T} @return {!Array<T>}`, NTI fails with
```js
Array.of(1, 'foo', undefined)
```
with the error
```
input0:1: WARNING - Illegal instantiation in function type function(...T):Array<T> for the type variable T.
 You can only specify one type. Found [number, string, undefined].
Array.of(1, 'foo', undefined));
^
```

**Comment by dimvar** [comment]
It's deliberate to instantiate T to a single type, rather than the union of the arguments. This is usually the user intent, and the fact that the old type checker just unions everything is a loose check IMO. Also, I wouldn't want to special-case Array.of by name. So, the current behavior is inconvenient in this case, but I think it's generally the right one.

The fix for this case would be to allow explicitly specifying the type to instantiate, and one would be able to say that it is ? in this case.
