### ISSUE TITLE
Reflect polyfill warning

### ISSUE THREAD

**Issue by evmar** [google/closure-compiler#1846]
Suppose you're using a polyfill for Reflect.  Any reference in your code to `Reflect` causes the warning:

```
WARNING - Built-in 'Reflect' not supported in output version ECMASCRIPT5: set --language_out to at least ECMASCRIPT6
```

On https://github.com/google/closure-compiler/issues/1425, @dimvar wrote:

> You can avoid the warnings by skipping the compiler's rewriting of the polyfills --rewrite_polyfills=false. If you want to run the pass and not see the warnings, I think it's not possible at the moment. @shicks can chime in.

What I'd like instead is to continue to use the builtin polyfills but still use my own Reflect polyfill.

**Comment by martine** [comment]
Sample code snippet:

```js
if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(...)
else r = function(...) {};
```

**Comment by shicks** [comment]
That's correct.  I can see three ways around this:
(1) I'm working on a Reflect polyfill, but it's blocked on some long-needed reorganization
(2) We could put the warning into a diagnostic group that can be disabled (globally and/or locally)
(3) We could provide customization for exactly which polyfills to use

The third option is more customization than we'd ideally prefer, so that leaves options (1) and (2).  The new way we're doing polyfills will play a lot better with any you provide yourself, but there's still a potential problem if you're targeting ES3 but our polyfill only works in ES5 (i.e. you'll still get an error even though you're providing your own that will work).  But that's probably not actually going to come up.

**Comment by martine** [comment]
I don't know how the code works, but what I was imagining is you could just disable the Reflect polyfill-matching logic entirely when targeting ES5, making it a compiler error to reference it (the same as referencing some nonexistent FooBar() function might be).

Now that I think of it, would it work to change the above code to something like
```js
if (typeof window['Reflect'] === "object" && typeof window['Reflect'].decorate === "function") r = window['Reflect']
```
?

**Comment by shicks** [comment]
The reason we want to give an error is that if we're polyfilling some things and not others, people are likely to be surprised if they're expecting it but it's silently left as-is.

Your workaround should work fine in the short term.

**Comment by shicks** [comment]
The workaround should no longer be required.  In particular, (a) we do polyfill Reflect, (b) we now only care about individual methods, so the top-level symbol itself is not actually a problem, and (c) we understand guards.
