### ISSUE TITLE
remap polyfills (via $jscomp) without including $jscomp definition in the output

### ISSUE THREAD

**Issue by caridy** [google/closure-compiler#1905]
When splitting the app into "bundles", sharing `$jscomp` definitions between all bundles could be beneficial, especially if the rollups are created by concatenating "bundles" on-demand. 

With the new option `--inject_library=es6_runtime` we can easily externalize `$jscomp` definitions that can be used to patch the environment, but the missing part is how to compile modules with the proper mapping for polyfills without having to include `$jscomp` definitions in those other files?

**Comment by ChadKillingsworth** [comment]
I'm really unclear on the details of what you are doing.

 1. What compilation mode?
 2. Are you running a single compilation or multiple?
 3. How are you splitting your app into "bundles"?
 4. How is your output designed to be consumed?

**Comment by caridy** [comment]
> What compilation mode?

A variation of the following with some extra wrapping:

```bash
java -jar path/to/compiler.jar
     --js_module_root=section1
     --js=section1/*.js
     --entry_point=section1/foo
     --language_in=ECMASCRIPT6_STRICT
     --language_out=ECMASCRIPT5_STRICT
     --js_output_file=output/section1.js
```
> Are you running a single compilation or multiple?

Compiling multiple sections, and producing multiple files (or bundles).

> How are you splitting your app into "bundles"?

Think of a bundle as a folder with few ES modules, an entry point, and few external dependencies. Compiling each folder separately produces a fold, exporting the internals of the fold via a wrapper.

> How is your output designed to be consumed?

bundles can be provision and evaluated at any given time, and somehow will provide access to the exports of the fold via the wrapping function, and can be consume by invoking the wrapping function which returns the exports of the fold.

**Comment by caridy** [comment]
Additionally, the request here is to have an option to match babel's polyfilling strategy, which allows you to have the polyfills separate (as part of the runtime patching mechanism) and getting all your compiled code to map to those polyfills. Currently, there is no way to compile a module while mapping to `$jscomp` without including the polyfills at the top of the output, even when `$jscomp` can be provisioned ahead of time.

**Comment by ChadKillingsworth** [comment]
> Think of a bundle as a folder with few ES modules, an entry point, and few external dependencies. Compiling each folder separately produces a fold, exporting the internals of the fold via a wrapper.

With `ADVANCED` mode, the compiler would compile all of your "bundles" as a single job and split the output. It would move between the bundles when it thinks it's safe to do so.

With `SIMPLE` mode, it's a little trickier. You would have to do the heavy lifting.

> bundles can be provision and evaluated at any given time, and somehow will provide access to the exports of the fold via the wrapping function, and can be consume by invoking the wrapping function which returns the exports of the fold.

That's pretty general. I need specifics. Are you expecting your bundles to be a CommonJS module? Are you wanting to export a namespace? How are you loading them?

Module rewriting will remove all module specific code. You are left with a JS bundle that isn't a module at all - it's a script (unless you are doing something specific I'm not seeing). If you are wrapping it after compilation, you could add a module wrapper there.

> Additionally, the request here is to have an option to match babel's polyfilling strategy.

This project is distinctly different from Babel. Some devs (like me) prefer that the compiler not add polyfills - that should be a user's responsibility. You always have the option to include the polyfills on your own.

**Comment by caridy** [comment]
>That's pretty general. I need specifics. Are you expecting your bundles to be a CommonJS module? Are you wanting to export a namespace? How are you loading them?

* CommonJS or System.register or any similar (and arbitrary) format that we can define and add via the wrapper.
* no namespace (we don't want to leak out of the bundle)
* they can be loaded as script tags, which will call to register the bundle into some sort of global register via the wrapper.

> Module rewriting will remove all module specific code. You are left with a JS bundle that isn't a module at all - it's a script (unless you are doing something specific I'm not seeing). If you are wrapping it after compilation, you could add a module wrapper there.

That's precisely the idea. Adding a bundle/module wrapper that helps us to control them.

> You always have the option to include the polyfills on your own.

Maybe I shouldn't have mentioned polyfills, and just es6 runtime in general. It is true that we might cover the polyfills via FT polyfill service, or something similar that allow us to patch the runtime before the compiled code runs. But considering that the closure's `$jscomp`definition is much more than just polyfills or equivalent implementations, I think this is a valid case.

Even though we might inject `$jscomp` into the bundle via the module wrapper, closure will have to 
remap without defining `$jscomp` in the bundle itself.

**Comment by ChadKillingsworth** [comment]
You should check out the `--module` flag (for code splitting) and compile all of your code in a single compilation job. The runtime and polyfills will only be included in your base module. That's the preferred method of doing things like this.

**Comment by caridy** [comment]
@ChadKillingsworth we have tried `--module` flag, but that doesn't come close, we are talking about ~2500 bundles, each with at least 2 modules, plus 1K coming from another filesystem. Closure compiler simply blows away (from leaking to just taking too much time when the number of modules to be compile is too big), and considering that the relationship between the bundles is via an indirection (another registry of web-components like) they don't really depend on each other, and they don't really mix and match. Ideally we can compile them in isolation. In other words, `--module` flag does not work for salesforce scale :/

**Comment by shicks** [comment]
I'm not all that clear on exactly what you're asking for, but it sounds like you're saying that you can get `$jscomp` in a separate module, but then you want to do a bundle job that *doesn't* get `$jscomp` included so that you can include it yourself.  There's a flag in `CompilerOptions` (not sure if it's externalized in the command line runner) to disable library injection, so if it's not exposed currently, it would be easy enough to add it.

**Comment by caridy** [comment]
@shicks yeah, that will be enough, doing the re-mapping in a bundle without injecting the `$jscomp` because we can "magically" set that up upfront.

**Comment by diffen** [comment]
Isn't there a chance that `$jscomp` defined in multiple minified JS files will conflict? Say you use **main.js** for a web app and that lazy loads **module1.js** and/or **module2.js** if needed. All 3 files are updated for bug fixes independently of each other. When one file updates, you minify it separately using Closure Compiler (simple mode) and deploy it. 

Isn't this risky because $jscomp will conflict? What is a good way to work around this?

**Comment by ChadKillingsworth** [comment]
@diffen Use the isolation mode flag to ensure you aren't in the same scope.

**Comment by OzoneGrif** [comment]
It does conflict, I'm having this very issue on our project, and the Whitespace mode crashes with 'for of' loops. I've read the whole thread but I don't see any solution to the original question which is :
- One JS file with the polyfill (possibly created manually)
- Many JS optimized files (generated by Closure), without the polyfill

**Comment by brad4d** [comment]
AFAICT, the purpose of this issue is to request the ability to do something like this.

1. Run closure-compiler on `a.js`, `b.js`, and `c.js` to create `abc_out.js`
2. Run closure-compiler on `x.js`, `y.js`, and `z.js` to create `xyz_out.js`
3. Concatenate `abc_out.js` and `xyz_out.js` when shipping them to the browser and / or load them independently in the browser.

Presumably externs files are used to define the interface between code in the 2 output files.
This bug exists because you would need to include the `$jscomp` polyfill code needed to support transpilation only once.

A core part of the closure-compiler design is that it should see all of the relevant code, except possibly some external library code that is not compiled. Separately compiling pieces then putting them together later isn't something we actively try to support.

If the purpose of doing things this way is to reduce the amount of code that must be shipped to the browser, the `--module` flag should be used as @ChadKillingsworth suggested above. With this flag the compiler sees all the code as input, but splits the output into separately loadable files.
Here's his nice SO article about it.

https://stackoverflow.com/questions/10395810/how-do-i-split-my-javascript-into-modules-using-googles-closure-compiler/10401030#10401030

**Comment by stevendwood** [comment]
@brad4d - given the answer from @shicks here https://github.com/google/closure-compiler/issues/1603 it seems like you kind of can do this ?  I think first would need to get the polyfills in a separate output file by compiling and empty source with force inject es6 runtime.

Then you build `abc_out.js` and `xyz_out.js` using the option `setPreventLibraryInjection(true)`.     Or presumably you could write a small file that used all the transpilations you wanted to support and include that.  You combine the polyfill and the two output files.
