### ISSUE TITLE
Subclassing a class with a zero argument constructor generates an incorrect default constructor

### ISSUE THREAD

**Issue by xaquseg** [google/closure-compiler#1929]
If you define a class with a zero argument constructor (or no declared constructor), the generated constructor for a subclass has an extra argument.

Example:
```javascript
class Base {
  constructor() {
    alert(1);
  }
}

class Subclass extends Base {
}

alert(new Subclass);
```
Compiles to:
```javascript
var $jscomp = {scope:{}, inherits:function(a, b) {
  function d() {
  }
  d.prototype = b.prototype;
  a.prototype = new d;
  a.prototype.constructor = a;
  for (var c in b) {
    if (Object.defineProperties) {
      var e = Object.getOwnPropertyDescriptor(b, c);
      e && Object.defineProperty(a, c, e);
    } else {
      a[c] = b[c];
    }
  }
}}, Base = function() {
  alert(1);
}, Subclass = function(a) {
  Base.apply(this, arguments);
};
$jscomp.inherits(Subclass, Base);
alert(new Subclass);
```
In advanced mode, a warning is also printed:

>JSC_WRONG_ARGUMENT_COUNT: Function Subclass: called with 0 argument(s). Function requires at least 1 argument(s) and no more than 1 argument(s). at line 10 character 6

**Comment by MatrixFrog** [comment]
We compile each class separately, without looking at the superclass, in order to make sure that transpilation can be done a file at a time. So the transpiled output for the subclass has a `var_args` parameter. It should also have a `@param {...?}` annotation or something like that, but it looks like we're failing to add that, or dropping it somewhere.
