### ISSUE TITLE
The list of available types is missing

### ISSUE THREAD

**Issue by JoeArizona** [google/closure-compiler#1979]
In the docs on type annotations, there is no actual list of available type names.

In the table presented on [this page](https://developers.google.com/closure/compiler/docs/js-for-compiler#types), three example type names are given:
````
{boolean}
{Window}
{goog.ui.Menu}
````
We see `string` and `number` elsewhere, but I never would have guessed `Window` or `goog.ui.Menu` as basic types. Can we get a list of available type names?

**Comment by MatrixFrog** [comment]
There are a few types built into the language itself (string, Function, Array, etc) and many others that are present in browsers (Document, Window, HTMLElement, etc.)

All these are listed in what we call "externs" files, as described at https://developers.google.com/closure/compiler/docs/api-tutorial3

See for example https://github.com/google/closure-compiler/blob/master/externs/es3.js and https://github.com/google/closure-compiler/blob/master/externs/es5.js -- browser APIs are under https://github.com/google/closure-compiler/tree/master/externs/browser

goog.ui.Menu is defined in the Closure Library (https://github.com/google/closure-library). Docs for it are at https://google.github.io/closure-library/api/goog.ui.Menu.html

Of course if you use some other library (jQuery, Polymer, whatever) then the library maintainer will hopefully have docs for the types that library provides. Those types will be provided to the compiler either because you're passing the library itself to the compiler, or passing externs for that library to the compiler. We have externs for some well-known libraries in https://github.com/google/closure-compiler/tree/master/contrib/externs
