### ISSUE TITLE
NTI fails to detect typing error

### ISSUE THREAD

**Issue by gaetmorin** [google/closure-compiler#2048]
The following incorrect program emits no warning with `--new_type_inf --warning_level VERBOSE`
(compiler version v20160911):

``` js
/** @constructor */ function A() {}
/** @constructor */ function B() {}

/**
 * @param {!Array<A>} as
 * @return {A}
 */
function compiles(as) {
    let a = new A();
    let b = new B();
    as.filter((it) => it !== b);
    return b;
}
```

The function contains two errors: comparing `it` (of type `A`) to `b` (of type `B`), and returning `b` where an `A` is expected. OTI correctly reports both errors (with `--warning_level VERBOSE`):

```
src/main.js:11: WARNING - condition always evaluates to true
left : (A|null)
right: B
    as.filter((it) => it !== b);
                      ^

src/main.js:12: WARNING - inconsistent return type
found   : B
required: (A|null)
    return b;
           ^
```

The problem seems to be the invalid filter callback. If I fix that error, NTI correctly reports the second error. That is:

``` js
/** @constructor */ function A() {}
/** @constructor */ function B() {}

/**
 * @param {!Array<A>} as
 * @return {A}
 */
function doesNotCompile(as) {
    let a = new A();
    let b = new B();
    as.filter((it) => it !== a); // replaced b with a
    return b;
}
```

correctly warns when compiled with `--new_type_inf --warning_level VERBOSE`:

```
src/main.js:12: WARNING - Returned type does not match declared return type.
Expected : A|null
Found    : B

    return b;
    ^
```

**Comment by dimvar** [comment]
Note to self: compare to the following code, that doesn't use generics and finds the correct warnings. Maybe the issue here is generics related?

https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540constructor%2520*%252F%2520function%2520A()%2520%257B%257D%250A%252F**%2520%2540constructor%2520*%252F%2520function%2520B()%2520%257B%257D%250A%250A%252F**%250A%2520*%2520%2540return%2520%257B!A%257D%250A%2520*%252F%250Afunction%2520doesNotCompile()%2520%257B%250A%2520%2520var%2520a%2520%253D%2520new%2520A()%253B%250A%2520%2520var%2520b%2520%253D%2520new%2520B()%253B%250A%2520%2520ext(function%2520g()%2520%257B%2520takesA(b)%253B%2520%257D)%253B%250A%2520%2520return%2520b%253B%250A%257D%250A%250Afunction%2520takesA(%252F**%2520!A%2520*%252F%2520x)%2520%257B%257D%26input1%26conformanceConfig%26externs%3Dvar%2520ext%253B%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1
