### ISSUE TITLE
ES6 transpilation causes syntax error

### ISSUE THREAD

**Issue by fejesjoco** [google/closure-compiler#2070]
With whitespace only compilation, language_in = es6_strict, language_out = es6_strict, this code:

```js
return value => ({foo: 'bar', baz: value});
```

Is changed to:

```js
return (value) => {foo: 'bar', baz: value};
```

Adding the parens around the arrow function params is nice, but removing it from the body is not okay. The braces are parsed as a function body with higher priority, it needs to be in parens to be parsed as an object literal, which this code wants to do. Or to be absolutely correct, it may be rewritten as:

```js
return (value) => { return {foo: 'bar', baz: value} }
```

**Comment by fejesjoco** [comment]
With whitespace compilation level, is it possible not to transpile but leave the original ES6 source intact?

Even if you don't support it, can I still volunteer to try and fix it myself?

**Comment by brad4d** [comment]
There's a lot of work to be done to make the code checking passes, particularly type checking, understand ES6 features. Until that is done, we have to transpile the code before passing it to the checks.

**Comment by MatrixFrog** [comment]
We actually do kind of need to support ES6 as an output in whitespace only mode, because it's used to gather test coverage information. So it would be good to fix this, and @fejesjoco, if you want to dig into it that would be great. A lot of the logic for code printing is in https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/CodeGenerator.java -- you can see various places where we specifically check whether extra parens are needed (search for `needsParens`) so it sounds like this is one such place we overlooked.

**Comment by MatrixFrog** [comment]
Marking low-priority though since I'm pretty sure this actually won't affect coverage instrumentation, which always converts `() => someExpression` to `() => { return someExpression; }` so that it can add a call before the return.
