### ISSUE TITLE
Type Inference Fails to Find Type Information When assigned after the Var

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-compiler#2083]
Fails on both OTI and NTI:

```js
var foo;
foo = class {

  bar() {
    console.log(this.baz); // type of this is unknown
  }

  get baz() {
    return 'baz';
  }
}
```

http://closure-compiler-debugger.appspot.com/#input0%3Dvar%2520foo%253B%250Afoo%2520%253D%2520class%2520%257B%250A%250A%2520%2520bar()%2520%257B%250A%2520%2520%2520%2520console.log(this.baz)%253B%250A%2520%2520%257D%250A%250A%2520%2520get%2520baz()%2520%257B%250A%2520%2520%2520%2520return%2520'baz'%253B%250A%2520%2520%257D%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26LANG_IN_IS_ES6%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

This type of pattern is occurring during module rewriting. The pattern is specifically required because of hoisting:

```js
module.exports = Foo;
/** @constructor */
function Foo() {}
```

My current work has this rewritten to the pattern listed above.

**Comment by dimvar** [comment]
Can we change module rewriting to not produce this pattern? It's more error prone to expand what we consider a "definition" in the rest of the compiler passes.

**Comment by ChadKillingsworth** [comment]
I'm finding it pretty difficult to avoid:

```js
(function() {
  module.exports = class Foo{};
})()
```

Rewrites to:

```js
goog.provide('module$foo$');
var module$foo$;
(function() {
  module$foo$ = class {};
})()
```

**Comment by dimvar** [comment]
I was chatting w/ Ben about this. I think since goog.module and CommonJS modules are somewhat similar, it would be good to do a similar rewriting for both of them. The rewriting of goog.module avoids the issue here because it does not use an IIFE. It gives obscure names to the module-local variables. (Example)[https://closure-compiler-debugger.appspot.com/#input0%3Dgoog.module('Foo')%253B%250A%250Aclass%2520Foo%2520%257B%257D%250A%250Aclass%2520Bar%2520%257B%257D%250A%250Aexports%2520%253D%2520Foo%253B%26input1%3Dgoog.module('baz')%253B%250A%250Avar%2520Foo%2520%253D%2520goog.require('Foo')%253B%250A%250Aexports%2520%253D%2520new%2520Foo%253B%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1].

Can you land a follow-up CL to the CommonJS rewriting to avoid the IIFE?

**Comment by blickly** [comment]
I think that's what Chad has already done in https://github.com/google/closure-compiler/pull/2085
Sorry if I explained it to you wrong.

**Comment by ChadKillingsworth** [comment]
Yes after your initial response I added more logic so that I'm avoiding this case in all cases where practical. To handle the remaining cases would take a fully optimizing compiler with a control flow graph and function inlining 😼 . In the case above, the IIFE would have been pre-existing - not generated.

The cases that are left are possible, but I haven't seen in real world code:

https://github.com/ChadKillingsworth/closure-compiler/blob/03a49c300dfef7d14d368ed645ba8e3c29000fa2/test/com/google/javascript/jscomp/ProcessCommonJSModulesTest.java#L114-L125

**Comment by dimvar** [comment]
Thanks Chad!
