### ISSUE TITLE
Warning about w3c_rtc.js

### ISSUE THREAD

**Issue by 4shome** [google/closure-compiler#2091]
I found these warning when I use CC to compile JS code with webrtc code:

externs.zip//w3c_rtc.js:924: WARNING - property addEventListener on interface EventTarget is not implemented by type RTCPeerConnection
function RTCPeerConnection(configuration, constraints) {}
^

externs.zip//w3c_rtc.js:924: WARNING - property dispatchEvent on interface EventTarget is not implemented by type RTCPeerConnection
function RTCPeerConnection(configuration, constraints) {}
^

externs.zip//w3c_rtc.js:924: WARNING - property removeEventListener on interface EventTarget is not implemented by type RTCPeerConnection
function RTCPeerConnection(configuration, constraints) {}
^

This is pretty odd, since the 3 methods are defined in w3c_rtc.js

**Comment by Dominator008** [comment]
Which version of the compiler are you using?

**Comment by 4shome** [comment]
It has been there for a while (maybe from the beginning). I tried the latest release v20160911, which still has it.

**Comment by Dominator008** [comment]
Hmm, that seems unlikely. Can you try to come up with a minimal repro case?

**Comment by 4shome** [comment]
Please take a look at https://github.com/YijinLiu/closure-compiler-test
Thanks.

**Comment by 4shome** [comment]
Ping. Any updates on this?

**Comment by Dominator008** [comment]
@4shome I think the problem came from you redefining something that already exists in the externs. It confuses the typechecker.

I suggest using
```js
window['RTCPeerConnection'].prototype = webkitRTCPeerConnection.prototype;
```
as a workaround until we find a better solution.

We might change
https://github.com/google/closure-compiler/blob/b54f518b4ae5f0ec6b5503aca646110a6360dc77/externs/browser/w3c_rtc.js#L1145
to
```js
/** @const */
var webkitRTCPeerConnection = RTCPeerConnection;
```
and that should solve it, but it's unclear to me whether this aliasing is correct.

**Comment by 4shome** [comment]
Thanks. It works.
