### ISSUE TITLE
maven build broken from head

### ISSUE THREAD

**Issue by joeltine** [google/closure-compiler#2154]
As a part of our closure library travis build, we build the compiler from head. It's now failing with errors like:

 "[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:testCompile (default-testCompile) on project closure-compiler-gwt: Compilation failure: Compilation failure:
[ERROR] /home/travis/build/google/closure-compiler/test/com/google/javascript/jscomp/transpile/BaseTranspilerTest.java:[20,25] error: package org.mockito does not exist
"

For full logs see https://travis-ci.org/google/closure-library/builds/175834571

**Comment by MatrixFrog** [comment]
Looks like our internal test just does the main mvn build and not the gwt one, so we missed a few lines in the gwt POM file, and a few uses of gwt-incompatible methods.

**Comment by ChadKillingsworth** [comment]
And this is why it's important for Travis to run 👍

**Comment by MatrixFrog** [comment]
https://github.com/MatrixFrog/closure-compiler/commit/0e8ea95859458dcf864dccd7c759125d0e3378cc partially fixes this but then I still get an error for some Guava testing stuff:

[INFO] --- gwt-maven-plugin:1.0-rc-6:compile (default-compile) @ closure-compiler-gwt ---
[INFO] Compiling module com.google.JsComp
[INFO]    Tracing compile failure path for type 'com.google.javascript.jscomp.transpile.TranspileResult'
[INFO]       [ERROR] Errors in 'file:/usr/local/google/src/closure-compiler/target/classes/com/google/javascript/jscomp/transpile/TranspileResult.java'
[INFO]          [ERROR] Line 98: The method format(String, String, String, String, String) is undefined for the type String
[INFO]    Tracing compile failure path for type 'com.google.javascript.jscomp.transpile.CachingTranspiler'
[INFO]       [ERROR] Errors in 'file:/usr/local/google/src/closure-compiler/target/classes/com/google/javascript/jscomp/transpile/CachingTranspiler.java'
[INFO]          [ERROR] Line 47: No source code is available for type com.google.common.cache.CacheLoader<K,V>; did you forget to inherit a required module?
[INFO]          [ERROR] Line 35: No source code is available for type com.google.common.cache.LoadingCache<K,V>; did you forget to inherit a required module?
[INFO]          [ERROR] Line 41: No source code is available for type com.google.common.cache.CacheBuilder<K,V>; did you forget to inherit a required module?
[INFO]       [ERROR] Errors in 'file:/usr/local/google/src/closure-compiler/target/classes/com/google/javascript/jscomp/transpile/TranspileResult.java'
[INFO]          [ERROR] Line 98: The method format(String, String, String, String, String) is undefined for the type String
[INFO]    [ERROR] Aborting compile due to errors in some input files

**Comment by TimvdLippe** [comment]
(Mockito Developer) If it is possible you can already adopt Mockito 2.0. We upstreamed the upgrade from Mockito 1.8 to 2.X in Google Guava (https://github.com/google/guava/pull/2567) which did not require any codebase changes. Mockito 2 is almost fully backwards compatible. Note that instead of `mockito-all`, you should load `mockito-core` instead.

**Comment by MatrixFrog** [comment]
Oh cool. Thanks!
