### ISSUE TITLE
Caching browser externs

### ISSUE THREAD

**Issue by alubbe** [google/closure-compiler#2186]
We run the closure compiler to produce several small output files. We know of no way of asking the cli to compile multiple, independent files.

So instead we spawn separate cli processes. For each run, profiling has shown that 40-50% of the time is spent on parsing and using the 35.000+ lines of code contained in the standard browser externs. So because our files are so small (<1k lines), we got a 2x speedup by changing `env` to `CUSTOM` and loading only those few externs that we actually used. But it takes a lot of manual effort and maintenance to pursue this route.

I was wondering whether it might be possible to cache these externs instead? Something like saving to disk the produced AST and loading it back to memory on startup.

To be careful, it could be made so that the cache is only used if no additional externs are specified.

What do you think?

**Comment by ChadKillingsworth** [comment]
It's been discussed many many times (though I'm not sure that it's been in a public forum). I've been told that deserializing the AST after reading it from disk would be SLOWER.

Having a build step that converts the builtin externs to JAVA classes that can be compiled is what has been most widely tossed around. Nobody has volunteered to do that work though (and it's non-trivial).

I'm closing this issue - not because its invalid, but simply because there isn't anybody to work on it right now. If someone wants to volunteer, they are free to reopen it.

**Comment by alubbe** [comment]
Thanks for your response - that's unfortunate but understandable.

Alternatively, a solution could be to tell a single process to run multiple compilations (a.js -> a.min.js & b.js ->b.min.js, ...), all with the same externs. Is something like that possible today?

**Comment by alubbe** [comment]
Is there a way to achieve this using modules?

**Comment by ChadKillingsworth** [comment]
One of the biggest hits is the JVM startup time. You can use nailgun or drip to alleviate this issue: http://stackoverflow.com/a/22735918/1211524

**Comment by alubbe** [comment]
Thank you, I will look into that.
Just to clarify, is there a way to use modules?

**Comment by ChadKillingsworth** [comment]
No - not for externs currently.

**Comment by alubbe** [comment]
nailgun is fantastic, those small compilations now run 3-5x faster!
I had to hack the node wrapper a little bit to make it work, see https://github.com/google/closure-compiler-npm/pull/51
