### ISSUE TITLE
Add a warning for unused variables

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#222]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-compiler/issues/detail?id=891

**Comment by usmonster** [comment]
Just to revive this--was something like this ever implemented (as described in the original abovelinked issue)?

**Comment by ChadKillingsworth** [comment]
Not to my knowledge.

**Comment by concavelenz** [comment]
I think what we would want here is something much simpler than what we have for unused variable removal.  It would be too confusing to report recursively referenced but otherwise unused variables, unused values in a chain of values, etc.  So this would be simple "value read somewhere" check, which should simple for someone wanting to contribute
