### ISSUE TITLE
NTI: Another IObject regression

### ISSUE THREAD

**Issue by vobruba-martin** [google/closure-compiler#2239]
@dimvar Unfortunately the fix in 38215dead99bc9a1aaaab76f8d4e5f9a1ec4d589 introduced another regression:

```javascript
/**
 * @param {!IObject<(string|number), *>} x
 */
function fn1(x) {};

/**
 * @param {!IObject<string, *>} x
 */
function fn2(x) {
	fn1(x);
};
```
```
WARNING - Invalid type for parameter 1 of function fn1.
Expected : IObject<number|string,*>
Found    : IObject<string,*>

	fn1(x);
	    ^

0 error(s), 1 warning(s), 100.0% typed
```

**Comment by dimvar** [comment]
This is not a regression. It's expected behavior that we were not implementing correctly before. It is not allowed to pass a `IObject<string,*>` to a function that takes `IObject<number|string,*>`. The type `IObject<string,*>` can only be indexed with strings, so indexing it with a number is wrong. On the other hand, it is valid to pass `IObject<number|string,*>` to a function that takes `IObject<string,*>`, because you know it will only be indexed with string, which is a subtype of the allowed index type of `number|string`.
