### ISSUE TITLE
Support `@nosideeffects` all code (not just externs) 

### ISSUE THREAD

**Issue by mhevery** [google/closure-compiler#2256]
There are many scenarios where the developer knows that code has no side-effects but the CC fails to detect it and retains the code. 

CC already has `@nosideeffects` annotation, but that one only works in externs file. Could we make it work in normal code as well?

**Comment by ChadKillingsworth** [comment]
We have repeatedly avoided doing that. It's a huge foot-gun.

**Comment by mhevery** [comment]
Could you share the concerns which make it a foot-gun for better understanding?

**Comment by ChadKillingsworth** [comment]
```js
/** @nosideeffects */
function IHaveSideEffects() {
   document.body.innerHTML = 'Hello World';
}
IHaveSideEffects(); //this gets removed - user lied to the compiler.
```

Trivial case. This becomes VERY hard to debug the farther apart the call is from the definition. It's also not always clear to users that the function has side effects.

In general, if an annotation can be mis-used, it will be.

**Comment by mhevery** [comment]
Sure, but that is a developer bug, like many other bugs which developer can make. Alternative is that we are retaining KBs of code which are not needed and we have no tools to remove them.

**Comment by ChadKillingsworth** [comment]
There have been some strategies discussed regarding this. See #1746. However none have come to fruition. It's a huge balancing act.

**Comment by dimvar** [comment]
@mhevery I definitely agree that we should be doing better with the examples you brought up recently. We do want to eventually be able to remove this code, by improving the optimizations. This is where we would like to make improvements, e.g., by moving the side-effect calculation in the optimization loop (currently it can't happen because the pass is too slow).

But as Chad said, we don't want to solve this by introducing the annotation in the code. Optimization directives will be misused and the bugs will be very hard to diagnose. We are fine sacrificing some code size to avoid introducing even more complexity to the compiler.

**Comment by alexeagle** [comment]
I thought we had rough agreement with @blickly that after adding a warning class for usage of `@nosideeffects` in non-externs code, we could allow this.
Angular needs to tree-shake sooner, rather than wait for eventual improvements to the side-effect calculations. We have a great advantage at this moment, that closure compiler can do better than any other bundler/tree-shaker right now and there is a lot of interest.

**Comment by tadeegan** [comment]
The compiler side effects computation could definitely use some improvement.

As an alternative to adding "@nosideeffects" someone could invest time into making the PureFunctionIdentifier more accurate.  For example, the following function "f" would be marked as having side effects:

```
function f() {
  var a = 3;
  a += 5;
  return a;
}
```
  

See: https://github.com/google/closure-compiler/blob/de36c96e070dc2f9ad69fb814925af34c4d6c91d/src/com/google/javascript/jscomp/PureFunctionIdentifier.java#L58

And: https://github.com/google/closure-compiler/blob/26b48d2562494a46c74a193fd65f6be872933285/src/com/google/javascript/jscomp/NodeUtil.java#L4238


**Tests to be improved:**
https://github.com/google/closure-compiler/blob/de36c96e070dc2f9ad69fb814925af34c4d6c91d/test/com/google/javascript/jscomp/PureFunctionIdentifierTest.java#L947

https://github.com/google/closure-compiler/blob/de36c96e070dc2f9ad69fb814925af34c4d6c91d/test/com/google/javascript/jscomp/PureFunctionIdentifierTest.java#L1321

https://github.com/google/closure-compiler/blob/de36c96e070dc2f9ad69fb814925af34c4d6c91d/test/com/google/javascript/jscomp/PureFunctionIdentifierTest.java#L697



Perhaps I should open a new bug for that, or maybe there already is one...

**Comment by NMinhNguyen** [comment]
Sorry to be commenting on an old thread, but this is the only one I've found to be remotely relevant to the question I am about to ask. Babel 7 now emits `#__PURE__` annotations in order to improve tree-shake-ability when the transpiled output is consumed by Uglify. References: babel/babel#6209, babel/babel#5632, https://github.com/mishoo/UglifyJS2/commit/1e51586996ae4fdac68a8ea597c20ab170809c43, and the `side_effects` compiler option in Uglify's [README](https://github.com/mishoo/UglifyJS2#compress-options). I was wondering if Google Closure Compiler also supports or plans to support this annotation at some point in the future?
