### ISSUE TITLE
NTI: goog.forwardDeclare does not work to break circular dependencies

### ISSUE THREAD

**Issue by shicks** [google/closure-compiler#2322]
Using `goog.forwardDeclare` to import a dependent type does not work in NTI.  Consider these two files:

```js
goog.module('A');
const B = goog.require('B');
exports = class A extends B {};
```

```js
goog.module('B');
const A = goog.forwardDeclare('A');
exports = class B {
  constructor(/** A= */ a = undefined) { this.a = a; }
};
```

This results in a warning
```
b.js:2: WARNING - Required namespace "A" never defined.
const A = goog.forwardDeclare('A');
          ^^^^^^^^^^^^^^^^^^^^^^^^
```
which later causes an error
```
b.js:4: ERROR - Type annotation references non-existent type module$contents$B_A.
  constructor(/** A= */ a = undefined) { this.a = a; }
                  ^
```

**Comment by dimvar** [comment]
The problem is that module B needs to come before module A in the source, because class A extends B. The old type checker [also warns for this](https://closure-compiler-debugger.appspot.com/#input0%3Dgoog.module('A')%253B%250Aconst%2520B%2520%253D%2520goog.require('B')%253B%250Aexports%2520%253D%2520class%2520A%2520extends%2520B%2520%257B%257D%253B%250A%26input1%3Dgoog.module('B')%253B%250Aconst%2520A%2520%253D%2520goog.forwardDeclare('A')%253B%250Aexports%2520%253D%2520class%2520B%2520%257B%250A%2520%2520constructor(%252F**%2520A%253D%2520*%252F%2520a%2520%253D%2520undefined)%2520%257B%2520this.a%2520%253D%2520a%253B%2520%257D%250A%257D%253B%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1).

If you put module B first as expected, then [NTI gives no warnings](https://closure-compiler-debugger.appspot.com/#input0%3Dgoog.module('B')%253B%250Aconst%2520A%2520%253D%2520goog.forwardDeclare('A')%253B%250Aexports%2520%253D%2520class%2520B%2520%257B%250A%2520%2520constructor(%252F**%2520A%253D%2520*%252F%2520a%2520%253D%2520undefined)%2520%257B%2520this.a%2520%253D%2520a%253B%2520%257D%250A%257D%253B%250A%26input1%3Dgoog.module('A')%253B%250Aconst%2520B%2520%253D%2520goog.require('B')%253B%250Aexports%2520%253D%2520class%2520A%2520extends%2520B%2520%257B%257D%253B%250A%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1).
