### ISSUE TITLE
Can no longer call a function named `async`

### ISSUE THREAD

**Issue by anmonteiro** [google/closure-compiler#2336]
Looks like the fix to https://github.com/google/closure-compiler/issues/2244 resulted in a regression in that it disallows calling a function called `async`.

Example:

```js
var x = {async: function(){return 3;}}
x.async()
```

This now results in the following error:

```
Parse error. No newline allowed before '=>'
```

**Comment by duzun** [comment]
I'm facing a similar issue.
In an old code-base we have a function `async()`.

The code below

```js
async(5e3, [e,b], function(e,b) { b.removeChild(e); })
      ^ 
```

results in:

```
Parse error. ')' expected at line 1 character 7 in sample.js
```

**Comment by anmonteiro** [comment]
Looks like the same issue. FWIW, `async` is not a JS reserved keyword so our examples should work.

**Comment by brad4d** [comment]
I'll see what's needed to fix this.

**Comment by brad4d** [comment]
I'm most concerned with the `x.async()` case, but I cannot reproduce the error.
This compiles fine for me.

```javascript
var x = {async(){return 3;}};
x.async();
```

https://closure-compiler-debugger.appspot.com/#input0%3Dvar%2520x%2520%253D%2520%257Basync()%257Breturn%25203%253B%257D%257D%253B%250Ax.async()%253B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

The case of async used as a bare function generating an error is incorrect according to the spec, but somewhat intentional on our part, since we wanted to simplify the grammar and discourage general use of a word that is treated specially by the language as a variable name.

**Comment by anmonteiro** [comment]
It might be a bad repro on my part, sorry for misleading you there. I think what I'm actually seeing is the bare `async()` case.

WRT. your last point, I don't think introducing a breaking change would be the way to go regarding a keyword that isn't considered as reserved by the EcmaScript specification.

**Comment by MatrixFrog** [comment]
We did it for `yield` and I don't think I've heard any complaints.

https://closure-compiler-debugger.appspot.com/#input0%3Dvar%2520yield%2520%253D%25200%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

**Comment by anmonteiro** [comment]
@MatrixFrog `yield` is a reserved JavaScript keyword according to the specification. `async` isn't.

**Comment by anmonteiro** [comment]
The ClojureScript compiler is heavy reliant on the Google Closure Compiler. We're really excited about what the recent developments in processing CommonJS and ES6 modules represent for our community. However, introducing this change relating to the `async` keyword simply breaks every ClojureScript project out there using the immensely popular [`core.async`](https://github.com/clojure/core.async) library. My opinion is that, by not reserving the keyword for that usage, we could achieve backwards compatibility.

This has come up after we [upgraded to the February release](http://dev.clojure.org/jira/browse/CLJS-1954) and is now a blocker to future upgrades.

At the end of the day, this is obviously your project and you choose how to run it. I just wanted to give my perspective on what the consequences are for ClojureScript.

**Comment by MatrixFrog** [comment]
Very good to know, thank you.

**Comment by anmonteiro** [comment]
No problem, happy to give more context if needed. Looking forward to finding a solution that can serve both our use cases. Let me know if I can help further.

**Comment by ChadKillingsworth** [comment]
> We're really excited about what the recent developments in processing CommonJS and ES6 modules represent for our community.

Glad to see hard work paying off.

**Comment by anmonteiro** [comment]
@ChadKillingsworth definitely. Huge kudos to you for implementing those. We're on our way to having seamless interoperability between ClojureScript and JavaScript libraries in the very short term.

**Comment by duzun** [comment]
@brad4d 

> The case of async used as a bare function generating an error is incorrect according to the spec, but somewhat intentional on our part, since we wanted to simplify the grammar and discourage general use of a word that is treated specially by the language as a variable name.

I'm using [typeahead.js](https://github.com/corejavascript/typeahead.js/blob/master/dist/typeahead.bundle.js#L927) which contains this kind of code:

```js
    function search(query, sync, async) {
        // ...
        async(nonDuplicates);
    }
```

So the compilation of JS breaks in by project because of this lib, and I'm sure there are a lot of libraries like this one in the wild. 

I don't think it's wise to impose artificial language restrictions just to enforce best practices. It would most likely break a lot of projects somewhere in the world.

Cheers!

**Comment by brad4d** [comment]
Sounds like this is much more of a problem than `yield` was. I'm working on fixing it.

**Comment by brad4d** [comment]
fix submitted internally
This bug should automatically close with our next push to github.

**Comment by duzun** [comment]
Great!

**Comment by fearphage** [comment]
I'm still hitting this error in `1.9.495`. Can anyone confirm?

**Comment by glittershark** [comment]
@fearphage per the comments on http://dev.clojure.org/jira/browse/CLJS-1954, this won't be fixed in Clojurescript until a new version of Closure Compiler is released

**Comment by ertugrulcetin** [comment]
@fearphage Also getting the same error.

**Comment by brad4d** [comment]
The fix for this will be in the next external release.
I believe it will be out this week.
