### ISSUE TITLE
How to produce Maven-consumable artifact?

### ISSUE THREAD

**Issue by martinklepsch** [google/closure-compiler#2373]
When running `mvn -DskipTests` I get a jar that is runnable but it cannot be depended upon in an application using the compiler. Therefore the question: 

How do you build the jar that gets deployed into the Maven repository and can be depended upon via Maven/pom.xml?

/via #2372

**Comment by ChadKillingsworth** [comment]
There are multiple jars produced. One of them (shaded maybe?) doesn't have the dependencies.

**Comment by MatrixFrog** [comment]
Generally if another project depends on the compiler, they just put the dependency in their pom.xml and Maven automatically fetches the latest from Maven Central. If I'm understanding correctly, this doesn't work for you because you want to be able to make local changes to the compiler and have your other project see those changes?

**Comment by martinklepsch** [comment]
@MatrixFrog that is exactly right. I figured adding a little note in the Readme section would help so here's a PR that does this: https://github.com/google/closure-compiler/pull/2374
