### ISSUE TITLE
w3c_pointerlock.js externs not included by default.

### ISSUE THREAD

**Issue by freshp86** [google/closure-compiler#2502]
w3c_pointerlock.js appears under [contrib folder](https://github.com/google/closure-compiler/blob/27039b0c2c9905982c54b657a8664992e9e67800/contrib/externs/w3c_pointerlock.js) instead of the [externs folder](https://github.com/google/closure-compiler/tree/27039b0c2c9905982c54b657a8664992e9e67800/externs), which (I think) means that it is not included by default in the compiler's externs, since I am getting errors similar to the following

```
toolbar_manager.js:125: ERROR - Property movementX never defined on MouseEvent
            Math.sqrt(e.movementX * e.movementX + e.movementY * e.movementY);
                        ^^^^^^^^^
```

Is this intentional? The related [w3c_pointer_events.js](https://github.com/google/closure-compiler/blob/27039b0c2c9905982c54b657a8664992e9e67800/externs/browser/w3c_pointer_events.js) is included by default.

Discovered this as I am trying to compile some Chromium code that uses `movementX` and `movementY` properties of `MouseEvents`, at [crbug.com/721073](https://bugs.chromium.org/p/chromium/issues/detail?id=721073).

**Comment by MatrixFrog** [comment]
We aren't very consistent with what's included by default and what's not. We don't want to put all web APIs in the default externs because then it takes a long time to parse and analyze them all. This can add a significant amount of time, especially for small builds. On the other hand, we do want the compiler to be easy to use which means any API that a typical web app is going to use, should be in the default externs. 

I'm not familiar with the distinction between the "pointer events" API and the "pointer lock" API but it seems like it would make sense to move pointerlock into the default set if pointer events already is. If you're a Googler the easiest way to do that is to tweak the MOE configuration; let me know if you want to do that and I can show you what to do.

**Comment by freshp86** [comment]
Eh, ignore my comment about w3c_pointer_events.js.  I meant to link to [w3c_event.js](https://github.com/google/closure-compiler/blob/8ac08c03cd695b84f8a79ac3a1338172df00003f/externs/browser/w3c_event.js#L336), which defines the `MouseEvent` class definition.

The options I have is either to pass the `w3c_pointerlock.js` manually to the compiler, which would require that file to be hosted somewhere within [Chromium repo](https://cs.chromium.org/chromium/src/third_party/closure_compiler/compiler/) (does not seem to exist currently), or tweaking MOE accordingly.

The latter seems simpler, but would require pushing a closure_compiler version, and rolling it into Chromium
