### ISSUE TITLE
Caching functions adds weird/senseless code

### ISSUE THREAD

**Issue by L3P3** [google/closure-compiler#2512]
`var window_alert=window['alert'];window_alert('123');` produces `(0,window.alert)("123");` in `ADVANCED_OPTIMIZATIONS`. In `SIMPLE_OPTIMIZATIONS` or when calling `window_alert` for multiple times, it works fine.

Looks like a quick fix but I am not into GCC.
In my project, this problem appears often.

**Comment by MatrixFrog** [comment]
As far as the compiler knows, `window_alert` and `window.alert` might have subtly different behavior, if the body of `alert` referenced `this` at all. The `(0, window.alert)` thing ensures that it's called as a normal function (so that `this` will be the global object, or undefined in strict mode) rather than as a property of `window` (in which case `this` will be `window`).

If you describe why you want to alias the alert function we can probably recommend something.

**Comment by L3P3** [comment]
Oh, yes! My fault.
