### ISSUE TITLE
NTI: register properties defined with prototype assignments

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-compiler#2525]
Ran across this one in an open source library I'm consuming:

http://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540constructor%2520*%252F%250Avar%2520Foo%2520%253D%2520function%2520()%2520%257B%250A%2520%2520this.bar()%253B%250A%2520%2520this.baz()%253B%250A%257D%253B%250AFoo.prototype%2520%253D%2520%257B%250A%2520%2520bar%253A%2520function()%2520%257B%257D%252C%250A%2520%2520baz%253A%2520function()%2520%257B%250A%2520%2520%2520%2520var%2520that%2520%253D%2520this%253B%250A%2520%2520%2520%2520%255B%255D.forEach(function(value%252C%2520key)%2520%257B%250A%2520%2520%2520%2520%2520%2520that.bar()%253B%250A%2520%2520%2520%2520%257D)%253B%250A%2520%2520%257D%250A%257D%253B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

**Comment by ChadKillingsworth** [comment]
Apparently it works if the alias is marked `@const`. Feel free to close this if that's by design.

**Comment by brad4d** [comment]
sounds like a question for @dimvar 
he's out of the office for a week, though

**Comment by shicks** [comment]
Note that the same warning happens when we [don't use the alias], though that's actually an error.

Seems like any number of workarounds fixes it:
1. [const]
2. [use an arrow]
3. [don't use an object literal for the prototype][1]

I do know that NTI backs off inference a bit for mutable variables across closures, though the specific warning seems erroneous.  Workaround 3 suggests it's partly due to a lack of understanding of assigning the whole prototype at once, but [clearly] it has some understanding since it does correctly identify `bar` as a property of `Foo`, while `qux` is not.


[don't use the alias]: http://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540constructor%2520*%252F%250Avar%2520Foo%2520%253D%2520function%2520()%2520%257B%250A%2520%2520this.bar()%253B%250A%2520%2520this.baz()%253B%250A%257D%253B%250AFoo.prototype%2520%253D%2520%257B%250A%2520%2520bar%253A%2520function()%2520%257B%257D%252C%250A%2520%2520baz%253A%2520function()%2520%257B%250A%2520%2520%2520%2520%255B%255D.forEach(function(value%252C%2520key)%2520%257B%250A%2520%2520%2520%2520%2520%2520this.bar()%253B%250A%2520%2520%2520%2520%257D)%253B%250A%2520%2520%257D%250A%257D%253B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

[const]: http://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540constructor%2520*%252F%250Avar%2520Foo%2520%253D%2520function%2520()%2520%257B%250A%2520%2520this.bar()%253B%250A%2520%2520this.baz()%253B%250A%257D%253B%250AFoo.prototype%2520%253D%2520%257B%250A%2520%2520bar%253A%2520function()%2520%257B%257D%252C%250A%2520%2520baz%253A%2520function()%2520%257B%250A%2520%2520%2520%2520const%2520that%2520%253D%2520this%253B%250A%2520%2520%2520%2520%255B%255D.forEach(function(value%252C%2520key)%2520%257B%250A%2520%2520%2520%2520%2520%2520that.bar()%253B%250A%2520%2520%2520%2520%257D)%253B%250A%2520%2520%257D%250A%257D%253B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

[1]: http://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540constructor%2520*%252F%250Avar%2520Foo%2520%253D%2520function%2520()%2520%257B%250A%2520%2520this.bar()%253B%250A%2520%2520this.baz()%253B%250A%257D%253B%250AFoo.prototype.bar%2520%253D%2520function()%2520%257B%257D%253B%250AFoo.prototype.baz%2520%253D%2520function()%2520%257B%250A%2520%2520%255B%255D.forEach(function(value%252C%2520key)%2520%257B%250A%2520%2520%2520%2520this.bar()%253B%250A%2520%2520%257D)%253B%250A%257D%253B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

[use an arrow]: http://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540constructor%2520*%252F%250Avar%2520Foo%2520%253D%2520function%2520()%2520%257B%250A%2520%2520this.bar()%253B%250A%2520%2520this.baz()%253B%250A%257D%253B%250AFoo.prototype%2520%253D%2520%257B%250A%2520%2520bar%253A%2520function()%2520%257B%257D%252C%250A%2520%2520baz%253A%2520function()%2520%257B%250A%2520%2520%2520%2520%255B%255D.forEach((value%252C%2520key)%2520%253D%253E%2520%257B%250A%2520%2520%2520%2520%2520%2520this.bar()%253B%250A%2520%2520%2520%2520%257D)%253B%250A%2520%2520%257D%250A%257D%253B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

[clearly]: http://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540constructor%2520*%252F%250Avar%2520Foo%2520%253D%2520function%2520()%2520%257B%250A%2520%2520this.bar()%253B%250A%2520%2520this.baz()%253B%250A%257D%253B%250AFoo.prototype%2520%253D%2520%257B%250A%2520%2520bar%253A%2520function()%2520%257B%257D%252C%250A%2520%2520baz%253A%2520function()%2520%257B%250A%2520%2520%2520%2520%255B%255D.forEach((value%252C%2520key)%2520%253D%253E%2520%257B%250A%2520%2520%2520%2520%2520%2520this.qux()%253B%250A%2520%2520%2520%2520%257D)%253B%250A%2520%2520%257D%250A%257D%253B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

**Comment by dimvar** [comment]
Yes, using `@const` here is WAI.

But there is another issue with this code. NTI should be recognizing the `bar` definition and not saying that `bar` isn't defined anywhere. [Simplified repro](http://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540constructor%2520*%252F%250Avar%2520Foo%2520%253D%2520function%2520()%2520%257B%257D%253B%250A%250AFoo.prototype%2520%253D%2520%257B%250A%2520%2520bar%253A%2520function()%2520%257B%257D%252C%250A%2520%2520baz%253A%2520function()%2520%257B%257D%250A%257D%253B%250A%250Afunction%2520f(x)%2520%257B%250A%2520%2520return%2520x.bar()%253B%250A%257D%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1)

````
/** @constructor */
var Foo = function () {};

Foo.prototype = {
  bar: function() {},
  baz: function() {}
};

function f(x) {
  return x.bar();
}
````

I'll fix that.
