### ISSUE TITLE
[NTI] Handle block scope correctly. 

### ISSUE THREAD

**Issue by EatingW** [google/closure-compiler#2532]
Currently NTIScope is function scoped, but to handle ES6 type checking correctly we need to handle block scope.

**Comment by Dominator008** [comment]
Would it be easier if we rename variables to be unique across a function before typechecking instead?

**Comment by dimvar** [comment]
We will handle block scopes as we slowly migrate NTI to ES6. We may do it the way Michael is suggesting; that should be good enough for typechecking, even though it's not correct for the runtime semantics.

**Comment by shicks** [comment]
My understanding is that the goal is for NTI (and the rest of the compiler) to understand ES6 - so transpilation won't be necessary before typechecking.  If renaming variables isn't on, then we shouldn't be renaming them at all (obviously we do currently, but once ES6 output is done, we won't need to).

Another option is to annotate the identifier nodes with a unique name, so that the actual variable name can remain the same, but it's clear which any instance is referring to.

**Comment by Dominator008** [comment]
@shicks I was really referring to your option 2 - I meant rename them internally.

**Comment by realityforge** [comment]
@EatingW NTI was dropped so this issue should be able to be closed

**Comment by EatingW** [comment]
Thanks!
