### ISSUE TITLE
compiler ignores @export in interface

### ISSUE THREAD

**Issue by ikabirov** [google/closure-compiler#2587]
```
/** @interface */
class PlayerApi {
	/** @export */
	play() {}
	/** @export */
	pause() {}
}

/** @implements {PlayerApi} */
class Player {
	/** @override */
	play(){}
	/** @override */
	pause(){}
}
```

methods play/pause should not be renamed

**Comment by shicks** [comment]
[debugger]

This is currently WAI, in that `@export` does not do what you think it does.  `@export` is syntactic sugar for `goog.exportProperty`, which adds an alias to the property.  You need to move the interface to an extern for it to do what you're trying to do.

I've filed #2591 to track the underlying issue here.

[debugger]: https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540interface%2520*%252F%250Aclass%2520PlayerApi%2520%257B%250A%2509%252F**%2520%2540export%2520*%252F%250A%2509play()%2520%257B%257D%250A%2509%252F**%2520%2540export%2520*%252F%250A%2509pause()%2520%257B%257D%250A%257D%250A%250A%252F**%2520%2540implements%2520%257BPlayerApi%257D%2520*%252F%250Aclass%2520Player%2520%257B%250A%2509%252F**%2520%2540override%2520*%252F%250A%2509play()%257B%257D%250A%2509%252F**%2520%2540override%2520*%252F%250A%2509pause()%257B%257D%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26DISAMBIGUATE_PROPERTIES%3D1%26AMBIGUATE_PROPERTIES%3D1%26VARIABLE_RENAMING%3D1%26PROPERTY_RENAMING%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1
