### ISSUE TITLE
constant folding and PolymerRenamer

### ISSUE THREAD

**Issue by maximermilov** [google/closure-compiler#2594]
Code snippet from https://github.com/PolymerElements/app-route.git
```javascript
      observers: [
        '__tryToMatch(route.path, pattern)',
        '__updatePathOnDataChange(data.*)',
        '__tailPathChanged(tail.path)',
        '__routeQueryParamsChanged(route.__queryParams)',
        '__tailQueryParamsChanged(tail.__queryParams)',
        '__queryParamsChanged(queryParams.*)'
      ],
```
got compiled to
```javascript
observers:"__tryToMatch(route.path, pattern);__updatePathOnDataChange(data);__tailPathChanged(tail.path);__routeQueryParamsChanged(route.__queryParams);__tailQueryParamsChanged(tail.__queryParams);__queryParamsChanged(queryParams)".split(";")
```

PolymerRenamer expect observers to be array of strings (to rename function names)

I suggest disabling foldConstants if PolymerPass is enabled.

**Comment by MatrixFrog** [comment]
cc @robliao

**Comment by ChadKillingsworth** [comment]
I would love for some pressure to help push forward alternatives to all this string reflection: https://github.com/Polymer/polymer/issues/4543

**Comment by ChadKillingsworth** [comment]
If you disable foldConstants, it should only be when `--polymer_version=1`

**Comment by maximermilov** [comment]
> it should only be when --polymer_version=1

why?

**Comment by ChadKillingsworth** [comment]
Because `--polymer_version=2` will changes a lot of other semantics. I'm fairly certain you need something more than PolymerRenamer to handle the v2 style conventions and there are other people (myself included) that really want fold constants on with Polymer.

Inside Google, you are going to need to switch to a different approach for renaming polymer elements. Such as https://github.com/Banno/polymer-rename. I think @jart was also working on a solution.

**Comment by rictic** [comment]
Is there a way to disable constant folding for specific sections of code, or specific files rather than for the whole binary?

**Comment by ChadKillingsworth** [comment]
Not that I know of. We don't really support avoiding optimizations at micro levels like that. It would be easier if Polymer Renamer recognized this alternate syntax - specifically because that's really the only optimization that can occur on that type of code.

For reference, the optimization won't trigger unless it saves bytes so you'll only see it on longer arrays of strings.

**Comment by maximermilov** [comment]
> Polymer Renamer recognized this alternate syntax

I suspect other optimization can get on the way as well.
In my opinion, safer option would be to teach compiler do not touch such strings.

**Comment by ChadKillingsworth** [comment]
If you really want to address this properly, then we need to add the ability to parse observers and paths and emit the appropriate reflection calls to the PolymerPass. Someone would just need to add that ability.

Doing that would enable us to also add the necessary sink calls to prevent dead code elimination of the methods.

I'd be happy to assist or review and test the changes.

cc @azakus

**Comment by dimvar** [comment]
@maximermilov in the internal version of the compiler, you can enable/disable passes individually, so you can disable constant folding if you wish.

As Chad said, the changes to avoid this issue should happen in Polymer Renamer and/or the Polymer pass in the compiler, not in the optimizations.

**Comment by dimvar** [comment]
Chad tells me that Polymer Renamer is also incompatible with the compiler's type-based optimizations, so it sounds like some more work is needed to make Polymer Renamer compatible with advanced mode.
