### ISSUE TITLE
Latest binary v20170910 does not work on Java 7 anymore, no mention in wiki.

### ISSUE THREAD

**Issue by david-benes** [google/closure-compiler#2672]
There was an important, but undocumented change between last two releases.

The latest release v20170910 is compiled with Java 1.8, previous was 1.7.

This should be mentioned in release notes since it might be breaking change for specific environments.

**Comment by dimvar** [comment]
@blickly, who did the last external release.

**Comment by dimvar** [comment]
What is the error you are seeing? If I remember correctly, we have started using some Java 8 features in our test files recently.

**Comment by blickly** [comment]
Sorry about that. Added a line to the [release notes](https://github.com/google/closure-compiler/wiki/Releases)

**Comment by david-benes** [comment]
@dimvar This is what error we encountered:
`Unsupported major.minor version 52.0`

It is a generic error when running java binary compiled with Java 8 using some lower java runtime
(Java 7 in our case).

@blickly No harm done. We have just upgraded to Java 8 without any issues.
You might also consider updating `readme.md` in "Building it Yourself" section that says:
Note: The Closure Compiler requires Java 7 or higher.

Then we can close this.

**Comment by dimvar** [comment]
Fixed by 2a495feed94c6ffa160768d9830619259a228e4d

**Comment by juj** [comment]
Do you have more specific information as to which Java 8 version is required?

Looking at https://www.java.com/en/download/faq/release_dates.xml, a "Java 8" originally shipped in March 18, 2014, whereas latest Java 8 is "Java 8 Update 151 CPU" which shipped on October 17, 2017. This is quite a large span of release window, so it would be great to know what is the exact required minimum version so that projects that depend on Closure can document which dependency versions are needed.

A contributor accidentally updated our Emscripten project to depend on this and this broke our distributions. We are now evaluation whether this affects minimum operating system version requirements on different linux distros or macOS versions, so if you know more specifically which Java 8 is now the minimum needed version, please let me know!

**Comment by david-benes** [comment]
@juj You can look in to /pom.xml. There is a line:

`<jdk.version>1.8</jdk.version>`

It says that the project must be compiled using Java 8 and you should be fine to run it in any Java 8 runtime.
