### ISSUE TITLE
generators created by transpilation do not support the `return()` method

### ISSUE THREAD

**Issue by brad4d** [google/closure-compiler#2728]
This feature isn't needed by many cases, but some really need it.
I believe we need to do some rework to the generator transpilation that will end up making implementing this feature fairly easy.

**Comment by trxcllnt** [comment]
@brad4d I'm getting back around to this now -- thanks for following up and filing this issue.

Like I mentioned in the other thread, compiling ES6 generators to iterators without "return" methods works well in all the cases/environments I've tested. But if the "return" method is there (as is the case today), it'll get called by the runtime, and the "Not yet implemented" error is thrown.

I'd really love to move to a full closure compiler-only ES6 -> ES5 compilation instead of going through TypeScript's generator compilation, as our performance tests indicate Closure Compiler's iterators are as fast (or slightly faster) than even native ES6+ iteration.

Unfortunately, I can only test this after manually removing the error-throwing "return" methods from Closure compiler's output. I would like to avoid adding this post-compilation step to our build, as it'll be difficult to make sure things like sourcemaps are still correct.

Would you mind if I submit a PR that simply removes the error-throwing "return" method from the iterator output, with the expectation that full ES6 generator transpilation will follow up later on your/your team's timeline?

**Comment by brad4d** [comment]
This was fixed by the recent rewrite of generators transpilation.
