### ISSUE TITLE
NTI: extending a @record does not warn when overriding types.

### ISSUE THREAD

**Issue by smaren** [google/closure-compiler#2748]
[Compiler link](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250A%250A%252F**%250A%2520*%2520%2540record%250A%2520*%252F%250AMyRec%2520%253D%2520function()%2520%257B%257D%250A%250A%252F**%250A%2520*%2520%2540public%2520%257Bnumber%257D%250A%2520*%252F%250AMyRec.prototype.hat%253B%250A%250A%250A%252F**%250A%2520*%2520%2540param%2520%257B!MyRec%257D%2520rec%250A%2520*%2520%2540return%2520%257Bnumber%257D%250A%2520*%252F%250Ahat%2520%253D%2520function(rec)%2520%257B%250A%2520%2520return%2520rec.hat%252B1%253B%250A%257D%250A%250A%250A%252F**%250A%2509*%2520%2540record%250A%2520%2520*%2520%2540extends%2520%257BMyRec%257D%250A%2520%2520*%252F%250AExtRec%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%252F**%250A%2520*%2520%2540public%2520%257Bstring%257D%250A%2520*%252F%250AExtRec.prototype.hat%253B%250A%250A%250A%252F**%250A%2520*%2520%2540param%2520%257B!ExtRec%257D%2520rec%250A%2520*%2520%2540return%2520%257Bstring%257D%250A%2520*%252F%250Apat%2520%253D%2520function(rec)%2520%257B%250A%2520%2520var%2520o%2520%253D%2520hat(rec)%253B%250A%2520%2520return%2520rec.hat%2520%252B%2520'flat'%2520%252B%2520o%253B%250A%257D%250A%250Avar%2520rec%2520%253D%2520%257B%250A%2520hat%253A%2520'hat'%250A%257D%250A%250Apat(rec)%253B%250A)

When extending a `@record` structural interface with another `@record` type, it is possible to redefine the type of a property on the super.

The above code compiles with no warnings, the expected result would be an error where the `ExtRec` type overrides the `hat` property on `MyRec`

**Comment by brad4d** [comment]
Actually it looks like this bug exists in OTI but is fixed in NTI.

The link in the description is running with OTI. Here's one using the web debugger with NTI enable.d

https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540record%2520*%252F%250Avar%2520MyRec%2520%253D%2520function()%2520%257B%257D%250A%250A%252F**%2520%2540public%2520%257Bnumber%257D%2520*%252F%250AMyRec.prototype.hat%253B%250A%250A%250A%252F**%250A%2520*%2520%2540param%2520%257B!MyRec%257D%2520rec%250A%2520*%2520%2540return%2520%257Bnumber%257D%250A%2520*%252F%250Avar%2520hat%2520%253D%2520function(rec)%2520%257B%250A%2520%2520return%2520rec.hat%252B1%253B%250A%257D%250A%250A%250A%252F**%250A%2520*%2520%2540record%250A%2520*%2520%2540extends%2520%257BMyRec%257D%250A%2520*%252F%250Avar%2520ExtRec%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%252F**%250A%2520*%2520%2540public%2520%257Bstring%257D%250A%2520*%252F%250AExtRec.prototype.hat%253B%250A%250A%250A%252F**%250A%2520*%2520%2540param%2520%257B!ExtRec%257D%2520rec%250A%2520*%2520%2540return%2520%257Bstring%257D%250A%2520*%252F%250Avar%2520pat%2520%253D%2520function(rec)%2520%257B%250A%2520%2520var%2520o%2520%253D%2520hat(rec)%253B%250A%2520%2520return%2520rec.hat%2520%252B%2520'flat'%2520%252B%2520o%253B%250A%257D%250A%250Avar%2520rec%2520%253D%2520%257B%250A%2520hat%253A%2520'hat'%250A%257D%250A%250Aalert(pat(rec))%253B%250A%26input1%26conformanceConfig%26externs%3Dfunction%2520alert(msg)%2520%257B%257D%26refasterjs-template%26includeDefaultExterns%3Dtrue%26CHECK_SYMBOLS%3Dtrue%26MISSING_PROPERTIES%3Dtrue%26TRANSPILE%3Dtrue%26CHECK_TYPES%3Dtrue%26CHECK_TYPES_NEW_INFERENCE%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue
