### ISSUE TITLE
[NTI] Invalid redeclaration of method when accepting a subclass of an argument in an overriding function

### ISSUE THREAD

**Issue by rcfox** [google/closure-compiler#2759]
```
/** @constructor */
function Foo() {};

/** @constructor @extends {Foo} */
function Bar() {};

/** @constructor */
function Qux() {};

/** @constructor @extends {Qux} */
function Hap() {};

/** @param {!Qux} q */
Foo.prototype.blah = function(q) {};

/** @override @param {!Hap} h */
Bar.prototype.blah = function(h) {};
```
When I try to compile:
```
$ java -jar closure-compiler-v20171203.jar --new_type_inf test.js 
test.js:17: WARNING - Invalid redeclaration of property blah.
inherited type  : function(this:Foo,Qux): ?
overriding type : function(this:Bar,Hap): ?

Bar.prototype.blah = function(h) {};
^^^^^^^^^^^^^^^^^^

0 error(s), 1 warning(s)
```

It seems to me that a Hap should be an acceptable Qux as far as Foo is concerned.

I'm using the lastest version from the project readme:
```
$ java -jar closure-compiler-v20171203.jar --version
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20171203
Built on: 2017-12-05 14:07
```

**Comment by brad4d** [comment]
@shicks 
Do you know if supporting type narrowing on override like this is on the horizon for NTI?

**Comment by MatrixFrog** [comment]
This sounds like http://closuretools.blogspot.com/2012/06/subtyping-functions-without-poking-your.html if I'm not mistaken.

**Comment by brad4d** [comment]
Thanks @MatrixFrog 
I'll paraphrase that article for this specific case.

The example code is defining `Bar` as an extension of `Foo`.
Suppose you passed a `Bar` object, `b`, into a function that expects a `Foo`.
That's supposed to be ok, right?
But then, the function calls `b.blah(new Qux())`, and you have a runtime error because
`Bar.prototype.blah()` only knows how to handle the `Hap` subclass of `Qux`.
