### ISSUE TITLE
Dependency conflict with google/closure-compiler

### ISSUE THREAD

**Issue by PandaMonkey** [google/closure-compiler#2815]
Hi, our project encountered a dependency conflict problem----
we used com.google.code.gson:gson:2.8.2, and closure-compiler, however, duplicate classes exist in these JARs. By analzing the closure-compiler, we found that com.google.javascript:closure-compiler is a repackaged JAR, and that it contains library com.google.code.gson:gson:2.7. So the conflicting classes appear, which leads to the loaded classes are not the ones we really required. Could you please update the com.google.code.gson:gson: from 2.7 to 2.8.2? Thanks!

**Comment by PandaMonkey** [comment]
@brad4d Thanks a lot for your support.

**Comment by cnsgithub** [comment]
Hi, i'm having this problem as well. Is there a way to get or build the closure compiler jar without any dependencies packaged in the jar? 

Especially the following packages are problematic since most environments already have them in their classpath, resulting in duplicate classes.

- javax.annotation
- com.google.json

This can also cause problems if java9 jigsaw module-info.java is used.

Currently as a workaround i am removing those folders manually when a new version comes out. Thanks..

**Comment by brad4d** [comment]
In order to control internal chaos it is Google policy that all projects must use the same version of any given third party library. This means that for us to upgrade from gson 2.7 to gson 2.8.2 requires us to upgrade every other project at Google at the same time.

Since there's no actual benefit to closure-compiler in doing this work, I don't believe we'll be doing it.
We've got much bigger fish to fry.

I'm sorry this is inconvenient for folks who are trying to incorporate our compiled code into their own Java projects.

Regarding that, we will be happy to entertain pull requests that refactor our build in ways that make things more convenient for such users.
