### ISSUE TITLE
[Generators] not correct "this" binding in v20180319

### ISSUE THREAD

**Issue by teppeis** [google/closure-compiler#2873]
Degraded in v20180319
https://kangax.github.io/compat-table/es6/#test-generators_correct_this_binding

## input

```js
// functions / generators / correct "this" binding
module.exports = function() {
  function* generator() {
    yield this.x;
    yield this.y;
  }
  var iterator = { g: generator, x: 5, y: 6 }.g();
  var item = iterator.next();
  var passed = item.value === 5 && item.done === false;
  item = iterator.next();
  passed &= item.value === 6 && item.done === false;
  item = iterator.next();
  passed &= item.value === undefined && item.done === true;
  return passed;
};
```

## output
- [output in v20180204](https://github.com/teppeis/closure-compiler-es6-compat-table/blob/ce45cb1039fa6d34822c0b6c8d81356ce6baf493/es6/v20180204/functions/generators/correct_this_binding/out.js): PASS
- [output in v20180319](https://github.com/teppeis/closure-compiler-es6-compat-table/blob/ce45cb1039fa6d34822c0b6c8d81356ce6baf493/es6/v20180319/functions/generators/correct_this_binding/out.js): FAIL

**Comment by MatrixFrog** [comment]
It turns out the generator transpilation is doing things correctly but then the "fold constants" pass is producing invalid code. It didn't do this in the previous release because the generator function was brought into the object literal before "fold constants":

function *generator() {...}
{g:generator, x:5, y:6}

became

{*g() {...}, x:5, y:6}

but in the new compiler that does not happen. Will do a bisect and figure out where this changed.

**Comment by teppeis** [comment]
@MatrixFrog Fixed in v20180506. Thanks!
