### ISSUE TITLE
Assignment to properties of global object are dropped at SIMPLE_OPTIMIZATIONS level

### ISSUE THREAD

**Issue by alexp-sssup** [google/closure-compiler#2874]
My understanding is that the compiler should not remove globally visible assignment to properties at SIMPLE_OPTIMIZATION level. If that is true then there is a bug which can be triggered with this simple test case.

[closure-compiler-global-properties.js](https://d3415aa6bfa4.leaningtech.com/closure-compiler-global-properties.js)

When compiled using current master (15049ed5fbfee7149aa94f2022b6312e1ff05287) the assignment to the global object will be removed, generating invalid output.

This is my command line

```
> java -jar closure-compiler-1.0-SNAPSHOT.jar --compilation_level SIMPLE_OPTIMIZATIONS --js closure-compiler-global-properties.js --js_output_file closure-compiler-global-properties.js.out
```

This is the expected result
```
> nodejs closure-compiler-global-properties.js
{ i0: 0, i1: 0 }
{ i0: 2, i1: 3 }
```

This is the result generated by the JS output of the compiler
```
> nodejs closure-compiler-global-properties.js.out
{ i0: 0, i1: 0 }
{ i0: 0, i1: 0 }
```

The bug may be connected to the DeadPropertyAssignmentElimination pass. If I disable the pass from DefaultPassConfig.java the generated output becomes correct again.

**Comment by lauraharker** [comment]
Thanks for the detailed report, and I agree that this is a bug. This is present in r20180323 as well as head. I was also able to track this down to the DeadPropertyAssignmentEliminationPass.

It looks like the pass, when checking if a property assignment is "dead" or not, does not consider that the owner object may alias another object that later reads the property.

I suspect that we haven't hit this bug before since we usually inline all aliases of a global inside a function (the `AggressiveInlineAliases` pass). In your repro, `g` in `var g = globalObj;` is not inlined because `g` is later reassigned.

Debugger link:
https://closure-compiler-debugger.appspot.com/#input0%3Dvar%2520globalObj%253D%257Bi0%253A0%257D%253B%250Afunction%2520func(b)%250A%257B%250A%2509var%2520g%253DglobalObj%253B%250A%2509var%2520f%253Db%253B%250A%2509g.i0%253Df.i0%257C0%253B%250A%2509g%253Db%253B%250A%2509g.i0%253D0%253B%250A%257D%250Aconsole.log(globalObj)%253B%250Afunc(%257Bi0%253A2%257D)%253B%250Aconsole.log(globalObj)%253B%26input1%26conformanceConfig%26externs%3Dvar%2520console%253B%250Aconsole.log%2520%253D%2520function(s)%2520%257B%257D%26refasterjs-template%26CHECK_SYMBOLS%3Dtrue%26MISSING_PROPERTIES%3Dtrue%26TRANSPILE%3Dtrue%26CHECK_TYPES%3Dtrue%26DEAD_ASSIGNMENT_ELIMINATION%3Dtrue%26REMOVE_UNUSED_VARIABLES%3Dtrue%26COLLAPSE_PROPERTIES%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue

**Comment by lauraharker** [comment]
Submitted a fix internally. It'll be on Github later today.
