### ISSUE TITLE
Failure Perform Array Instantiation Inlining Optimization

### ISSUE THREAD

**Issue by anonyco** [google/closure-compiler#2875]
When set to the most advanced optimizations (ADVANCED_OPTIMIZATIONS), closure compiler turns the following code

```Javascript
// ==ClosureCompiler==
// @compilation_level ADVANCED_OPTIMIZATIONS
// @output_file_name default.js
// ==/ClosureCompiler==

alert((function(){
  var pathObject = [
  	"blabla"
  ];
  if (someCondition) {
    pathObject[1] = valueOne;
  } else {
    randomConditional = true;
    pathObject[1] = valueTwo;
  }
  return pathObject;
})());
```

Into the following code

```Javascript
var a=alert,b=["blabla"];someCondition?b[1]=valueOne:(randomConditional=!0,b[1]=valueTwo);a(b);
```

When, optimally, closure compiler should output the following code (which is 23% shorter).

```Javascript
alert(["blabla",someCondition?valueOne:(randomConditional=!0,valueTwo)]);
```

**Comment by lauraharker** [comment]
Closing this, as I don't believe it's actionable.

Our policy for optimization feature requests is outlined here:
https://github.com/google/closure-compiler/wiki/FAQ#how-do-i-submit-a-feature-request-for-a-new-type-of-optimization

> Sometimes we will close an optimization request as invalid, because we believe that the benefit would be too small to make it worthwhile, or because it optimizes a code pattern that shows up very rarely in real code.

This issue would be more actionable if it was about a general code pattern instead of a specific input. There will always be inputs which you can hand-optimize better than the compiler can.
