### ISSUE TITLE
No way to use Custom Module Loader

### ISSUE THREAD

**Issue by davydotcom** [google/closure-compiler#2949]
It appears the module resolution mode is fixed on newer versions. asset-pipeline has been using this library for minification and ES6-ES5 transpiling for a while now but due to limited module resolution asset-pipeline parsed the goog.require output and injected the appropriate modules where needed. This seems to error now no matter what resolution mode is specified. a custom ModuleLoaderFactory may be a way to resolve this.

**Comment by ChadKillingsworth** [comment]
At this point in time, we don't intend to expand the module resolution algorithms or support generic custom resolution. I personally have yet to be able to see a good use case.

In most other cases, a pre-compilation build step translates the custom resolution into one the compiler understands. Translating the modules into absolute paths and using the `BROWSER` mode works especially well.

I am keeping my eye on various resolution proposals that are being targeted for Node or browsers.

**Comment by davydotcom** [comment]
Use case is asset-pipeline uses a moduler resolver filesystem to resolve assets that may exist in a jar (on the classpath) or on the actual filesystem.

**Comment by thheller** [comment]
FWIW in [shadow-cljs](https://github.com/thheller/shadow-cljs) I need to fully resolve all dependencies before calling the Closure Compiler, since they are important for CLJS compilation as well. It would be nice if I could tell Closure which variable it should assign for `require("react")` for example.

The `NodeModuleResolver` did not work for me at all and doesn't support several features I [required](https://shadow-cljs.github.io/docs/UsersGuide.html#js-resolve).

Currently I'm forced to use the `BrowserModuleResolver` and replace every `require("react")` with `require("/some/filename/i-picked.js")` in the JS before passing it to Closure. Basically every require/import is replaced by an absolute path.

This works very reliably and side-steps many of the issues I had with `NodeModuleResolver` but it would be much nicer to just configure a custom ModuleLoader/Resolver.

**Comment by ChadKillingsworth** [comment]
@thheller What in particular were you missing with node module resolution?

**Comment by thheller** [comment]
@ChadKillingsworth the possibility to influence how things resolve basically. Similar to https://webpack.js.org/configuration/resolve/. For example having `react` resolve to a global `React` variable since the page already has react included from a CDN. There are also some libraries on `npm` which use node native packages but can still work in the browser using https://github.com/webpack/node-libs-browser.

`NodeModuleResolver` also does a bunch of work regarding `.json` parsing and figuring out which files to load that I have already done at the point I call the Closure Compiler. So it was much less painful going the `BrowserModuleResolver` path since replacing some strings was easy enough. Not ideal but ok.

**Comment by thheller** [comment]
Oh and https://github.com/google/closure-compiler/pull/2622

I'm actually compiling for the Browser not Node so I need support for `"browser"` aliases in `package.json`.

**Comment by ChadKillingsworth** [comment]
So I introduced a webpack module resolution which looks up modules from a map, or fails back to node module resolution if it's missing. It currently requires providing the input to the compiler via a JSON object on standard input though. That's the only way you can tell the compiler which module is which webpack id. That could be generalized to be a more generic lookup map though.

**Comment by davydotcom** [comment]
Is there a no module resolution mode like their used to be... id rather have the goog.require and goog.provide stuff go in without the module resolution so I can take care of it from the outside

**Comment by thheller** [comment]
@ChadKillingsworth yeah I understand the purpose of the webpack resolver. However if I'm pre-processing and insert absolute paths that also works. Whether I insert a absolute path or a number doesn't matter much. Ideally I just wouldn't have to pre-process at all.
