### ISSUE TITLE
'Symbol' undefined on IE 11 when using --output_wrapper

### ISSUE THREAD

**Issue by joeyparrish** [google/closure-compiler#2957]
In https://github.com/google/shaka-player/issues/1455#issuecomment-393250035 we discovered that references to `Symbol` in ES6 polyfills don't work inside our wrapper.  This seems similar to #1227.

To fix this for our project, I was able to recompile the release of the compiler we use (v20180402) after going through `src/com/google/javascript/jscomp/js/es6/` and changing references to `Symbol` to `$jscomp.global.Symbol`.

The same problem seems to be present in the latest compiler sources on `master`, as well.  Would a PR for this be welcome?

**Comment by joeyparrish** [comment]
PR #2959 created.

**Comment by tjgq** [comment]
The issue here is that your [wrapper](https://github.com/google/shaka-player/blob/master/build/wrapper.template.js) is incompatible with [`$jscomp.getGlobal`](https://github.com/google/closure-compiler/blob/36f332788d54803c3c1afe06a9d84bf4b9f4945b/src/com/google/javascript/jscomp/js/util/global.js#L44), which determines what the compiler considers to be the global object, in the following order of preference:

1. `window`, if defined and equal to `this`;
2. `global`, if defined and not null;
3. Otherwise, `this`.

Inside your wrapper, `window` is a local variable pointing to the Window object, and `this` points to variable `g` in the outer scope. Therefore `g` is deemed to be the global object, and that's where the polyfills end up being installed.

Note that your PR doesn't solve the fundamental problem: the polyfills wouldn't crash, but any references to `Symbol` in your own code would still fail on browsers without a native `Symbol`.

We could loosen the implementation of `$jscomp.getGlobal`, but I'm not sure that's the right thing to do here. Can you write your wrapper in such a way that the current logic works?

**Comment by ChadKillingsworth** [comment]
The `--isolation_mode=iife` flag is a good reference for this.

**Comment by joeyparrish** [comment]
Thanks, @tjgq & @ChadKillingsworth.  I'll see if I can fix the wrapper.

On that note, why is there no guidance for wrapper development?  Or some sample code to support popular module loaders?

**Comment by joeyparrish** [comment]
I have something working in my wrapper now.  I'll tag this issue on the change so anyone who wants to look at the details will be able to find the change.  Thanks!
