### ISSUE TITLE
Spurious "Missing return statement" warning for abstract method with default arg value

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#3004]
This code yields `Missing return statement. Function expected to return boolean.`:
``` javascript
/** @abstract */
class X {

    /**
     * @param {boolean=} x
     * @returns {boolean}
     * @abstract
     */
    selectOption(x = true) { }

}
```

Take away ` = true` for `x` and the warning magically disappears.

[Debugger](https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540abstract%2520*%252F%250Aclass%2520X%2520%257B%250A%250A%2520%2520%2520%2520%252F**%250A%2520%2520%2520%2520%2520*%2520%2540param%2520%257Bboolean%253D%257D%2520x%250A%2520%2520%2520%2520%2520*%2520%2540returns%2520%257Bboolean%257D%250A%2520%2520%2520%2520%2520*%2520%2540abstract%250A%2520%2520%2520%2520%2520*%252F%250A%2520%2520%2520%2520selectOption(x%2520%253D%2520true)%2520%257B%2520%257D%250A%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3Dtrue%26ENABLE_ALL_DIAGNOSTIC_GROUPS%3Dtrue%26CHECK_TYPES%3Dtrue%26STRICT_CHECK_TYPES%3Dtrue%26CHECK_CONSTANTS%3Dtrue%26CHECK_DEPRECATED%3Dtrue%26CHECK_ES5_STRICT%3Dtrue%26CHECK_GLOBAL_NAMES%3Dtrue%26CHECK_GLOBAL_THIS%3Dtrue%26CHECK_LINT%3Dtrue%26CHECK_MISSING_RETURN%3Dtrue%26CHECK_UNREACHABLE_CODE%3Dtrue%26CHECK_PROVIDES%3Dtrue%26CHECK_REQUIRES%3Dtrue%26CHECK_REPORT_MISSING_OVERRIDE%3Dtrue%26CHECK_SUSPICIOUS_CODE%3Dtrue%26CHECK_SYMBOLS%3Dtrue%26CHECK_VISIBILITY%3Dtrue%26MISSING_PROPERTIES%3Dtrue%26TRANSPILE%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue)

**Comment by lauraharker** [comment]
This is because of how the `CheckMissingReturn` pass handles abstract functions. Instead of checking if a function is annotated `@abstract`, it just never warns for missing returns on functions with empty bodies.
https://github.com/google/closure-compiler/blob/6250a23fc5ac60b0a34b7a44e53dc6cfd5bb075d/src/com/google/javascript/jscomp/CheckMissingReturn.java#L189

Unfortunately, we currently run this check on transpiled code, and default parameter transpilation adds a line to the body of `selectOption`.

This should fix itself once we move default param transpilation after all the checks run. We're actively working on this and it will (optimistically) happen at the end of July. For now, you can just put `@suppressMissingReturn` on the function.

If you're interested in trying to fix this earlier, I think we'd accept a PR that looks for the `@abstract` annotation in `CheckMissingReturn`.

**Comment by lauraharker** [comment]
Fixed in v20181028.
