### ISSUE TITLE
Regression: unnecessary assignment using SIMPLE_OPTIMIZATIONS

### ISSUE THREAD

**Issue by ex** [google/closure-compiler#3008]
I have updated to the latest version v20180610 from the one I was using (v20170806) and I found the code below to add an unnecessary assignment on class constructors:
```
/**
 * @constructor
 * @struct
 * @param {number} x
 * @param {number} y
 */
function Character( x, y ) {
    this.m_x = x;
    this.m_y = y;
};
/**
 * @constructor
 * @struct
 * @param {number} x
 * @param {number} y
 */
function FroggerPlayer( x, y ) {
    this.m_character = null;
    this.m_character = new Character( x, y );
};
```
Previously this code was minified to:
```
function Character(a, b) {
	this.m_x = a;
	this.m_y = b
}
function FroggerPlayer(a, b) {
	this.m_character = new Character(a, b)
};
```
But now is minified to:
```
function Character(a, b) {
	this.m_x = a;
	this.m_y = b
}
function FroggerPlayer(a, b) {
	this.m_character = null;
	this.m_character = new Character(a, b)
};
```
The compilation flags are: --language_in ECMASCRIPT5_STRICT --compilation_level SIMPLE_OPTIMIZATIONS

**Comment by lauraharker** [comment]
Assigning to myself to investigate because I suspect this is because of https://github.com/google/closure-compiler/commit/627f90f54952f0601bef6d5057675fd196d46a6b#diff-a55a956858d023be41b94bae129c5794

**Comment by lauraharker** [comment]
Ok... I confirmed this is a result of https://github.com/google/closure-compiler/commit/627f90f54952f0601bef6d5057675fd196d46a6b.

The problem here is that the compiler is unsure if `new Character(a, b)` will read  `this.m_character`. The `DeadPropertyAssignmentElimination` pass doesn't track properties globally, so it must treat any function invocation as potentially reading `this.m_character` through another reference to the `this` object.

In this particular case, though, it might (?) be safe for the compiler to assume it can remove the property write because a) we're in a constructor and b) it's on `this`.

There's already an (unused) code path in `DeadPropertyAssignmentElimination` for assuming that `this` never escapes in a constructor.
https://github.com/google/closure-compiler/blob/e5d4332b1563141b124aa183b849b2e619318b15/src/com/google/javascript/jscomp/DeadPropertyAssignmentElimination.java#L64

**Comment by ex** [comment]
Oh I see, I know this code seems silly and we have already cleaned it, but it could happens ¨naturally¨ initializing multiple times a property on a constructor without noticing it, bad practice anyways. Just wanted to be sure if  was the expected result. Should I close this issue_

**Comment by lauraharker** [comment]
Thanks for reporting the regression anyway, we definitely appreciate people making us aware of these changes. 

It would be nice to still optimize this case (both because people accidentally write code like this and because generated/partially optimized code could produce this pattern), but I doubt the code size win is large enough to be worth the effort. Could you close the issue then?

**Comment by ex** [comment]
I love the Closure compiler, no prob. 
Closing this.
