### ISSUE TITLE
Null pointer crash in v20180716

### ISSUE THREAD

**Issue by blq** [google/closure-compiler#3044]
Trying to compile "slick.core.js" from https://raw.githubusercontent.com/6pac/SlickGrid/master/slick.core.js
https://github.com/6pac/SlickGrid
Results in a null pointer compiler crash in the latest July v20180716 release. Both when run locally and in the online service.  The June v20180610 version works.

It seems like @warning_level VERBOSE might be the trigger. (using SIMPLE_OPTIMIZATIONS+ mode)

Run this ->
https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540warning_level%2520VERBOSE%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540code_url%2520https%253A%252F%252Fraw.githubusercontent.com%252F6pac%252FSlickGrid%252Fmaster%252Fslick.core.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D

**Comment by tjgq** [comment]
Smaller repro: https://closure-compiler-debugger.appspot.com/#input0%3Dfunction%2520f()%257B%257D%250A%250Avar%2520x%2520%253D%2520%257B%250A%2520%252F**%2520%2540constructor%2520*%252F%250A%2520%2520f%253A%2520f%250A%257D%253B%250A%250A%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3Dtrue%26CHECK_TYPES%3Dtrue%26TRANSPILE%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue

The problem is a missing null check for `n` [here](https://github.com/google/closure-compiler/blob/930f0c7821be4df2e567bba0f95f4db021f05b78/src/com/google/javascript/rhino/jstype/InstanceObjectType.java#L110). I'll submit a fix internally.

Incidentally, the type annotation on the [original code](https://raw.githubusercontent.com/6pac/SlickGrid/master/slick.core.js
https://github.com/6pac/SlickGrid) seem a bit off to me. Since the `GlobalEditorLock` property is a class instance, it makes no sense to annotate it with `@constructor`.
