### ISSUE TITLE
Object properties converted to variables don't respect block scope

### ISSUE THREAD

**Issue by maharmstone** [google/closure-compiler#3050]
Sorry if this issue has been filed already, but I couldn't find it anywhere.

Closure miscompiles the following code

```
for (var i = 0; i < 2; i++) {
  let obj = {};
  
  if (i == 0)
    obj.val = 1;
  
  console.log(obj.val);
}
```

as

```for(var a=0;2>a;a++){if(0==a)var b=1;console.log(b)};```

Expected output:
```
1
undefined
```

Actual output:
```
1
1
```

**Comment by lauraharker** [comment]
[Debugger repro](https://closure-compiler-debugger.appspot.com/#input0%3Dfor%2520(var%2520i%2520%253D%25200%253B%2520i%2520%253C%25202%253B%2520i%252B%252B)%2520%257B%250A%2520%2520var%2520obj%2520%253D%2520%257B%257D%253B%250A%2520%2520%250A%2520%2520if%2520(i%2520%253D%253D%25200)%250A%2520%2520%2520%2520obj.val%2520%253D%25201%253B%250A%2520%2520%250A%2520%2520console.log(obj.val)%253B%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3Dtrue%26CHECK_TYPES%3Dtrue%26TRANSPILE%3Dtrue%26COLLAPSE_PROPERTIES%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue)

With the `CollapseProperties` pass enabled, this: 
``` javascript
for (var i = 0; i < 2; i++) {
  var obj = {};
  
  if (i == 0)
    obj.val = 1;
  
  console.log(obj.val);
}
```
becomes
``` javascript
for (var i = 0; i < 2; i++) {
  if (i == 0) {
    var obj$val = 1;
  }
  console.log(obj$val);
}
```

**Comment by lauraharker** [comment]
I'm not aware of a pre-existing issue for this

**Comment by lauraharker** [comment]
It seems to me like the safest way to avoid this problem is to not collapse properties on anything defined in a loop

We already don't collapse properties on names that are set more than once not in a loop, e.g. [this is unchanged](https://closure-compiler-debugger.appspot.com/#input0%3Dvar%2520obj%2520%253D%2520%257B%257D%253B%250Aobj.val%2520%253D%25203%253B%250Aobj%2520%253D%2520%257B%257D%253B%250Aconsole.log(obj.val)%253B%26input1%26conformanceConfig%26externs%3Dvar%2520console%2520%253D%2520%257B%257D%253B%250A%250Aconsole.log%2520%253D%2520function(s)%2520%257B%257D%26refasterjs-template%26includeDefaultExterns%3Dtrue%26CHECK_TYPES%3Dtrue%26TRANSPILE%3Dtrue%26COLLAPSE_PROPERTIES%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue):
``` javascript
var obj = {};
obj.val = 3;
obj = {};
console.log(obj.val);
```

The only difficultly I can predict in landing this change would be if it causes code size regressions. Hopefully there are not too many people creating objects in loops in the global scope (since this pass doesn't run inside function scopes).

**Comment by lauraharker** [comment]
My attempted fix breaks exactly one browser test in a Google internal project with `randomvarname is not defined`, so can't land it yet. I'll debug what's going on

**Comment by concavelenz** [comment]
Yes, "collapse properties" should treat anything assigned in a loop as being defined multiple times.  Though collapsing would generally work, if it treated the initial defintion as being set to undefined:

`
for (var i = 0; i < 2; i++) {
  var obj$val = undefined;
  if (i == 0) {
    obj$val = 1;
  }
  console.log(obj$val);
}
`

**Comment by lauraharker** [comment]
Sorry for the delay - I'll try to get the fix in this week.

I'll compare results with not collapsing the object vs. initializing to undefined as John suggested.
