### ISSUE TITLE
[DEGRADE] Object.assign polyfill isn't injected by ES2018 object rest props

### ISSUE THREAD

**Issue by teppeis** [google/closure-compiler#3139]
[Input](https://github.com/teppeis/closure-compiler-es-compat-table/blob/master/es2016plus/v20181028/2018_features/object_rest_spread_properties/object_rest_properties/in.js):

```js
module.exports = () => {
  var {a, ...rest} = {a: 1, b: 2, c: 3};
  return a === 1 && rest.a === undefined && rest.b === 2 && rest.c === 3;
};
```

v20181008 injects `Object.assign` polyfill expectdly: [output](https://github.com/teppeis/closure-compiler-es-compat-table/blob/master/es2016plus/v20181008/2018_features/object_rest_spread_properties/object_rest_properties/out.js)

v20181028 doesn't: [output](https://github.com/teppeis/closure-compiler-es-compat-table/blob/master/es2016plus/v20181028/2018_features/object_rest_spread_properties/object_rest_properties/out.js)

In result, the compiled code throws `TypeError: Object function Object() { [native code] } has no method 'assign'`.

**Comment by brad4d** [comment]
I believe this is due to the transpilation of destructuring being moved after all checks, which includes it moving after the pass that injects polyfills.
It will be fixed automatically when we make the planned change to have the polyfills pass always inject all polyfills required by the difference between the input and output language modes, but that also requires changes to `RemoveUnusedCode` so it can safely remove the polyfills that aren't actually needed.

We should be able to fix this more quickly than that by changing the `es6InjectRuntimeLibraries` pass to explicitly inject the `Object.assign` polyfill.

**Comment by brad4d** [comment]
Internal Google bug created: b/119199280

**Comment by teppeis** [comment]
From v20190121, Object.assign is not injected for object spread properties too.

- [v20190106 output](https://github.com/teppeis/closure-compiler-es6-compat-table/blob/master/es2016plus/v20190106/2018_features/object_rest_spread_properties/object_spread_properties/out.js)
- [v20190121 output](https://github.com/teppeis/closure-compiler-es6-compat-table/blob/master/es2016plus/v20190121/2018_features/object_rest_spread_properties/object_spread_properties/out.js)

**Comment by teppeis** [comment]
Not yet fixed in v20191111: [input](https://github.com/teppeis/closure-compiler-es-compat-table/blob/master/es2016plus/v20191111/2018_features/object_rest_spread_properties/object_rest_properties/in.js) / [output](https://github.com/teppeis/closure-compiler-es-compat-table/blob/master/es2016plus/v20191111/2018_features/object_rest_spread_properties/object_rest_properties/out.js)

**Comment by teppeis** [comment]
Thanks!
