### ISSUE TITLE
Compiler incorrectly removes try/catch block

### ISSUE THREAD

**Issue by nbeloglazov** [google/closure-compiler#3156]
Consider following function that used to check whether passed window is cross domain or not:

```js
function canInspectWindowBad(win) {
  try {
    const unused = !!win.location.href && win['test'];
    return true;
  } catch (unusedErr) {
    return false;
  }
}
```

With advanced optimization enabled compiler thinks that this function always returns true and removes it. Slight modification to this function fixes the problem:

```js
function canInspectWindowGood(win) {
  try {
    return !!win.location.href && win['test'];
  } catch (unusedErr) {
    return false;
  }
}
```

but compiler shouldn't remove the original function in the first place. 

Here is the [full example](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F**%250A%2520*%2520%2540fileoverview%2520Case%2520to%2520reproduce%2520bug%2520in%2520js%2520compiler.%250A%2520*%252F%250A%250A%250A%252F**%250A%2520*%2520This%2520function%2520is%2520not%2520optimized%2520by%2520JS%2520compiler%2520as%2520dead%2520good%2520which%2520is%2520correct.%250A%2520*%2520%2540param%2520%257B!Window%257D%2520win%250A%2520*%2520%2540return%2520%257Bboolean%257D%250A%2520*%252F%250Afunction%2520canInspectWindowGood(win)%2520%257B%250A%2520%2520try%2520%257B%250A%2520%2520%2520%2520return%2520!!win.location.href%2520%2526%2526%2520win%255B'test'%255D%253B%250A%2520%2520%257D%2520catch%2520(unusedErr)%2520%257B%250A%2520%2520%2520%2520return%2520false%253B%250A%2520%2520%257D%250A%257D%250A%250Aif%2520(canInspectWindowGood(window))%2520%257B%250A%2520%2520console.log('should%2520be%2520kept%25201')%253B%250A%257D%2520else%2520%257B%250A%2520%2520console.log('should%2520be%2520kept%25202')%253B%250A%257D%250A%250A%252F**%250A%2520*%2520This%2520function%2520is%2520optimized%2520by%2520js%2520compiler%2520as%2520dead%2520code%253A%2520JS%2520compiler%2520thinks%250A%2520*%2520it%2520always%2520returns%2520true%2520even%2520though%2520it%2520can%2520throw%2520access%2520error%2520from%250A%2520*%2520access%2520win.location%2520or%2520win%255B'test'%255D%2520if%2520win%2520is%2520cross%2520domain.%250A%2520*%2520%2540param%2520%257B!Window%257D%2520win%250A%2520*%2520%2540return%2520%257Bboolean%257D%250A%2520*%252F%250Afunction%2520canInspectWindowBad(win)%2520%257B%250A%2520%2520try%2520%257B%250A%2520%2520%2520%2520const%2520unused%2520%253D%2520!!win.location.href%2520%2526%2526%2520win%255B'test'%255D%253B%250A%2520%2520%2520%2520return%2520true%253B%250A%2520%2520%257D%2520catch%2520(unusedErr)%2520%257B%250A%2520%2520%2520%2520return%2520false%253B%250A%2520%2520%257D%250A%257D%250A%250Aif%2520(canInspectWindowBad(window))%2520%257B%250A%2520%2520console.log('should%2520be%2520kept%25203')%253B%250A%257D%2520else%2520%257B%250A%2520%2520%252F%252F%2520This%2520is%2520removed%2520as%2520dead%2520code%2520incorrectly.%250A%2520%2520console.log('should%2520be%2520kept%25204')%253B%250A%257D%250A) on closure-compiler appspot. When advanced mode enabled it removes `console.log('should be kept 4');` from the final output.

**Comment by tjgq** [comment]
As documented in the [compiler assumptions wiki page](https://github.com/google/closure-compiler/wiki/Compiler-Assumptions), the compiler generally assumes that property reads are side effect free, which is why `!!win.location.href && win['test']` is assumed to never throw.

The canonical workaround is to wrap the expression in a call to `goog.reflect.sinkValue`, which tells the compiler that it shouldn't be subject to dead code removal.

Your second example currently works because the compiler currently isn't smart enough to determine that `return expr` is side-effect free when `expr` itself is; putting `expr` all by itself in a separate line would also work. I don't think we make any promises that either will continue working in the future, though.

The reasons for this are historical and discussed [here](https://blickly.github.io/closure-compiler-issues/#398) (also linked to from the assumptions page). In case you're interested, [this](https://github.com/google/closure-compiler/commit/ff9dc85e994c34448130ee5bb38f801ab2f6ba16) is the commit corresponding to revision r1725 mentioned at the end of the discussion.

**Comment by nbeloglazov** [comment]
Ah, good to know. Thanks for explanation, Tiago!

**Comment by jeffkaufman** [comment]
@tjgq Is there a way to tell the compiler that the expression shouldn't be subject to dead code removal without including the closure library?  AMP uses closure compiler without the library.

For now I've created https://github.com/ampproject/amphtml/pull/19632 which uses @nbeloglazov 's workaround, but without a way to tell the compiler not to remove our code it could break at any time.
