### ISSUE TITLE
INTERNAL COMPILER ERROR when using generate exports

### ISSUE THREAD

**Issue by ikabirov** [google/closure-compiler#3161]
https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%2520%2540constructor%250A%2520*%2520%2540export%250A%2520*%252F%250Afunction%2520Foo()%2520%257B%250A%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26CHECK_TYPES%3Dtrue%26TRANSPILE%3Dtrue%26CLOSURE_PASS%3Dtrue%26GENERATE_EXPORTS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue

**Comment by tjgq** [comment]
GENERATE_EXPORTS injects calls to `goog.exportSymbol`, so it needs Closure Library. Passing [`closure/goog/base.js`](https://github.com/google/closure-library/blob/master/closure/goog/base.js) to the compiler should fix this.

Nevertheless, the compiler should report an error instead of crashing.

This is Google internal issue b/68906742.

**Comment by ChadKillingsworth** [comment]
@tjgq We should inject these like a polyfill if they aren't provided as part of the compilation. That's what I did for `goog.reflect.objectProperty` in the Polymer pass.

**Comment by lauraharker** [comment]
I have a pending change to make this an error instead of a crash.

I like Chad's suggestion of injecting these methods if they're not included, but since that's more work, filed

**Comment by lauraharker** [comment]
(edited my last comment to add the link to https://github.com/google/closure-compiler/issues/3597)
