### ISSUE TITLE
Update object using spread functionality was broken

### ISSUE THREAD

**Issue by ikabirov** [google/closure-compiler#3279]
functionality was broken in commit 171b655e8abfa368f4a6c7c2b1352ea04375ae7f

Now code like this:
```
/**
 * @type {{a: number, b: number}}
 */
let x = {a: 1, b: 2}

x = {...x, b: 3}

```
produce warnings:
```
index.js:6: WARNING - assignment
found   : Object
required: {a: number, b: number}
missing : [a,b]
mismatch: []
	x = {...x, b: 3}
	^^^^^^^^^^^^^^^^
```

**Comment by brad4d** [comment]
This was an intentional change.

Although in this case the compiler can safely determine what properties are on the new value of `x`, in general this is not true. We realized that the type checking we had initially implemented for Object rest 
could be wrong in potentially dangerous ways due to the way rest and spread are defined to behave.

*   only 'own' properties are copied
*   getters / setters are not invoked

Also, all of the useful code patterns we could think of could lead to code where the compiler would not have sufficient type information ensure correctness.

We decided it was safer to always infer the result of object rest/spread to be just `Object`, so users will at least be made aware that the compiler cannot type check it correctly.
Workaround is to add a cast.

**Comment by teppeis** [comment]
FYI: In TypeScript, the code passes type checking:
https://www.typescriptlang.org/play/index.html#src=let%20x%20%3D%20%7Ba%3A%201%2C%20b%3A%202%7D%0D%0Ax%20%3D%20%7B...x%2C%20b%3A%203%7D%0D%0A 

I think the inference is not perfect but very useful in the real world.
