### ISSUE TITLE
Incorrect peephole optimisation (all targets!)

### ISSUE THREAD

**Issue by zavr-1** [google/closure-compiler#3283]
The compiler does not work correctly with `export { default as Module, OtherModule } from './mod'` which have side-effects (and capital letters are the key for some reason, because it's fine with lowercase). The `peepholeOptimizations` pass removes code that it should not remove. It affects all targets, including 2015. For example, let's have a library module:

```js
// sync.js
export default (callback) => {
  callback()
}
```

And further, a module that exports the initial function using `export { as }`:

```js
// s.js
export { default as Update } from './sync'
```

Then our source code would import the module in the following way, first correctly from the original initial function:

```js
// source.js
import Update from './sync'

let stack = 1
Update(() => {
  stack = 0
})

if (stack) throw new Error('The stack is not updated')
console.log('everything is fine')
```

When compiled in advanced mode, all is good:

```sh
java -jar /Users/zavr/node_modules/google-closure-compiler-java/compiler.jar
--compilation_level ADVANCED 
--language_out ECMASCRIPT_2015 
--module_resolution NODE 
--js source.js sync.js
```

```js
'use strict';
console.log("everything is fine");
```

However, when we change the source to import the method from the proxying library, everything becomes broken:

```js
import { Update } from './s'

let stack = 1
Update(() => {
  stack = 0
})

if (stack) throw new Error('The stack is not updated')
console.log('everything is fine')
```

```sh
java -jar /Users/zavr/node_modules/google-closure-compiler-java/compiler.jar 
--compilation_level ADVANCED 
--language_out ECMASCRIPT_2015 
--module_resolution NODE 
--js source.js s.js sync.js
```

```js
'use strict';
throw Error("The stack is not updated");
```

## peepholeOptimizations yields:

The problem was uncovered with `--print_source_after_each_pass`. At some point we have:

```js
// ************************************

// earlyInlineVariables yields:
// ************************************
'use strict';
var $jscompDefaultExport$$module$sync = callback$jscomp$48 => {
  callback$jscomp$48();
};
let stack$$module$source = 1;
({get Update() {
  return $jscompDefaultExport$$module$sync;
}}).Update(() => {
  stack$$module$source = 0;
});
if (stack$$module$source) {
  throw new Error("The stack is not updated");
}
console.log("everything is fine");

// ************************************

// peepholeOptimizations yields:
// ************************************
'use strict';
var $jscompDefaultExport$$module$sync = callback$jscomp$48 => {
  callback$jscomp$48();
};
let stack$$module$source = 1;
(function() {
  return $jscompDefaultExport$$module$sync;
})();
if (stack$$module$source) {
  throw Error("The stack is not updated");
}
console.log("everything is fine");

// ************************************
```

So that the optimiser removes the call to the `Update` function. It is a pretty serious offence and it prevents ~~any~~ side-effects producing code that has `export { as }` from working correctly, regardless of the target! It doesn't matter whether it is `export { default as ... } from` or `export { Module } from` because in the end `earlyInlineVariables` changes 
```js
var module$s = {get Update() {
  return Update$$module$sync;
}};
let stack$$module$extract = 1;
module$s.Update(() => {
  stack$$module$extract = 0;
});
```
to
```js
({get Update() {
  return Update$$module$sync;
}}).Update(() => {
  stack$$module$extract = 0;
});
```
which is not handled correctly by `peephole` pass. 

---
## Lowercase and Uppercase
When the module starts with Upper-case, there's this bug. When they start with lower-case, there's no bug 🤣 
### Uppercase
```js
// earlyInlineVariables yields:
// ************************************
var $jscompDefaultExport$$module$t$modules$sync = function(callback$jscomp$48) {
  callback$jscomp$48();
};
var stack$$module$t$modules$index = 1;
({get Update() {
  return $jscompDefaultExport$$module$t$modules$sync;
}}).Update(function() {
  stack$$module$t$modules$index = 0;
});
if (stack$$module$t$modules$index) {
  throw new Error("The stack is not updated");
}
console.log("everything is fine");

// ************************************

// peepholeOptimizations yields:
// ************************************
var $jscompDefaultExport$$module$t$modules$sync = function(callback$jscomp$48) {
  callback$jscomp$48();
};
var stack$$module$t$modules$index = 1;
(function() {
  return $jscompDefaultExport$$module$t$modules$sync;
})();
if (stack$$module$t$modules$index) {
  throw Error("The stack is not updated");
}
console.log("everything is fine");
```
### lowercase 
```js
// earlyInlineVariables yields:
// ************************************
var $jscompDefaultExport$$module$t$modules$sync = function(callback$jscomp$48) {
  callback$jscomp$48();
};
var stack$$module$t$modules$index = 1;
({get update() {
  return $jscompDefaultExport$$module$t$modules$sync;
}}).update(function() {
  stack$$module$t$modules$index = 0;
});
if (stack$$module$t$modules$index) {
  throw new Error("The stack is not updated");
}
console.log("everything is fine");

// ************************************

// peepholeOptimizations yields:
// ************************************
var $jscompDefaultExport$$module$t$modules$sync = function(callback$jscomp$48) {
  callback$jscomp$48();
};
var stack$$module$t$modules$index = 1;
(function() {
  return $jscompDefaultExport$$module$t$modules$sync;
})()(function() {
  stack$$module$t$modules$index = 0;
});
if (stack$$module$t$modules$index) {
  throw Error("The stack is not updated");
}
console.log("everything is fine");
```

--- 

I don't know what happen above with the upper/lower-case, but it's not just the case with uppercase (pun unintended) .
```js
const f = () => console.log(10)
;({ get b() { return f } }).b()
```
will be wrong, with no code produced. The problem is in the folding of the getter like a normal property 
 
```js
// Es6RewriteBlockScopedDeclaration yields:
// ************************************
var f = function() {
  return console.log(10);
};
({get b() {
  return f;
}}).b();

// ************************************

// peepholeOptimizations yields:
// ************************************
var f = function() {
  return console.log(10);
};
(function() {
  return f;
})();

// ************************************
```

and it's really difficult to debug the Java source,
```fs
Pass did not update source getters / setters
Not true that <{B=GETTER_ONLY}> is equal to <{}>. It has the following entries with unexpected keys: {B=GETTER_ONLY}
	at com.google.javascript.jscomp.CompilerTestCase.testInternal(CompilerTestCase.java:1641)
	at com.google.javascript.jscomp.CompilerTestCase.testInternal(CompilerTestCase.java:1301)
	at com.google.javascript.jscomp.CompilerTestCase.testInternal(CompilerTestCase.java:2328)
	at com.google.javascript.jscomp.CompilerTestCase.test(CompilerTestCase.java:2294)
	at com.google.javascript.jscomp.CompilerTestCase.testSame(CompilerTestCase.java:1379)
	at com.google.javascript.jscomp.PeepholeRemoveDeadCodeTest.testUpperCase(PeepholeRemoveDeadCodeTest.java:1365)
```
for
```java
@Test
  public void testUpperCase() {
    test("var a=1; ({ get B() { return () => { a=0; } } }).B()", "a=0");
  }
```

**Comment by EatingW** [comment]
Created Google internal issue http://b/129139679

**Comment by lauraharker** [comment]
Your original `export ... from` issue might have been fixed by @jplaisted's recent change https://github.com/google/closure-compiler/commit/0393c80ca01b6b861376dad7f91043a38bb37dc0.

This change stops the compiler from creating getters when rewriting `export ... from`.

@zavr-1 can you see if that commit fixed your original issue?

As for the broader issue with getter/setter optimizations: @concavelenz is working on rolling forward a change that will recognize when getter/setter accesses have side effects. Unfortunately this change is tricky to land. Someone else tried last year, but had to roll back because the change increased code size for a lot of internal projects.

I'll comment more on your PR.

**Comment by zavr-1** [comment]
@lauraharker thank you I have checked the reset changes and they do indeed solve the problem. For completeness, it would be great to understand what was the factor leading to incorrect peephole in case of Uppercase, but not with the lowercase... as seen with the line `;({ get b() { console.log } }).b` it doesn't matter there, but I wonder why in the actual example there're two different outcomes.

**Comment by jplaisted** [comment]
> This change stops the compiler from creating getters when rewriting export ... from.

Small correction: it still generates the getters, but shouldn't need to reference them anymore in _most_ cases. If you did something silly like this then the getters need to stick around:

```
import * as m from 'module';
for (const key in m) {
  console.log(m[key]);
}
```

**Comment by lauraharker** [comment]
Thanks for the correction, @jplaisted.

@zavr-1 the underlying issue isn't an uppercase/lowercase different, but it's because there's some externs method called `update` with side effect. The compiler treats the `update` getter as having side effects because it coalesces side effects for all same-named properties.

Here are two similar examples in the debugger.
[with side effect computation](https://closure-compiler-debugger.appspot.com/#input0%3Dvar%2520%2524jscompDefaultExport%2524%2524module%2524t%2524modules%2524sync%2520%253D%2520function(callback%2524jscomp%252448)%2520%257B%250A%2520%2520callback%2524jscomp%252448()%253B%250A%257D%253B%250Avar%2520stack%2524%2524module%2524t%2524modules%2524index%2520%253D%25201%253B%250A(%257Bget%2520update()%2520%257B%250A%2520%2520return%2520%2524jscompDefaultExport%2524%2524module%2524t%2524modules%2524sync%253B%250A%257D%257D).update(function()%2520%257B%250A%2520%2520stack%2524%2524module%2524t%2524modules%2524index%2520%253D%25200%253B%250A%257D)%253B%250Aif%2520(stack%2524%2524module%2524t%2524modules%2524index)%2520%257B%250A%2520%2520throw%2520new%2520Error(%2522The%2520stack%2520is%2520not%2520updated%2522)%253B%250A%257D%250Aconsole.log(%2522everything%2520is%2520fine%2522)%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26CHECK_TYPES%3Dtrue%26COMPUTE_FUNCTION_SIDE_EFFECTS%3Dtrue%26FOLD_CONSTANTS%3Dtrue%26INLINE_FUNCTIONS%3Dtrue%26INLINE_VARIABLES%3Dtrue%26REMOVE_DEAD_CODE%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue)
[without side effect computation](https://closure-compiler-debugger.appspot.com/#input0%3Dvar%2520%2524jscompDefaultExport%2524%2524module%2524t%2524modules%2524sync%2520%253D%2520function(callback%2524jscomp%252448)%2520%257B%250A%2520%2520callback%2524jscomp%252448()%253B%250A%257D%253B%250Avar%2520stack%2524%2524module%2524t%2524modules%2524index%2520%253D%25201%253B%250A(%257Bget%2520update()%2520%257B%250A%2520%2520return%2520%2524jscompDefaultExport%2524%2524module%2524t%2524modules%2524sync%253B%250A%257D%257D).update(function()%2520%257B%250A%2520%2520stack%2524%2524module%2524t%2524modules%2524index%2520%253D%25200%253B%250A%257D)%253B%250Aif%2520(stack%2524%2524module%2524t%2524modules%2524index)%2520%257B%250A%2520%2520throw%2520new%2520Error(%2522The%2520stack%2520is%2520not%2520updated%2522)%253B%250A%257D%250Aconsole.log(%2522everything%2520is%2520fine%2522)%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26CHECK_TYPES%3Dtrue%26FOLD_CONSTANTS%3Dtrue%26INLINE_FUNCTIONS%3Dtrue%26INLINE_VARIABLES%3Dtrue%26REMOVE_DEAD_CODE%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue)

Note that turning on COMPUTE_SIDE_EFFECTS triggers this bug. However, if we add an externs class with a method `update`, this bug goes away:
[with side effect computation + `update` method](https://closure-compiler-debugger.appspot.com/#input0%3Dvar%2520%2524jscompDefaultExport%2524%2524module%2524t%2524modules%2524sync%2520%253D%2520function(callback%2524jscomp%252448)%2520%257B%250A%2520%2520callback%2524jscomp%252448()%253B%250A%257D%253B%250Avar%2520stack%2524%2524module%2524t%2524modules%2524index%2520%253D%25201%253B%250A(%257Bget%2520update()%2520%257B%250A%2520%2520return%2520%2524jscompDefaultExport%2524%2524module%2524t%2524modules%2524sync%253B%250A%257D%257D).update(function()%2520%257B%250A%2520%2520stack%2524%2524module%2524t%2524modules%2524index%2520%253D%25200%253B%250A%257D)%253B%250Aif%2520(stack%2524%2524module%2524t%2524modules%2524index)%2520%257B%250A%2520%2520throw%2520new%2520Error(%2522The%2520stack%2520is%2520not%2520updated%2522)%253B%250A%257D%250Aconsole.log(%2522everything%2520is%2520fine%2522)%253B%26input1%26conformanceConfig%26externs%3Dclass%2520Foo%2520%257B%250A%2520%2520update()%2520%257B%257D%250A%257D%26refasterjs-template%26CHECK_TYPES%3Dtrue%26COMPUTE_FUNCTION_SIDE_EFFECTS%3Dtrue%26FOLD_CONSTANTS%3Dtrue%26INLINE_FUNCTIONS%3Dtrue%26INLINE_VARIABLES%3Dtrue%26REMOVE_DEAD_CODE%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue).

**Comment by zavr-1** [comment]
Oh wow I would've never figured it out on my own, thanks, now I've got peace of mind :)

**Comment by lauraharker** [comment]
I'm closing this issue since original issue with ES modules is resolved.

Just opened https://github.com/google/closure-compiler/issues/3296 to track the broader issue of getter/setter optimizations.
