### ISSUE TITLE
Unable to compile array spread

### ISSUE THREAD

**Issue by Getfree** [google/closure-compiler#3298]
**Input.js**
```
let a ;
[].push( ... a || [] ) ;
```

**Command line:**
```
java.exe -jar closure-compiler-v20190301.jar --language_out NO_TRANSPILE -O SIMPLE  --js_output_file output.js input.js
```

**Result:**

> ERROR - Attempted to run pass "normalize" on input with features it does not support. Running pass anyway.
> Unsupported features: [object literals with spread, object pattern rest, async generator functions, for-await-of loop, RegExp flag 's', RegExp Lookbehind, RegExp named groups, RegExp unicode property escape]

This error didn't occur on previous versions. At least version v20190121 was working ok with this code.

**Comment by blickly** [comment]
Hmm, sounds like maybe we updated the value of --language_in, so that now setting --language_out=NO_TRANSPILE is requesting a different output language version than previously.

@nreid260, do you know offhand if there was a change like that recently?

**Comment by blickly** [comment]
Created internal issue http://b/129430418

**Comment by nreid260** [comment]
In a recent version of the compiler we added a diagnostic for when passes were requested to run over code with features they might not support. That's the message you're seeing. Up until that version, there had been a log message indicating the same thing, but it was non-blocking and easy to miss.

Two solutions are available:
  - Update to a newer release of the compiler in which all passes support spread (the latest one should)
  - Lower your --language_out, so that spread is transpiled away before the failing pass runs

**Comment by Getfree** [comment]
I've just tried the new version released yesterday and it indeed solved the problem.
