### ISSUE TITLE
dangerous use of the global this object when function's type was annotated

### ISSUE THREAD

**Issue by zavr-1** [google/closure-compiler#3343]
I'm trying to make the function to have `this` by defining it in its type.

```js
/**
 * @type {function(this:{hello:string})}
 */
function test() {
  console.log(this.hello)
}

test.call({ hello: 'world' })
```
However, I get an error. Is this meant to happen despite me giving the hint as to what `this` is going to be ? 
```
t/this.js:5: WARNING - dangerous use of the global this object
  console.log(this.hello)
              ^^^^

0 error(s), 1 warning(s), 100.0% typed
```

 Basically my function must adhere to an interface but can have a custom `this`. When i define it like 
```js
/**
 * @this {{hello:string}}
 * @type {_functionInterface}
 */
function test() {
  console.log(this.hello)
}
```
I get another error because the annotations are incompatible (can't use 2 together). Just have to suppress the `globalThis` for now.

**Comment by brad4d** [comment]
I believe this is what you meant to do.

```javascript
/**
 * @this {{hello:string}}
 */
function test() {
  console.log(this.hello);
}

test.call({ hello: 'world' });
```

You don't generally want to use `@type` when declaring a function.
Use `@this`, `@param`, and `@return` as needed instead.

https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler

**Comment by zavr-1** [comment]
@brad4d why cannot I not annotate the function type? As I said, I want functions to adhere to an interface. Otherwise I would have to annotate each function with the same `@this`, `@param` and `@return`. Also the compiler doesn't work in my case:
```js
/**
 * @type {Rule}
 */
const rule = {
  re: /(hello) world/,
  replacement,
}

/**
 * @this {ReplacerInterface}
 * @param {string} match
 * @param {string} hello
 * @returns {string}
 */
function replacement(match, hello) {
  this.emit('match', match)
  return `the match was "${match}": ${hello}`
}

/**
 * @type {Rule}
 */
const rule2 = {
  re: /(hello) (world)/i,
  replacement: replacement2,
}

/**
 * @this {ReplacerInterface}
 * @param {string} match
 * @param {string} hello
 * @param {string} world
 * @returns {string}
 */
function replacement2(match, hello, world) {
  this.emit('match (i)', match)
  return `the match was "${match}": ${hello} ${world}`
}

/** @implements {ReplacerInterface} */
class Replacer {
  emit(i) {
    console.log('the emitted match is %s', i)
  }
}
const replacer = new Replacer()

console.log('hello world'.replace(rule.re, rule.replacement.bind(replacer)))
console.log('HELLO WORLD'.replace(rule2.re, rule2.replacement.bind(replacer)))
```
```js
/**
 * @interface
 */
var ReplacerInterface = function() {}
/** @type {function(string, ...*)} */
ReplacerInterface.prototype.emit = function () {}

/**
 * @typedef {{re:!RegExp, replacement: function(this:ReplacerInterface, ...string): string}}
 */
var Rule
```

**Comment by brad4d** [comment]
Created internal issue http://b/131248506

**Comment by brad4d** [comment]
OK, I see the issue now.

The problem code is here.
https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/CheckGlobalThis.java#L95

It's only looking at the JSDoc on the function specifically for an `@this` annotation (among other things),
so it misses the `@type` case. The pass runs as part of the "suspiciousCode" pass which goes after type checking, so it could definitely us the `JSType` on the node, when it exists for a more robust check.

To fix this bug for the case where type checking is disabled, it will be necessary to add logic that looks for an `@type` annotation, parses it, then looks inside it for a defined type for `this`. Since that will work with or without type checking enabled, that's probably the way to go.

I can't give fixing this a high priority relative to other things, because it represents a rather unusual use-case, but this would be a good first-fix for someone, so I've marked it "Help wanted".

By "unusual use case" I mean that this is a problem when you want to define "loose" functions that expect to be called with a `this` supplied. That's not a code pattern we want to encourage.
Why not just define the function to take the `ReplacerInterface` object as its first argument?

**Comment by zavr-1** [comment]
@brad4d , Thank you, to answer your question I don't want to pass `ReplacerInterface` as the first argument because not all replacers will need to access it. I have a library that binds all replacement rules to a constructor, so that typically _if_ functions want to access this they will have a set of APIs from the interface, but they might choose to extend the interface to add other methods. I admit I could add it as the first argument it's true I just feel like I can put `meta` APIs in `this` and "pure" arguments can come directly as args if that makes sense. I see what you mean by this type of programming, using `this` as another argument, but sometimes it syntactically sugars up programming, e.g., 
```js
function plain (interface, match, group) {
  // no access to the interface is needed
  return group
}
function access (interface, match, group, position) {
  this.emit(match, position)
  return group
}
function access (interface, match, group, position, string) {
  this.extendedAPI(parse(match, string, position))
  return match
}
```

**Comment by brad4d** [comment]
@zavr-1, I have other suggestions to make for your case, but I don't want to make them here, since that discussion is likely to drown out the information about the issue being tracked here.

If you'd like to discuss it further, you could post your design problem as a question on
https://groups.google.com/forum/#!forum/closure-compiler-discuss
