### ISSUE TITLE
Static Methods Are Dropped On Externalised Interfaces

### ISSUE THREAD

**Issue by zavr-1** [google/closure-compiler#3447]
The compiler wouldn't keep static methods even though they are defined in externs. 

<table>
<tr><th>Externs</th><th>Source</th></tr>
<tr>
<td>

```js
/**
 * @fileoverview
 * @externs
 */

/**
 * @interface
 */
var Test

/**
 * @param {string} test
 */
Test.staticMethod = function(test) {}
/**
 * @param {string} test
 */
Test.prototype.api = function(test) {}

var module
/** @type {!Object} */
module.exports
```
</td>
<td>

```js
import './externs'

/**
 * @implements {Test}
 */
class Example {
  api(test) {
    console.log(test)
  }
  /** @nocollapse */
  static staticMethod(test) {
    console.error(test)
  }
}

module.exports = Example
```

</td>
</tr>
</table>

**OUTPUT**
```js
'use strict';
class b {
  api(a) {
    console.log(a);
  }
  static a(a) {
    console.error(a);
  }
}
module.exports = b;
```

```
java -jar google-closure-compiler-java/compiler.jar --compilation_level \
ADVANCED --language_out ECMASCRIPT_2017 --formatting \
PRETTY_PRINT --js_output_file t/c.js 
--module_resolution NODE --js \
t/index.js t/externs.js
```

The title says "dropped", and if there was no `nocollapse`, the static method would have been removed. The workaround is to write 

<table>
<tr><th>Workaround</th><th>Compiled</th></tr>
<tr>
<td>

```js
  /** 
    * @nocollapse
    * @suppress {checkTypes}
    */
  static 'staticMethod'(test) {
    console.error(test)
  }
```
</td>
<td>

```js
'use strict';
class b {
  api(a) {
    console.log(a);
  }
  static ["staticMethod"](a) {
    console.error(a);
  }
}
module.exports = b;
```
</td></tr></table>

OK the static method is not used, but nor is the instance method -- they should both be present, unless I understand wrongly what effect the `Test.staticMethod` has in externs.

**Comment by zavr-1** [comment]
I thought the following might work, but it also drops the method from the output.
```js
/**
 * @interface
 */
class Test {
  /**
   * @param {string} test
   */
  static staticMethod(test) {}
  /**
   * @param {string} test
   */
  api(test) {}
}
```

**Comment by tjgq** [comment]
Created Google internal issue b/138790032

**Comment by jplaisted** [comment]
I think Closure allows concrete static fields / methods on interfaces. So `Example` only inherits `Test`'s instance fields / methods, not its statics. Those are considered concrete on `Test` and not part of the interface.

Try using `@export` instead of `@nocollapse`.

**Comment by shicks** [comment]
That's right, good catch - implementing an interface is only about the instance.

`@export` may not be what you want, either.  I'm not sure if there is way to write what you want.  Effectively you need to define an extern'd interface for the static part of the class, and then you'd want to declare the class itself as an instance of that interface.  But that could break other parts, so it's not great.

Abstract classes *do* keep their statics along, but you can't extend an extern class, since it doesn't actually exist.  Possibly you could fake it with `@extends` but no `extends` clause, though that might also cause an error.  There's talk about allowing to "implement" a class (a la TypeScript) but we don't have anything concrete for that.

I would consider the bug here that we just don't have a way to write this right now.  But I'm also not optimistic about being able to make it possible, since it seems like it will require a pretty significant architectural change.

**Comment by zavr-1** [comment]
@shicks OK thanks friend can you explain though why does my staticMethod gets renamed into `a` even though the property is defined in externs? I thought that any properties that are defined in externs will never get renamed and so far it's been the case! i.e., nevermind typechecking, but the renaming should not really happen

**Comment by brad4d** [comment]
@zavr-1
The renaming happens because the compiler doesn't believe there is any relationship between `Test.staticMethod` and `Example.staticMethod`.

I hope this example will make this clearer.

https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%2520%2540implements%2520%257BTest%257D%250A%2520*%252F%250Aclass%2520Example%2520%257B%250A%2520%2520%252F%252F%2520this%2520is%2520an%2520instance%2520method%252C%2520so%2520the%2520%2540implements%250A%2520%2520%252F%252F%2520above%2520tells%2520the%2520compiler%2520it%2520is%2520an%2520implementation%2520of%250A%2520%2520%252F%252F%2520Test.prototype.api%250A%2520%2520api(test)%2520%257B%250A%2520%2520%2520%2520console.log(test)%250A%2520%2520%257D%250A%250A%2520%2520%252F%252F%2520The%2520compiler%2520only%2520expects%2520non-static%2520methods%2520on%250A%2520%2520%252F%252F%2520interfaces%252C%2520so%2520the%2520compiler%2520doesn't%2520believe%2520there%2520is%250A%2520%2520%252F%252F%2520any%2520relationship%2520between%2520Test.staticMethod%2520and%250A%2520%2520%252F%252F%2520Example.staticMethod%250A%2520%2520%252F%252F%250A%2520%2520%252F%252F%2520The%2520compiler%2520will%2520feel%2520free%2520to%2520rename%2520this%2520method.%250A%2520%2520static%2520staticMethod(test)%2520%257B%250A%2520%2520%2520%2520console.error(test)%250A%2520%2520%257D%250A%257D%250A%250AExample.staticMethod('hi')%253B%26input1%26conformanceConfig%26externs%3D%252F**%250A%2520*%2520%2540fileoverview%250A%2520*%2520%2540externs%250A%2520*%252F%250A%250Avar%2520console%253B%250A%252F**%250A%2520*%2520%2540param%2520%257B...*%257D%2520args%250A%2520*%252F%250Aconsole.log%2520%253D%2520function(...args)%2520%257B%257D%250A%252F**%250A%2520*%2520%2540param%2520%257B...*%257D%2520args%250A%2520*%252F%250Aconsole.error%2520%253D%2520function(...args)%2520%257B%257D%250A%250A%252F**%250A%2520*%2520%2540interface%250A%2520*%252F%250Avar%2520Test%250A%250A%252F**%250A%2520*%2520%2540param%2520%257Bstring%257D%2520test%250A%2520*%252F%250ATest.staticMethod%2520%253D%2520function(test)%2520%257B%257D%250A%250A%252F**%250A%2520*%2520%2540param%2520%257Bstring%257D%2520test%250A%2520*%252F%250ATest.prototype.api%2520%253D%2520function(test)%2520%257B%257D%250A%250A%250Avar%2520module%250A%252F**%2520%2540type%2520%257B!Object%257D%2520*%252F%250Amodule.exports%26refasterjs-template%26includeDefaultExterns%3Dtrue%26CHECK_TYPES%3Dtrue%26DISAMBIGUATE_PROPERTIES%3Dtrue%26VARIABLE_RENAMING%3Dtrue%26PROPERTY_RENAMING%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue

**Comment by brad4d** [comment]
This debugger example confirms that using `@export` will keep the static method from being renamed.

https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%2520%2540implements%2520%257BTest%257D%250A%2520*%252F%250Aclass%2520Example%2520%257B%250A%2520%2520%252F%252F%2520this%2520is%2520an%2520instance%2520method%252C%2520so%2520the%2520%2540implements%250A%2520%2520%252F%252F%2520above%2520tells%2520the%2520compiler%2520it%2520is%2520an%2520implementation%2520of%250A%2520%2520%252F%252F%2520Test.prototype.api%250A%2520%2520api(test)%2520%257B%250A%2520%2520%2520%2520console.log(test)%250A%2520%2520%257D%250A%250A%2520%2520%252F%252F%2520The%2520compiler%2520only%2520expects%2520non-static%2520methods%2520on%250A%2520%2520%252F%252F%2520interfaces%252C%2520so%2520the%2520compiler%2520doesn't%2520believe%2520there%2520is%250A%2520%2520%252F%252F%2520any%2520relationship%2520between%2520Test.staticMethod%2520and%250A%2520%2520%252F%252F%2520Example.staticMethod%250A%2520%2520%252F%252F%250A%2520%2520%252F%252F%2520The%2520compiler%2520will%2520feel%2520free%2520to%2520rename%2520this%2520method.%250A%2520%2520%252F**%2520%2540export%2520*%252F%250A%2520%2520static%2520staticMethod(test)%2520%257B%250A%2520%2520%2520%2520console.error(test)%250A%2520%2520%257D%250A%257D%250A%250AExample.staticMethod('hi')%253B%26input1%26conformanceConfig%26externs%3D%252F**%250A%2520*%2520%2540fileoverview%250A%2520*%2520%2540externs%250A%2520*%252F%250A%250Avar%2520console%253B%250A%252F**%250A%2520*%2520%2540param%2520%257B...*%257D%2520args%250A%2520*%252F%250Aconsole.log%2520%253D%2520function(...args)%2520%257B%257D%250A%252F**%250A%2520*%2520%2540param%2520%257B...*%257D%2520args%250A%2520*%252F%250Aconsole.error%2520%253D%2520function(...args)%2520%257B%257D%250A%250A%252F**%250A%2520*%2520%2540interface%250A%2520*%252F%250Avar%2520Test%250A%250A%252F**%250A%2520*%2520%2540param%2520%257Bstring%257D%2520test%250A%2520*%252F%250ATest.staticMethod%2520%253D%2520function(test)%2520%257B%257D%250A%250A%252F**%250A%2520*%2520%2540param%2520%257Bstring%257D%2520test%250A%2520*%252F%250ATest.prototype.api%2520%253D%2520function(test)%2520%257B%257D%250A%250A%250Avar%2520module%250A%252F**%2520%2540type%2520%257B!Object%257D%2520*%252F%250Amodule.exports%253B%250A%250A%252F%252F%2520needed%2520in%2520this%2520context%2520for%2520goog.exportProperty%250Avar%2520goog%2520%253D%2520%257B%257D%253B%250A%252F**%250A%2520*%2520%2540param%2520%257B%253F%257D%2520obj%250A%2520*%2520%2540param%2520%257Bstring%257D%2520propName%250A%2520*%2520%2540param%2520%257B%253F%257D%2520value%250A%2520*%252F%250Agoog.exportProperty%2520%253D%2520function(obj%252C%2520propName%252C%2520value)%2520%257B%257D%26refasterjs-template%26includeDefaultExterns%3Dtrue%26CHECK_TYPES%3Dtrue%26DISAMBIGUATE_PROPERTIES%3Dtrue%26VARIABLE_RENAMING%3Dtrue%26PROPERTY_RENAMING%3Dtrue%26CLOSURE_PASS%3Dtrue%26GENERATE_EXPORTS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue

**Comment by zavr-1** [comment]
@brad4d the nature of my question is shown in the following example:

**externs**
```js
/**
 * @fileoverview
 * @externs
 */
var randomObject = {}

/**
 * @type {string}
 */
randomObject.hello_world
```
**source**
```js
import './externs'
const file = {
  hello_world: 'abc',
}
console.log(file)
```
**output**
```js
'use strict';                                       
console.log({hello_world:"abc"});
```
as you can see, there is no relationship between `file` and `randomObject`. The fact is that the compiler will always keep all properties's that appeared anywhere in externs regardless of the object where they appeared. I thought that was intentional by design to make life simpler to prevent having to have 100% typing. 

moreover, thanks for the detailed examples, however I'm not using `goog` system at all therefore export is useless.

**Comment by brad4d** [comment]
@zavr-1 I believe the recipe below will help you work around the problem that led you to create this issue. This is basically what the `@export` ends up doing.

```javascript
// Make sure Example.staticMethod is visible with that name even if
// closure-compiler decides to rename it.
// The method is intended to be used outside of the code that closure-compiler
// sees. This statement also prevents closure-compiler from thinking the method is
// totally unused and removing it.
Example['staticMethod'] = Example.staticMethod;
```

**Comment by zavr-1** [comment]
@brad4d yes very good recipe thank you. still a hack though, Java has static interfaces for example. but no prob at all
one point left to cover, why did the property get renamed in the class despite the externs -- you said that it's because they were not related then I gave an example when 2 objects are also not related but the property is kept. is it because classes are typed when objects are not? thanks.

**Comment by brad4d** [comment]
@zavr-1 to you `randomObject` defined in externs and the `file` variable created in your example code seem completely unrelated, but the type information on them is very weak from the compiler's point of view. Basically, they are seen as simple subclasses of `Object` which means its safest to assume they are related to each other.
