### ISSUE TITLE
feature request: use `[][0]` instead of `void 0`

### ISSUE THREAD

**Issue by zaoqi** [google/closure-compiler#3457]

**Comment by brad4d** [comment]
@zaoqi 
We played around with this idea, but we have to decline.

It's true that `[][0]` is one character shorter, but it also requires the JavaScript engine to create an array, then access its 0th member every time we need an undefined literal value in the code.

@nreid260 created a test at jsperf.com that showed a definite negative impact on performance to using `[][0]` instead of `void 0`. Unfortunately, I don't have the link to it now, but I expect anyone interested wouldn't have much trouble recreating it.
