### ISSUE TITLE
[JSC_UNDEFINED_VARIABLE] variable goog is undeclared With Advanced Optimisation

### ISSUE THREAD

**Issue by zavr-1** [google/closure-compiler#3506]
With advanced optimisation, there are errors when dealing with modules in the newest release.
Source code:
```js
import { loadJSON } from '@lemuria/load-scripts'
loadJSON('test.json')
```
Without advanced, it's compiled alright. When I add advanced, I receive an error. I think it's because the optimisation drops the goog variable at some point, although it's not present in non-advanced output either.
```console
closure-compiler:~$ java -jar compiler.jar --compilation_level ADVANCED --module_resolution \
NODE
--js t/index.js
     node_modules/@lemuria/load-scripts/package.json
     node_modules/@lemuria/load-scripts/src/index.js
     node_modules/@lemuria/load-scripts/src/Cache.js
     node_modules/@lemuria/load-scripts/src/inject.js
Exit code 1                                         
node_modules/@lemuria/load-scripts/package.json:1: ERROR - [JSC_UNDEFINED_VARIABLE] variable goog is undeclared
({
^^

1 error(s), 0 warning(s)
```

**Comment by nreid260** [comment]
Created Google internal issue http://b/144427091

**Comment by lauraharker** [comment]
Hi,

A compiler change in the last release made it an error to use `goog.provide` (or similar dependency methods like `goog.{require,module,declareModuleId}` without including a declaration of `goog` somewhere.

I didn't realize that NODE resolution generated a `goog.provide` from the `package.json`:
``` js
goog.provide("module$node_modules$$lemuria$load_scripts$package_json");
```

but that's what's causing this error. The compiler sees a reference to an undeclared global variable `goog`.

You should be able to suppress the error by either depending on Closure library's base.js or just including a dummy declaration of `var goog;` in some input script. That will get optimized away post-module-rewriting. Does that work for you?

I'll leave this issue open, since I think the compiler should either emit a clearer error message or no error in this particular case.

**Comment by zavr-1** [comment]
@lauraharker hi thanks would you mind making it _no error_ please in the next release? I sure can add a dummy `var goog;` but that's not ideal really because the compiler is not just for the closure library which is a _tiny_ bit discriminatory to throw an error at users like me for just compiling JS and not using closure. i'm not offended just saying that coupling the compiler to the goog namespace isn't 100% fair thx for understanding
