### ISSUE TITLE
Inlining method calls on unknown types results in broken code

### ISSUE THREAD

**Issue by robfig** [google/closure-compiler#3543]
The combination of suppressions, missing externs, and ADVANCED optimizations causes the compiler to incorrectly inline method calls. 

Here's the scenario:

```
A.prototype.getBar = function() { return bar; } 

B.prototype.someMethod = function() {
  let foo = this.getFoo();  // foo is an unknown type
  console.log(foo.getBar());
}
```

With type checking errors suppressed and property renaming disabled, `A.getBar` is inlined for `foo.getBar()`, assuming it's the only method called `getBar` in the compilation unit.

```
B.prototype.someMethod = function() {
  console.log(this.getFoo().bar);
}
```

The compiler is inferring that the `getBar()` method being called is the only one that it knows about, but that is not correct. I think it should not perform inlining unless it knows the specific type being used or method being called.

This has caused us issues a couple times when we were missing externs. I can put together a minimal reproduction, just let me know if that would be helpful.

**Comment by nreid260** [comment]
The compiler makes several broad assumptions about the code being compiled which are essential to effective optimization. Authors are expected to verify their assumptions for the project being compiled. An outline of those assumptions is available [here](https://developers.google.com/closure/compiler/docs/limitations). In this case the assumption being violated is that the compiler has a "global view" (can see all the code being optimized).

Additionally, it feels important to point out that types wouldn't be a solution to this problem. Not only is type inference optional, it isn't expected/required to type all code 100% accurately: it explicitly allows the unknown (`?`) type and suppressing of type errors. There are plenty of ways for code to lie to the type inferencer. For this reason, because it tends to be much more reliable, most optimizations performed by the compiler are type-naive: they rely only on syntax.
