### ISSUE TITLE
Travis CI build failing

### ISSUE THREAD

**Issue by lauraharker** [google/closure-compiler#3568]
The last two builds have failed with "The job exceeded the maximum log length, and has been terminated.".

[Build #4641](https://travis-ci.org/google/closure-compiler/builds/658950872?utm_medium=notification&utm_source=github_status)
[Build #4642](https://travis-ci.org/google/closure-compiler/builds/659342534?utm_source=github_status&utm_medium=notification)

**Comment by lauraharker** [comment]
The first failing build started including ~2000 lines from mvn:

```
Downloading from google-maven-central: https://maven-central.storage-download.googleapis.com/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom
Downloaded from google-maven-central: https://maven-central.storage-download.googleapis.com/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom (6.6 kB at 17 kB/s)
Downloading from google-maven-central: https://maven-central.storage-download.googleapis.com/maven2/net/ltgt/gwt/maven/gwt-maven-plugin/1.0-rc-6/gwt-maven-plugin-1.0-rc-6.pom
Downloaded from google-maven-central: https://maven-central.storage-download.googleapis.com/maven2/net/ltgt/gwt/maven/gwt-maven-plugin/1.0-rc-6/gwt-maven-plugin-1.0-rc-6.pom (11 kB at 26 kB/s)
[etc.]
```
that aren't in the [last passing build's log](https://travis-ci.org/google/closure-compiler/builds/658449332?utm_medium=notification&utm_source=github_status).

**Comment by lauraharker** [comment]
From https://issues.apache.org/jira/browse/MNG-6605 and https://stackoverflow.com/questions/21638697/disable-maven-download-progress-indication, `--disable_transfer_progress` suppresses all these "Downloading" messages. Unfortunately that option was added in Maven 3.6.1 and Travis uses 3.5.2.

Another solution [here](https://stackoverflow.com/questions/21638697/disable-maven-download-progress-indication) that works with 3.5.2 is to add`-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B`. This [makes the build pass](https://travis-ci.org/google/closure-compiler/builds/659672235?utm_source=github_status&utm_medium=notification). The drawback is that using batch mode (`-B`) loses the ANSI coloring. (Compare [before](https://travis-ci.org/google/closure-compiler/jobs/658449333?utm_medium=notification&utm_source=github_status) and [after](https://travis-ci.org/google/closure-compiler/builds/659672235?utm_source=github_status&utm_medium=notification)).

Alternatively, we could download a custom version of Maven and then use `--disable_transfer_progress`.
https://github.com/travis-ci/enterprise-installation/issues/14#issuecomment-273746437.

I still don't know what changed in the last few days to expose these messages.

**Comment by niloc132** [comment]
Given that the last log before the failures not only didnt have the log spam, but also didn't even indicate that the files were being fetched at all, my hunch is that something has gone wrong in caching the `.m2/repository/` directory.

This seems to be also be suggested by looking at logs (though admittedly, I don't know TravisCI very well):
 * In the last successful build, https://travis-ci.org/google/closure-compiler/builds/658449332, this is logged in the "Setting up build cache" section:
```
     found cache

     adding /home/travis/.m2 to cache
```
* Then, in the two failures and in the subsequent success (by suppressing download logging), we instead see this:
```
     could not download cache

     adding /home/travis/.m2 to cache
```

My hunch is that the cache used to be populated, perhaps with different constraints on the log size or with the dependency count/size only gradually growing, or a different version in maven in travis? Now that the cache entry is missing, it had to be replaced from nothing, and that generated too much log output? Since a new build has now succeeded, the cache could be re-populated, so the workaround you applied may no longer be necessary (at least until whatever happened to the cache happens again).

--

Another thought to avoid this in the future while still keeping ANSI output coloring for the main build: break the build into two steps, one which merely loads maven dependencies with all download messages suppressed, and one which actually performs the build, but with the normal output coloring. That first command may look something like `mvn dependency:go-offline`, see https://maven.apache.org/plugins/maven-dependency-plugin/go-offline-mojo.html. It doesn't have to actually get 100% of the output, just enough to keep the transfer progress noise in the "real" build to a minimum.

**Comment by lauraharker** [comment]
Thanks for noticing the `could not download cache` message. That does seem like the culprit.

Testing out adding a `mvn dependency:go-offline` step now.

**Comment by lauraharker** [comment]
The [latest push to master](https://travis-ci.org/google/closure-compiler/builds/660836033) is now passing. I'll check back tomorrow to see if the caching is working now that we've had a successful build.

Thanks for your help, Colin!

**Comment by jeradrutnam** [comment]
Looks like this issue still exist.

```bash
adding /home/travis/.m2 to cache

No output has been received in the last 10m0s, this potentially indicates a stalled build or 
something wrong with the build itself.
Check the details on how to adjust your build configuration on: 
https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
```

And my config looks like this

```yaml
language: java
cache:
  directories:
    - .autoconf
    - $HOME/.m2
script: mvn clean install -q
sudo: true
```
