### ISSUE TITLE
Use of yield statement throws JSC_UNKNOWN_EXPR_TYPE

### ISSUE THREAD

**Issue by ckudzu** [google/closure-compiler#3590]
When ever I try to compile any code using yield like the code below,

```
/**
 * @return {!Generator<boolean>}
 */
function* generator() {
  while(true){
    yield true;
  }
}
```

I get the error below:

```
ERROR: /*****/BUILD:96:1: Compiling 3 JavaScript files to test_js.js failed (Exit 1)
test.js:6: ERROR - could not determine the type of this expression
    yield true;
    ^
  ProTip: "JSC_UNKNOWN_EXPR_TYPE" or "missingSourcesWarnings" or "reportUnknownTypes" can be added to the `suppress` attribute of:
  //:test_js_lib
  Alternatively /** @suppress {reportUnknownTypes} */ can be added to the source file.

1 error(s), 0 warning(s), 96.0% typed
```

Looking at the code that throws the message, it looks like in the visit() function, case YIELD: doesn't set typeable = false unlike RETURN.
https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/TypeCheck.java

**Comment by rrdelaney** [comment]
I'm not able to reproduce this using this [code](https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%2520%2540return%2520%257B!Generator%253Cboolean%253E%257D%250A%2520*%252F%250Afunction*%2520generator()%2520%257B%250A%2520%2520while(true)%257B%250A%2520%2520%2520%2520yield%2520true%253B%250A%2520%2520%257D%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26CHECK_TYPES%3Dtrue%26TRANSPILE%3Dtrue%26PRETTY_PRINT%3Dtrue). Can you please paste the command you're using to compile the code?

**Comment by ckudzu** [comment]
I was able to reproduce the warning with ENABLE_ALL_DIAGNOSTIC_GROUPS and no TRANSPILE
https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%2520%2540return%2520%257B!Generator%253Cboolean%253E%257D%250A%2520*%252F%250Afunction*%2520generator()%2520%257B%250A%2520%2520while(true)%257B%250A%2520%2520%2520%2520yield%2520true%253B%250A%2520%2520%257D%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26ENABLE_ALL_DIAGNOSTIC_GROUPS%3Dtrue%26PRETTY_PRINT%3Dtrue

**Comment by lauraharker** [comment]
`yield` isn't marked with "typeable = false" because it can be part of an expression as well as a statement. (`const result = yield true;`), unlike `return`.

One problem is that the compiler cannot accurately type generators whose `next` method is called with a value (`f.next(someValue);`). https://github.com/google/closure-compiler/issues/3489 is the canonical issue.  The compiler just falls back to typing all yields as `?`.

I agree that reporting this error for yield statements is a bug, though. 

Perhaps a good solution is to never warn about "unknown expression types" for expressions in top-level statements. Or, more generally, to never warn for expressions whose value is unused.

The [BanUnknownTypedClassPropsReferences](https://github.com/google/closure-compiler/wiki/JS-Conformance-Framework#banunknowntypedclasspropsreferences) already ignores unused values: https://github.com/google/closure-compiler/blob/e2fa23c8b7838b8554523254dc09c11efff30a5f/src/com/google/javascript/jscomp/ConformanceRules.java#L1562

So you'd have to cast `const result = /** @type {whatever} */ (yield true);` but `yield true;` would be allowed.
