### ISSUE TITLE
Travis CI broken

### ISSUE THREAD

**Issue by lauraharker** [google/closure-compiler#3624]
The build has been broken since https://github.com/google/closure-compiler/commit/a5def5b3d07483640f088f10a6373351797c3826.

Travis link: https://github.com/google/closure-compiler/commit/a5def5b3d07483640f088f10a6373351797c3826

Either it was something in my commit or it was that we started using `Copybara-Service` to export to GitHub.

**Comment by lauraharker** [comment]
Edit: the link to the broken build is https://travis-ci.org/github/google/closure-compiler/builds/702143304.

**Comment by patrick-sko** [comment]
The source of the issue seems to be the added `ResourceLoader.java` file within the super-j2cl folder (It's a j2cl compatible version of the file) in the `a5def5b` commit. It conflicts with the GWT compatible version of `ResourceLoader.java` already included in the project. Deleting it should result in a successful build. Perhaps `Copybara-Service` inadvertently committed the file to the open-source project?  I'm not sure why else a j2cl compatible version might be needed.

**Comment by patrick-sko** [comment]
https://github.com/google/closure-compiler/pull/3625 - PR with successful Travis build.

**Comment by lauraharker** [comment]
Switching to Copybara-Service just happened to coincide with an internal config change to start including these j2cl sources.

Seems like we want to have the j2cl sources, and then eventually switch to j2cl, but the j2cl sources should not affect the existing gwt build.

**Comment by niloc132** [comment]
tangent re: j2cl - I have it on my todo list to see about getting our j2cl-maven-plugin working on this project. Might make sense to track in a separate ticket as j2cl-only sources are made available, though in most cases (outside of google) we find that you can support both gwt and j2cl with the same sources. 

It may get a bit cyclical though, since the j2cl-maven-plugin depends on closure-compiler/library to produce the eventual JS, and we're currently working from a fork of closure-compiler so that we have sourcemaps in BUNDLE, restore the PersistentInputStore, deal with some lag between releases as externs are modified, etc.

**Comment by patrick-sko** [comment]
I updated the above PR to instead exclude the new j2cl compatible version from the maven build process(including the gwt goal). It seemed that maven was already configured to ignore the j2cl folder but since it was placed elsewhere it caused a build error. I'm not sure what the best way to proactively prevent build failures in the future might be apart from simply excluding them as they are introduced.

**Comment by lauraharker** [comment]
Build is passing as of https://travis-ci.org/github/google/closure-compiler/builds/702521461. Thanks Patrick!

@niloc132 - right now I think @gkdn is working right now on getting a J2CL build of Closure Compiler, maybe having that landed will make j2cl-maven-plugin easier to update
