### ISSUE TITLE
Compiler fails to load packages with "main" other than "index.js"

### ISSUE THREAD

**Issue by dmitrysteblyuk** [google/closure-compiler#3629]
Especially this is a critical issue for node modules with es6 exports (e.g. I tried rxjs, antd etc). In that case neither "main" or "es2015" worked.
The error is the following:

```
./a.js:1: ERROR - [JSC_JS_MODULE_LOAD_WARNING] Failed to load module "./src"
  1| import {doSomething} from './src';
     ^

1 error(s), 0 warning(s)
```

Repro: [resolve-package-bug-repro.zip](https://github.com/google/closure-compiler/files/4875406/resolve-package-bug-repro.zip)

Command:
```
java -jar ./node_modules/google-closure-compiler-java/compiler.jar \
  --compilation_level=ADVANCED \
  --language_in=ES6 \
  --language_out=ES6 \
  --module_resolution=NODE \
  --entry_point=./a.js \
  --js=./a.js \
  --js=./src/b.js \
  --js=./src/package.json \
  --js_output_file=./app.js
```

Files:
```
./a.js
import {doSomething} from './src';

doSomething();
```
```
./src/b.js
export const doSomething = () => {
  console.log('okay');
};
```
```
./src/package.json
{
  "name": "src",
  "version": "1.0.0",
  "main": "./b.js",
  "dependencies": {}
}
```

**Comment by nreid260** [comment]
@ChadKillingsworth Do you know if this is intended or not?

**Comment by ChadKillingsworth** [comment]
The `package.json` file must be included as a compilation source for the compiler to be able to use the `main` entry. We have tests demonstrating this functionality:

 - https://github.com/google/closure-compiler/blob/master/test/com/google/javascript/jscomp/deps/ModuleLoaderTest.java
 - https://github.com/google/closure-compiler/blob/master/test/com/google/javascript/jscomp/CommandLineRunnerTest.java#L1911-L1926

Since this comes up frequently, maybe we should change the error message to indicate this is likely the problem when the module resolution mode is NODE.

**Comment by dmitrysteblyuk** [comment]
hmm I thought i included the `package.json` in the first place, but it still didn't work. Here're the sources:
```
 --js=./a.js \
 --js=./src/b.js \
 --js=./src/package.json \
```

**Comment by ChadKillingsworth** [comment]
This may be an unaccounted for case then - using package.json to load a file outside of a node_modules folder.

**Comment by dmitrysteblyuk** [comment]
I think i tried moving it to node_modules manually (and also using with yarn workspaces), but i'll double check

**Comment by dmitrysteblyuk** [comment]
Didn't work. I also tried other node modules. For example, `core-util-is` (it's a dependency of closure compiler, no need to install).

```
java -jar ./node_modules/google-closure-compiler-java/compiler.jar \
  --compilation_level=ADVANCED \
  --language_in=ES6 \
  --language_out=ES6 \
  --module_resolution=NODE \
  --process_common_js_modules \
  --entry_point=./a.js \
  --js=./a.js \
  --js=./node_modules/core-util-is/lib/util.js \
  --js=./node_modules/core-util-is/package.json \
  --js_output_file=./dist/index.js
```

```
// ./a.js
const {isArray} = require('core-util-is');

console.log(isArray([]));
```

The error is the same:
```
./a.js:1: ERROR - [JSC_JS_MODULE_LOAD_WARNING] Failed to load module "core-util-is"
  1| const {isArray} = require('core-util-is');
                       ^

1 error(s), 0 warning(s)
```

**Comment by ChadKillingsworth** [comment]
I think the problem may be how you are specifying the path to the `--js` flag. I realize that is completely not obvious. If you specified `--js=node_modules/core-util-is/package.json` for instance, it might work.

I normally stream inputs to the compiler as a JSON structure via STDIN, so it's been a while since I've worked with just the `--js` flags.

**Comment by dmitrysteblyuk** [comment]
Omg, indeed! Thank you again!
Is there anywhere example/docs how to stream json to stdin?
