### ISSUE TITLE
Download links are broken

### ISSUE THREAD

**Issue by rolintoucour** [google/closure-compiler#3662]
Like #3409, download links don't work anymore => 404

**Comment by brad4d** [comment]
Only the "latest" links are broken.

This is intentional, because we're no longer uploading pre-compiled binaries to dl.google.com as part of our release process.

The metrics we have show that downloads of the pre-compiled files from dl.google.com are very near zero each month.
It seems that nearly everyone uses Maven or NPM to install closure-compiler.
We're trying to streamline our external release process with the ultimate goal of being able to release more frequently.
Since no one (for a small but apparently non-zero value of "no one") seemed to use these links, and uploading to them is more tedious than you would expect, we decided to drop them from our process.

We updated the binary download page to reflect this, but failed to make an announcement.
https://github.com/google/closure-compiler/wiki/Binary-Downloads

Sorry about that.
If fetching the compiler via Maven or NPM doesn't work for you, the alternative is to build from source.
https://github.com/google/closure-compiler#building-it-yourself
