### ISSUE TITLE
Incorrect type attribution

### ISSUE THREAD

**Issue by samouri** [google/closure-compiler#3678]
**summary**
I recently ran into a case where a type was being incorrectly attributed.
It seems pretty strange.

**good**
```js
// JSC_POSSIBLE_INEXISTENT_PROPERTY: Property b never defined on a
const getEmpty = () => ({});
const a = getEmpty();
console.log(a.b);
```

**bad**
```js
// No warnings
const unrelatedObject = {b: 5};
const getEmpty = () => ({});
const a = getEmpty();
console.log(a.b);
```

See a live example in [appspot](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Aconst%2520unrelatedObject%2520%253D%2520%257Bb%253A%25205%257D%253B%250Aconst%2520getEmpty%2520%253D%2520()%2520%253D%253E%2520(%257B%257D)%253B%250Aconst%2520a%2520%253D%2520getEmpty()%253B%250Aconsole.log(a.b)%253B).

**Comment by brad4d** [comment]
This is **working as intended** and here's why.

> **good**
> 
> ```js
> // JSC_POSSIBLE_INEXISTENT_PROPERTY: Property b never defined on a
> const getEmpty = () => ({});
> const a = getEmpty();
> console.log(a.b);
> ```

There is no type declaration on `getEmpty()` at all, so the return value for it is the unknown type `{?}`.
The only reason you get an error at all is because there is no definition of a property named `b` anywhere in the input.
Based on that  it seems really unlikely that the `b` property exists on `a`.
The compiler can't be certain, though, because it isn't certain what the type of `a` actually is.
This is also why the error name includes the word **`_POSSIBLE_`**.

> **bad**
> 
> ```js
> // No warnings
> const unrelatedObject = {b: 5};
> const getEmpty = () => ({});
> const a = getEmpty();
> console.log(a.b);
> ```

Here there is at least one definition of a property named `b` in the input source code,
so the compiler must assume that a value of unknown type (`a`), could have a property named `b`.

**The moral of the story**

If you want the compiler to do a really good job of catching errors like this, you need to thoroughly annotate your code with type information.

**Comment by samouri** [comment]
> Here there is at least one definition of a property named b in the input source code,
so the compiler must assume that a value of unknown type (a), could have a property named b

This is the part I find confusing. I would expect the fact that it only _might_ be fine should lead to a `POSSIBLE_INEXISTENT_PROPERTY` exception.

Thank you for the explanation, I can work around it
