### ISSUE TITLE
Open source build instructions unclear

### ISSUE THREAD

**Issue by ctjlewis** [google/closure-compiler#3743]
I intended to add details to the README regarding the runtime tests and building/testing with NPM/yarn (i.e., via `yarn build` and `yarn test`) when I realized I cannot get the Maven build to work anymore, now that `pom.xml` is no longer in the root directory. Despite my best efforts to repair this (moving POM to `pom.xml`, adding `project.source` version to silence "source version must be > 8" errors, etc.) so that `mvn -DskipTests` and so on execute as expected, I cannot the project to compile successfully.

Any help from someone more experienced with Maven would be greatly appreciated. I will send my README PR as soon as this is working again.

**Comment by lauraharker** [comment]
I believe we only intend to support building via Bazel instead of Maven now: https://github.com/google/closure-compiler#using-bazel. (@nreid260 would know better than me)

Most of the development on Closure Compiler is done in Google's internal repo via the internal version of Bazel. Most of the Closure Compiler devs are more familiar with Bazel / its internal version, so switching from Bazel to Maven reduced a lot of friction for us & made the internal -> external sync easier, with the tradeoff that non-Google contributors will probably be more familiar with Maven.

Do the Bazel build instructions work for you?

**Comment by ctjlewis** [comment]
Thank you so much for clarifying Laura, I will update the package.json scripts in my PR and adjust it to build with Bazel. I forgot that this change was made a few releases ago.

**Comment by lauraharker** [comment]
@nreid260 could you comment on this + close if  appropriate? Thanks

**Comment by ctjlewis** [comment]
@lauraharker I think this should stay open until #3746 is merged - I have a README PR draft to add documentation as well.

**Comment by nreid260** [comment]
I can confirm that we no longer intended to support a Maven build. Bazel is the current build tool. We do however continue to publish Maven compatible artifacts to Sontaype.

**Comment by ctjlewis** [comment]
Understood. This would be closed by updating the runtime tests to use Bazel with #3746.
