### ISSUE TITLE
ES6 method overriding leads to JSC_HIDDEN_SUPERCLASS_PROPERTY_MISMATCH

### ISSUE THREAD

**Issue by treblereel** [google/closure-compiler#3745]
i have two classes:

```
class Object3D {
    constructor() {}
    /**
     * @param { Object3D } source 
     * @return { Object3D }
     */
    copy(source) {

        return this;
    }
}
export { Object3D };
```

```
import { Object3D } from './Object3D.js';
class Mesh extends Object3D {
    constructor() {
        super();
    }

    /**
     * @param { Mesh } source 
     * @return { Mesh }
     */
    copy(source) {
        return this;
    }
}
export { Mesh };

```
During compilation i see the following warning:

```
Mesh.js:13:4: WARNING - [JSC_HIDDEN_SUPERCLASS_PROPERTY_MISMATCH] mismatch of the copy property type and the type of the property it overrides from superclass Object3D$$module$Object3D
original: function(this:Object3D$$module$Object3D, (Object3D$$module$Object3D|null)): (Object3D$$module$Object3D|null)
override: function(this:Mesh$$module$Mesh, (Mesh$$module$Mesh|null)): (Mesh$$module$Mesh|null)
  13|     copy(source) {
          ^^^^^^^^^^^^^^
  14|         return this;
      ^^^^^^^^^^^^^^^^^^^^
  15|     }
```
Looks like i missed something, how could it be fixed ?

**Comment by lauraharker** [comment]
The parameter of `Mesh.prototype.copy` needs to be a supertype of `Object3D|null`. (i.e. parameters are contravariant)

Imagine that the compiler allowed the above class definition and then you had the following code:

``` js
/** @type {!Object3D} */
const obj3d = new Mesh();
obj3d.copy(new Object3D());
```

`obj3d.copy`, at runtime, refers to `Mesh.prototype.copy`. That method has declared it can take a `Mesh` but not an `Object3D`. Passing it a non-`Mesh` instance of `Object3D` could cause a runtime bug. However, because `obj3d.copy` has the same type as `Object3D.prototype.copy` and can accept all `Object3D`s, the compiler can't warn you about this potential bug.

So instead the compiler requires that `Mesh.prototype.copy` must accept `Object3D`s.
