### ISSUE TITLE
Generates invalid inlining and variable-merging in certain cases

### ISSUE THREAD

**Issue by bvaughn** [google/closure-compiler#3788]
The React team encountered an issue with Closure Compiler when compiling the React DOM bundle.

Repro steps:
1. Checkout this branch of React: https://github.com/bvaughn/react/tree/closure-bug-repro
2. Install dependencies: `yarn install --ignore-engines`
3. Build React bundle: `NODE_ENV=production node ./scripts/rollup/build.js --type=FB_WWW_PROD react-dom/index`
4. Open the built bundle: `build/facebook-www/ReactDOM-prod.js`
5. Find the `updateSuspenseComponent` function and look at the conditional that has `formatProdErrorMessage(360` in it.

This part of the code shows [the `getBumpedLaneForHydration` function](https://github.com/facebook/react/blob/6a589ad711db330c68a371321450ee2f0087e22f/packages/react-reconciler/src/ReactFiberLane.old.js#L789-L841) has been inlined into [the `updateSuspenseComponent` function](https://github.com/facebook/react/blob/6a589ad711db330c68a371321450ee2f0087e22f/packages/react-reconciler/src/ReactFiberBeginWork.old.js#L1807) and [the `lane` var in `getBumpedLaneForHydration`](https://github.com/facebook/react/blob/6a589ad711db330c68a371321450ee2f0087e22f/packages/react-reconciler/src/ReactFiberLane.old.js#L796) has been merged into [the `nextFallbackChildren` variable in `updateSuspenseComponent`](https://github.com/facebook/react/blob/6a589ad711db330c68a371321450ee2f0087e22f/packages/react-reconciler/src/ReactFiberBeginWork.old.js#L1908).

This causes a problem, because it should not be possible for the `lane` variable to have a value of `undefined` the way it has been written, _but it is possible_ for `nextFallbackChildren` to have a value of `undefined`.

This change in runtime behavior was observed in production on Facebook. At the current time the only known workaround is to use the `@noinline` directive.

**Comment by gaearon** [comment]
I wonder if this is another instance of https://github.com/google/closure-compiler/issues/3588 or a different bug.

**Comment by concavelenz** [comment]
Thanks for the report!

Would it be possible to provide the code snippets for the generated output (preferably with the `--debug` output option and `--formatting PRETTY_PRINT`), so you can point out exactly where the code was corrupted?

Once we know what we are looking for at will be much easier to track this down.

**Comment by bvaughn** [comment]
Sure @concavelenz!

We're using the `google-closure-compiler` npm package so I think the two things you mentioned translate to: `formatting: 'PRETTY_PRINT'` and `debug: true`. I've added those to my branch so you can reproduce in case it's helpful

And here's a gist with the generated output from the steps on this repro:
https://gist.github.com/bvaughn/62c0e308751be0c243e0efd3b653248a

The "bad" merged variable with these flags enabled is called 
`lane$jscomp$inline_1347_mode$jscomp$inline_614_nextFallbackChildren_prevOffscreenState$67_prevOffscreenState`

**Comment by brad4d** [comment]
I've just been digging through the original source code and the gist trying to understand what the problem is.

Our problem variable name is `lane$jscomp$inline_1347_mode$jscomp$inline_614_nextFallbackChildren_prevOffscreenState$67_prevOffscreenState`

The gist is https://gist.github.com/bvaughn/62c0e308751be0c243e0efd3b653248a

The problem variable first appears on line 8113 where it seems to be used as `nextFallbackChildren from this line

https://github.com/facebook/react/blob/6a589ad711db330c68a371321450ee2f0087e22f/packages/react-reconciler/src/ReactFiberBeginWork.old.js#L1908

then it is used in the 2 places equivalent to the if/else statements just below that.
This is direct assignment, then usage. I can't see any change of behavior here.

Next it is reassigned on line 8166.
I'm not certain which bit of the original code this corresponds to, but seems to be a variable named `mode`.
The important thing, though is that it is assigned a new value, then that value is possibly used.
The value previously assigned is not used.

Next it is reassigned in the switch statement starting on line 8229
or else an exception is thrown.
Then the variable is possibly used.

There's one more assignment followed by usage after that.

My point is that every place where it's value is read is clearly preceded by the assignment that is appropriate for that use.
I can't see any way for the value from one assignment to somehow survive to be used in one of the other, unrelated sections of code.

Perhaps the source of the code behavior problem is something else?

**Comment by bvaughn** [comment]
I am going to refer to `lane$jscomp$inline_1347_mode$jscomp$inline_614_nextFallbackChildren_prevOffscreenState$67_prevOffscreenState` as `lane..._prevOffscreenState` below to make it easier to read.

---

The [`lane` variable in `getBumpedLaneForHydration`](https://github.com/facebook/react/blob/6a589ad711db330c68a371321450ee2f0087e22f/packages/react-reconciler/src/ReactFiberLane.old.js#L796) gets combined with the [`nextFallbackChildren` in `updateSuspenseComponent`](https://github.com/facebook/react/blob/6a589ad711db330c68a371321450ee2f0087e22f/packages/react-reconciler/src/ReactFiberBeginWork.old.js#L1908) and the [`mode` variable in `mountSuspenseFallbackAfterRetryWithoutHydrating`](https://github.com/facebook/react/blob/6a589ad711db330c68a371321450ee2f0087e22f/packages/react-reconciler/src/ReactFiberBeginWork.old.js#L2343) (and maybe some others) into a single variable, `lane..._prevOffscreenState`.

On [this line](https://gist.github.com/bvaughn/62c0e308751be0c243e0efd3b653248a#file-reactdom-profiling-modern-js-L8113-L8114) that variable is assigned the value of `props.fallback` (which is a user-defined prop that can be undefined):
```js
var lane..._prevOffscreenState = JSCompiler_inline_result...fallback;
```

On [this line](https://gist.github.com/bvaughn/62c0e308751be0c243e0efd3b653248a#file-reactdom-profiling-modern-js-L8166-L8167) it's reused to hold the value of `workInProgress.mode`:
```js
lane..._prevOffscreenState = JSCompiler_inline_result...mode;
```

And then on [these lines](https://gist.github.com/bvaughn/62c0e308751be0c243e0efd3b653248a#file-reactdom-profiling-modern-js-L8229-L8265) it's used to replace [`lane`](https://github.com/facebook/react/blob/6a589ad711db330c68a371321450ee2f0087e22f/packages/react-reconciler/src/ReactFiberLane.old.js#L796) and hold a derived "lane" value:
```js
switch (return_highestLanePriority) {
  case 12:
    lane..._prevOffscreenState = 0;
    break;
  case 10:
    lane..._prevOffscreenState = 2;
    break;
  case 9:
  case 8:
    lane..._prevOffscreenState = 8;
    break;
  case 7:
  case 6:
    lane..._prevOffscreenState = 32;
    break;
  case 5:
    lane..._prevOffscreenState = 32;
    break;
  case 4:
    lane..._prevOffscreenState = 134217728;
    break;
  case 3:
  case 2:
    lane..._prevOffscreenState = 268435456;
    break;
  case 1:
  case 0:
    lane..._prevOffscreenState = 0;
    break;
  default:
    throw Error(formatProdErrorMessage(360, lane..._prevOffscreenState));
}

```

The problem is [in the `default` case](https://github.com/facebook/react/blob/6a589ad711db330c68a371321450ee2f0087e22f/packages/react-reconciler/src/ReactFiberLane.old.js#L828-L829) which reads the `lane` variable.

Looking at the original code, `lane` should _always be undefined_ in the `default` case since it reads the value without having initialized it. However because the variable has been re-used for other functions, it ends up having an arbitrary/unexpected value.

**Comment by brad4d** [comment]
Thanks, @bvaughn.
I had overlooked that the variable was used in the creation of the thrown error.

**Comment by brad4d** [comment]
I've managed to reproduce this in a smaller form.
I'm creating a unit test for it now.
Then we'll see if it's tricky to fix or not.

**Comment by brad4d** [comment]
I spoke too soon. I actually can't reproduce it.

I've also taken another look at the gist, and I no longer convinced this issue is a closure-compiler bug.
There's a guaranteed return after each assignment to the variable before we get to any other assignments to the variable.

First assignment
https://gist.github.com/bvaughn/62c0e308751be0c243e0efd3b653248a#file-reactdom-profiling-modern-js-L8113

The very next line is a return.

Second assignment.
https://gist.github.com/bvaughn/62c0e308751be0c243e0efd3b653248a#file-reactdom-profiling-modern-js-L8166

Is in a block that terminates with a return statement
https://gist.github.com/bvaughn/62c0e308751be0c243e0efd3b653248a#file-reactdom-profiling-modern-js-L8198

Switch statement with multiple assignments and final `default` case that uses the value.
https://gist.github.com/bvaughn/62c0e308751be0c243e0efd3b653248a#file-reactdom-profiling-modern-js-L8229

If either of the earlier assignments had occurred, we never would have reached this point.

Now, the first assignment is also the declaration. The variable's declaration gets hoisted to the top of the scope by the JS engine, but it should have an undefined value until this statement is reached. Could the JS engine be somehow assigning a value at the wrong time?
This seems unlikely to me, but I'm not sure how else one of the earlier assignments could have set a value that ends up
getting read in the `default` case of the switch statement.

I do think this line is a mistake in the original code.

https://github.com/facebook/react/blob/6a589ad711db330c68a371321450ee2f0087e22f/packages/react-reconciler/src/ReactFiberLane.old.js#L829

Surely it should be reporting an error on the variable used for the switch statement, `highestLanePriority`, not `lane`.

**Comment by brad4d** [comment]
Do we have a guaranteed return after the switch statement?

Yes.
https://gist.github.com/bvaughn/62c0e308751be0c243e0efd3b653248a#file-reactdom-profiling-modern-js-L8317

What about that last assignment, maybe it does something and then we loop back around?
Actually, there are 2 more, but both occur within `return` statements.
https://gist.github.com/bvaughn/62c0e308751be0c243e0efd3b653248a#file-reactdom-profiling-modern-js-L8330
https://gist.github.com/bvaughn/62c0e308751be0c243e0efd3b653248a#file-reactdom-profiling-modern-js-L8372

Maybe we're inside a loop and there's a `continue` somewhere?

Searched the gist for a `continue`. There are 3, but none occur between one of these assignments and the following return.

**Comment by bvaughn** [comment]
> I do think this line is a mistake in the original code.
> 
> facebook/react@6a589ad/packages/react-reconciler/src/ReactFiberLane.old.js#L829
> 
> Surely it should be reporting an error on the variable used for the switch statement, highestLanePriority, not lane.

Right, that's what I meant by my comment above:
> Looking at the original code, lane should always be undefined in the default case since it reads the value without having initialized it (so this code is a little funky) but the Closure generated code is different which is unexpected. Because the variable has been re-used for other functions, it ends up having an arbitrary/unexpected value.

The original code definitely contains a mistake. My concern was that we saw (inside of Facebook) behavior from the "compiled" code that wasn't possible given the initial source code.

Regarding your comments about `return` statements, I just traced through the code again and I think you're right. It looks like there are returns after both of the earlier uses of the mixed variable. Sorry I missed that.

I'm confused now 🤔 because we definitely saw a value in this merged variable getting logged to our error metrics that wasn't a possible value of `lane`. Perhaps some subtle change in either the source code (between the revision this came from and the one I linked you to above) or the Closure arguments "fixed" the issue.

**Comment by bvaughn** [comment]
I'm going to close this issue for now because I don't have a working repro after all. My apologies! If I'm able to reconstruct one, I'll re-open with more information.

Thanks for taking a look @brad4d!
