### ISSUE TITLE
Associated? arrays munted after compiling

### ISSUE THREAD

**Issue by Antix-Development** [google/closure-compiler#3854]
I have the following code...
```
let arr = {
	logo: [512, 16, 214, 91],
};
console.log(arr.logo);
console.log(arr['logo']);
```
This code works as expected.

The resulting code using ADVANCED_OPTIMIZATIONS  is...
```
var a = {
    g: [512, 16, 214, 91],
};
console.log(a.g);
console.log(a.logo);
```
This code fails because a.logo no longer exists.

It seems to be a bug to me but I'm kind of a noob at JavaScript.

**Comment by concavelenz** [comment]
This is working as expected.  "advanced" optimizations are not safe for general JavaScript and require code to conform to its expectations.    The key one here is that "computed" properties are never renamed (along with quoted properties in objects and classes).  This can be used to access dynamically created properties or properties from outside the compilation job that otherwise don't have associated "extern definitions"

So either:
```
let arr = {
	'logo': [512, 16, 214, 91],
};
console.log(arr['logo']);
```

or:
```
let arr = {
	logo: [512, 16, 214, 91],
};
console.log(arr.logo);
```

If you have further question feel free to post them to stack overflow or the the closure-compiler-discuss@ mailing list.
