### ISSUE TITLE
Compiler runs and exits immediately on FreeBSD 12.2

### ISSUE THREAD

**Issue by morganwdavis** [google/closure-compiler#3855]
After upgrading via npm from 20190909.0.0 to 20210808.0.0, invoking google-closure-compiler simply runs and exits. If I uninstall it and revert to the 20190909.0.0 version, it runs fine. OS is FreeBSD 12.2.

**Comment by lauraharker** [comment]
I can't reproduce this with 20210808.0.0 on Google's [linux distro](https://en.wikipedia.org/wiki/GLinux). A basic  `google-closure-compiler --js=/tmp/foo.js` prints a minified foo.js.

Could you paste the full command you're running?

**Comment by morganwdavis** [comment]
Laura, thanks for helping.  I'm executing it without arguments, which does nothing and returns to the command line prompt:

![image](https://user-images.githubusercontent.com/4434533/131741742-71c7ac38-a769-4de3-96a5-21889d5912f4.png)

Normally, the compiler would go into standard input mode like with version 20190909.0.0:

![image](https://user-images.githubusercontent.com/4434533/131742212-a3bc6714-6085-459e-99cd-18e2425fb0f8.png)

It doesn't matter what arguments I give to 20210808.0.0 -- it ignores them and simply exits.

Since it used to work, my hunch is that the recent version is not happy about the OS platform (FreeBSD 12) or npm 7.21.1
environment.  I'm happy to do any diagnostic troubleshooting tasks to assist on this. Let me know what I can do to help.

**Comment by brad4d** [comment]
I suspect this commit is responsible for the behavior change.

https://github.com/google/closure-compiler/commit/c9a6eaf67854bfec0199ee5066c67ced23e562de

The internal version changed so it would not read from stdin by default.
The intention in this commit was to keep the read-from-stdin default unchanged for the open source version,
but I suspect we missed a step somewhere. I notice there's no test case update in the commit.

**Comment by morganwdavis** [comment]
Additionally, even just asking for it to display the version number will not emit anything.

![image](https://user-images.githubusercontent.com/4434533/131746489-7a87fbcf-f0a7-4d44-bb45-9abfa8fdd3aa.png)

**Comment by lauraharker** [comment]
Thanks for narrowing this down. Since breaking change was between 20200719.0.0 and 20200920.0.0, sounds like https://github.com/google/closure-compiler/commit/c9a6eaf67854bfec0199ee5066c67ced23e562de wasn't the culprit. I verified that `google-closure-compiler --version` works on my linux machine.

There were a number of major changes to the release process in that time period e.g. https://github.com/google/closure-compiler-npm/commits/master?after=85c8955c31c7e596011870ea97ac8f9d4afff5e6+1&branch=master. None of them immediately stand out.

If you have time to debug more:
 * does version [20200830.0.0](https://www.npmjs.com/package/google-closure-compiler/v/20200830.0.0) work?
 * does `google-closure-compiler --platform=java` work? (assuming java is available. the default platform is the [Graal native image](https://www.graalvm.org/) which could conceivably be incompatible)
 *  what version of Node are you using?
 * if you insert `console.log('begin');` and `console.log('end')` at the beginning and end of the Node script at `$(which google-closure-compiler)` (which should match https://github.com/google/closure-compiler-npm/blob/master/packages/google-closure-compiler/cli.js) and run `google-closure-compiler`, does that logging show up?

**Comment by morganwdavis** [comment]
I'm running node v16.2.0.  I do not have java installed. I modified the cli.js with the console log output and both lines show up:

```
# google-closure-compiler --version
begin
end
```

But the version does not show.  And attempting to compile anything also generates no output except for the console log messages.

```
# google-closure-compiler --js=/tmp/foo.js 
begin
end
```

Reverting from 20210808.0.0 to 20200830.0.0 and running these tests made no difference.

We can divide and conquer through cli.js to find the culprit if you give me some suggestions on where to add more debug output.  Happy to help!

**Comment by lauraharker** [comment]
Thanks for your work troubleshooting!

(A C/C++ version is something we've discussed but won't happen any time soon, if ever)
