### ISSUE TITLE
Compiler incorrectly conflates local variable with exported property due to initialiser

### ISSUE THREAD

**Issue by cpcallen** [google/closure-compiler#3873]
The following input, where an static export is initialised from a local variable:
```JS
goog.module('Foo');
/** @type {number} */
let foo = 0;
/** @type {number} */
exports.bar = foo;
/** @returns {number} */
exports.getFoo = function() {return foo;};
/** @param {number} newFoo */
exports.setFoo = function(newFoo) {foo = newFoo;};
```
[is incorrectly compiled](https://closure-compiler-debugger.appspot.com/#input0%3Dgoog.module('Foo')%253B%250A%252F**%2520%2540type%2520%257Bnumber%257D%2520*%252F%250Alet%2520foo%2520%253D%25200%253B%250A%252F**%2520%2540type%2520%257Bnumber%257D%2520*%252F%250Aexports.bar%2520%253D%2520foo%253B%250A%252F**%2520%2540returns%2520%257Bnumber%257D%2520*%252F%250Aexports.getFoo%2520%253D%2520function()%2520%257Breturn%2520foo%253B%257D%253B%250A%252F**%2520%2540param%2520%257Bnumber%257D%2520newFoo%2520*%252F%250Aexports.setFoo%2520%253D%2520function(newFoo)%2520%257Bfoo%2520%253D%2520newFoo%253B%257D%253B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26CHECK_TYPES%3Dtrue%26REWRITE_MODULES_BEFORE_TYPECHECKING%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue); in particular, the local variable `foo` disappears and `getFoo` is rewritten to return `exports.bar`:
```JS
'use strict';
/** @const */ 
var module$exports$Foo = {};
module$exports$Foo.bar = 0;
/** @const */ 
module$exports$Foo.getFoo = function() {
  return module$exports$Foo.bar;
};
/** @const */ 
module$exports$Foo.setFoo = function(newFoo) {
  module$exports$Foo.bar = newFoo;
};
```
In particular, the compiled code conflates the local variable `foo` with the export `bar`; this results in very different behaviour between the same code when running in compiled and uncompiled mode: in compiled mode, calling `setFoo` modifies the `bar` export, which in uncompiled mode it (correctly) does not.

Adding `@nocollapse` declarations to `foo` and/or `bar` did not seem to resolve the issue.

**Comment by brad4d** [comment]
I've just been reviewing `ClosureRewriteModule.java`, which is responsible for transforming the `exports.bar = foo;` assignment and other `goog.module()` related code into its final form.

This appears to actually be working as intended, surprising as that is.

An `exports.propName = exportedVar;` assignment is not a "normal" assignment.
The compiler considers it an explicit request to make the **variable** `exportedVar`  accessible to code that imports `propName` with `goog.require()`.

The example code here makes this behavior clearer than usual by using different names for the variable and the property name and by providing a side channel for modifying the variable name, but this is the intended behavior.

**Comment by brad4d** [comment]
Did you actually try to run this code uncompiled and observe the behavior difference? The "uncompiled serving" we support is really still doing a minimal form of transpilation of the modules in the browser at runtime. As a result it may actually have the same behavior as the fully compiled version. Can you confirm otherwise?

At this stage, the fact that you can even run a `goog.module()` file uncompiled at all is kind of a vestigial organ. It is only intended as a convenience for debugging, not a good way to serve code for actual use. If anything, I think we'd want to try to force uncompiled code to have the behavior that one currently gets for compiled code.

BTW, if you think of `exports.foo = foo;` as the closure equivalent of ES module `export foo;`, then you'll see that you're actually getting the same behavior. It's just that since the `goog.module()` method is working with normal assignments it is possible to use a name that doesn't match as the local variable.

Sorry this is confusing. Module systems are hard, and sadly we had to come up with our own for practical reasons before ECMAScript managed to define its own.
