### ISSUE TITLE
Uint8Array() constructor missing extern

### ISSUE THREAD

**Issue by vapier** [google/closure-compiler#3929]
the `new Uint8Array();` syntax new in ES2017 is missing from externs
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array/Uint8Array

```
$ closure-compiler --version
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20220301

$ cat test.js
const f = new Uint8Array();

$ closure-compiler --language_in=ECMASCRIPT_2020 --jscomp_error=* test.js 
test.js:1:10: ERROR - [JSC_WRONG_ARGUMENT_COUNT] Function Uint8Array:
      called with 0 argument(s). Function requires at least 1 argument(s) and no more than 3 argument(s).
  1| const f = new Uint8Array();
               ^^^^^^^^^^^^^^^^

1 error(s), 0 warning(s), 100.0% typed
```

**Comment by brad4d** [comment]
I notice that there is no description on MDN of what happens when you provide 0 arguments to this method.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array/Uint8Array

The only thing that makes sense to me is that you should get a 0-length array,
but it would be much less error-prone to specify `new Uint8Array(0)` to get that.

There are other cases where our externs require parameters that are actually optional for reasons of better readability and error detection.

I think this case meets the same criteria as those.

Thanks for pointing out that we're not quite matching the spec here.

I'll add a comment to our externs file to make it clear that our variation from the spec is intentional here.
