### ISSUE TITLE
Injecting logical or assignment operator loses trailing code

### ISSUE THREAD

**Issue by mcurland** [google/closure-compiler#3940]
Using closure-compiler-v20220502.jar downloaded from Maven repository (renamed without the version suffix).

Place this code in bug.js
```
/**
* @param {Array} xs
*/
function bug(xs) {
	var ys;
	for (var count = xs.length, i = 0; i < count; ++i) {
		var x = xs[i];
		x['y'] && (ys || (ys = [])).push(x);
	}
}
window['bug'] = bug;
```
java -jar closure-compiler.jar --compilation_level ADVANCED --language_out ECMASCRIPT_NEXT bug.js

Note that the output converts to a logical or assignment operator, but the trailing .push call is stripped (the defect). Needless to say stripping the call that actually adds data to the array is bad.
```
window.bug=function(b){for(var d,e=b.length,a=0;a<e;++a){var c=b[a];c.y&&(d||=[])}};
```

For comparison,
java -jar closure-compiler.jar --compilation_level ADVANCED --language_out STABLE bug.js

Stable output has less restructuring (the logical or assignment is not injected) but retains the .push call.
```
window.bug=function(b){for(var c,e=b.length,a=0;a<e;++a){var d=b[a];d.y&&(c||(c=[])).push(d)}};
```

**Comment by lauraharker** [comment]
Thanks for the report.

In the simplified repro I think technically the output code is fine, since the content of the `ys` array is never read. But if I add `return ys;` the `.push` call is still deleted so I agree this is a bug.

From printing this code after each compiler pass (results below)

The logical or assignment is inserted in `denormalize`. The `.push` call is later deleted in `latePeepholeOptimizations`.

I suspect that something in `latePeepholeOptimizations` does not understand how logical or assignments work.

```
// // ************************************
// 
// // collapseVariableDeclarations yields:
// // ************************************
// // bug.js
// 'use strict';
// window.bug = function(xs) {
//   var ys, count$jscomp$39 = xs.length, i$jscomp$18 = 0;
//   for (; i$jscomp$18 < count$jscomp$39; ++i$jscomp$18) {
//     var x$jscomp$90 = xs[i$jscomp$18];
//     x$jscomp$90.y && (ys || (ys = [])).push(x$jscomp$90);
//   }
// };
// 
// // ************************************
// 
// // denormalize yields:
// // ************************************
// // bug.js
// 'use strict';
// window.bug = function(xs) {
//   for (var ys, count$jscomp$39 = xs.length, i$jscomp$18 = 0; i$jscomp$18 < count$jscomp$39; ++i$jscomp$18) {
//     var x$jscomp$90 = xs[i$jscomp$18];
//     x$jscomp$90.y && (ys ||= []).push(x$jscomp$90);
//   }
// };
// 
// // ************************************
// 
// // renameVars yields:
// // ************************************
// // bug.js
// 'use strict';
// window.bug = function($xs$$) {
//   for (var $ys$$, $count$jscomp$39$$ = $xs$$.length, $i$jscomp$18$$ = 0; $i$jscomp$18$$ < $count$jscomp$39$$; ++$i$jscomp$18$$) {
//     var $x$jscomp$90$$ = $xs$$[$i$jscomp$18$$];
//     $x$jscomp$90$$.y && ($ys$$ ||= []).push($x$jscomp$90$$);
//   }
// };
// 
// // ************************************
// 
// // latePeepholeOptimizations yields:
// // ************************************
// // bug.js
// 'use strict';
// window.bug = function($xs$$) {
//   for (var $ys$$, $count$jscomp$39$$ = $xs$$.length, $i$jscomp$18$$ = 0; $i$jscomp$18$$ < $count$jscomp$39$$; ++$i$jscomp$18$$) {
//     var $x$jscomp$90$$ = $xs$$[$i$jscomp$18$$];
//     $x$jscomp$90$$.y && ($ys$$ ||= []);
//   }
// };
```

**Comment by lauraharker** [comment]
It would be nice if the compiler realized that entire block of code was useless.

I've sent out a fix for internal review.

Turned out that a certain utility incorrectly assumes all assignment operators evaluate to a primitive, which was only true before logical assignment operators were introduced: https://github.com/google/closure-compiler/blob/42648a11f847d9b53f5db4aa702108925e1d835b/src/com/google/javascript/jscomp/NodeUtil.java#L4856-L4931

**Comment by mcurland** [comment]
That was quick turnaround, well done Laura.

A warning for dead code internal to a function would be a nice but I don't think it's a good idea to automatically remove it (like can happen with entire unused library functions). Of course, you usually can't tell if the code is a noop from just the code structure because you have no idea if there are side effects in the called functions. That's where the fun begins.

Regardless programmers don't generally write meaningless code on purpose so a warning would be much better than silent removal. Having code simply disappear is unnerving (as evidenced in this issue).

Cheers.
