### ISSUE TITLE
Incorrect constant folding with ??=

### ISSUE THREAD

**Issue by AshleyScirra** [google/closure-compiler#3943]
Using v20220502, in.js:

```js
let myvar = null;
myvar ??= 1;
console.log(myvar);
```

Command line: `java -jar ./compiler.jar --js in.js --js_output_file out.js --compilation_level ADVANCED --language_in ECMASCRIPT_2021`

Observed result:

```js
console.log(null);
```

Expected result:
```js
console.log(1);
```

**Comment by lauraharker** [comment]
From printing the source code after each compiler pass, the early peephole optimizations are replacing `myvar ?? myvar = 1` with `false ?? myvar = 1`. 

I believe the problem is in https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/PeepholeRemoveDeadCode.java. Shouldn't be hard to fix.

```
// // inlineAndCollapseProperties yields:
// // ************************************
// // bug.js
// 'use strict';
// let module$contents$bug_myvar = null;
// module$contents$bug_myvar ?? (module$contents$bug_myvar = 1);
// console.log(module$contents$bug_myvar);
// 
// // ************************************
// 
// // earlyPeepholeOptimizations yields:
// // ************************************
// // bug.js
// 'use strict';
// let module$contents$bug_myvar = null;
// false ?? (module$contents$bug_myvar = 1);
// console.log(module$contents$bug_myvar);
```
