### ISSUE TITLE
java.lang.NoSuchMethodError for java/nio/file/Files.readString

### ISSUE THREAD

**Issue by GaneshKaparapu** [google/closure-compiler#3956]
We are getting an error executing with latest closure-compiler jar version.

java.lang.NoSuchMethodError: java/nio/file/Files.readString(Ljava/nio/file/Path;Ljava/nio/charset/Charset;)Ljava/lang/String; (loaded from /usr/lib/jvm/java-1.8.0-ibm-1.8.0.6.25-1jpp.1.el7.x86_64/jre/lib/rt.jar by <Bootstrap Loader>) called from class com.google.javascript.jscomp.SourceFile$CodeLoader$OnDisk (loaded from file:/<local-path>/closure-compiler/**closure-compiler-v20220601.jar**

**Comment by liblit** [comment]
This failure indicates that the `java.nio.file.Files` class does not have a `readString​(Path, Charset)` method. [That method was added in Java 11.](https%3A%2F%2Fdocs.oracle.com%2Fen%2Fjava%2Fjavase%2F11%2Fdocs%2Fapi%2Fjava.base%2Fjava%2Fnio%2Ffile%2FFiles.html%23readString%28java.nio.file.Path%2Cjava.nio.charset.Charset%29) From @GaneshKaparapu's message we can see that they are using `java-1.8.0`, which is simply too old to run the latest Closure code.

I see at least two recent commits that started using Java 11+ features:

* 49b3cd49c64944ff2dfc9add9ee76525a55f58fd by @lukesandberg: "use `Files.readString`, this should perform fewer buffer copies when reading and decoding the file"

* ac7007cf34316cadf3346baa448ba3d8677ae107 by @blickly: "Misc simplifications, including some that use Java11 APIs"

There may be other recent commits that also rely on Java 11+. I did not search exhaustively.

How backward-compatible does Closure intend to be? If Closure's maintainers want it to be runnable on Java 1.8 JVMs, then these two commits (and possibly others) will need to be reverted and reworked to only use Java 1.8 APIs. Otherwise, if Closure's maintainers are willing to require Java 11+, then it would be good to at least document that somewhere explicitly.

**Comment by concavelenz** [comment]
The intent is to require Java 11, it isn't great to "slide into it".  Let's get the documentation updated

**Comment by mhausner** [comment]
I updated the Readme page, the Release notes of the June release, and the FAQ.

**Comment by mhausner** [comment]
Documentation has been updated. Java 11 is required to run the compiler starting with the June release.
