### ISSUE TITLE
Compilation level BUNDLE with inject_libraries=false still injects some library code

### ISSUE THREAD

**Issue by AshleyScirra** [google/closure-compiler#3969]
Possibly related to #3948. Compilation level `BUNDLE` adds a lot of library code by default. This can be turned off with `inject_libraries=false`, but then some library code is still injected, causing errors as they are not declared anywhere.

main.js:

```js
import * as Module from "./dep.js";

console.log(Module.GetMessage());
```

dep.js:

```js
export function GetMessage()
{
	return "Hello world @ " + Date.now();
}
```

Command: `java -jar ./compiler.jar --js main.js --js dep.js --dependency_mode PRUNE --entry_point main.js --compilation_level BUNDLE --inject_libraries=false --language_in ECMASCRIPT_2021 --language_out ECMASCRIPT_2021 --formatting PRETTY_PRINT --js_output_file out.js`
(Tested with v20220502 as the Java 11 update has caused a bit of a headache in my setup)

Observed result in out.js:

```js
//dep.js
$jscomp.registerAndLoadModule(function($$require, $$exports, $$module) {
  "use strict";
  Object.defineProperties($$exports, {GetMessage:{enumerable:true, get:function() {
    return GetMessage;
  }}});
  function GetMessage() {
    return "Hello world @ " + Date.now();
  }
}, "dep.js", []);

//main.js
$jscomp.registerAndLoadModule(function($$require, $$exports, $$module) {
  "use strict";
  var Module = $$require("dep.js");
  console.log(Module.GetMessage());
}, "main.js", ["dep.js"]);
```

Note the undeclared references to things like `$jscomp.registerAndLoadModule` and `$$require`. Therefore this output code will not work.

Expected result:
If you switch the compilation mode to `SIMPLE`, you get an output that looks like this:

```js
function GetMessage$$module$dep() {
  return "Hello world @ " + Date.now();
}
var module$dep = {};
module$dep.GetMessage = GetMessage$$module$dep;
console.log(GetMessage$$module$dep());
var module$main = {};
```

I was expecting `BUNDLE` mode with `inject_libraries=false` to essentially look the same as that, while disabling the `SIMPLE` mode compilation features.

**Comment by concavelenz** [comment]
This is working as intended. "inject_libraries = false" doesn't remove the needed for these functions.   The assumption is that the needed code is being provided in some other way.

**Comment by AshleyScirra** [comment]
So is it not possible to get the output of SIMPLE mode but without any optimisations? I assumed that's what BUNDLE mode would do, but it seems to be a different mode entirely.

**Comment by niloc132** [comment]
@AshleyScirra what is your goal in getting SIMPLE (more accurately SIMPLE_OPTIMIZATIONS) without any optimizations? WHITESPACE_ONLY offers a very simple set of optimizations, which might be slightly more than whitespace changes (for example if you change the output language), while BUNDLE concatenates files, adds enough wiring so they can be loaded as a single file instead of many.

BUNDLE is very nearly not the same set of compiler options than the rest of the supported compilation levels (ADVANCED_OPTIMIZATIONS, SIMPLE_OPTIMIZATIONS, WHITESPACE_ONLY) - while both start from the command line utility in the CommandLineRunner class, three optimization levels call into the Compiler class to produce output, while BUNDLE results in the output being produced by the ClosureBundler class. Note that _some_ work is still done by the Compiler when producing BUNDLE output, this is mostly down to deciding which inputs should be included in the output.

But the es6 registerAndLoadModule helper isn't an optimization, it is just a way to rewrite a few es6 module semantics so that these modules can all coexist in a single file (since of course they won't be able to reference each other as distinct files). If you already have a function like this, you can omit the injected libraries, otherwise you will need some way to manage imports and exports. You could probably copy part/all of the contents of src/com/google/javascript/jscomp/js/es6/modules/runtime.js into your project so that you control how much extra is added to your BUNDLE output.
