### ISSUE TITLE
Expose cross_chunk_code_motion_no_stub_methods compiler flag

### ISSUE THREAD

**Issue by theseanl** [google/closure-compiler#3990]
There is a field "noStubFunctions" in `CrossChunkMethodMotion.java`

https://github.com/google/closure-compiler/blob/f6a71c13dbc9c2bd4e192115cf60e3032733f8d6/src/com/google/javascript/jscomp/CrossChunkMethodMotion.java#L67-L81

and also a field `crossChunkCodeMotionNoStubMethods` in `CompilerOptions.java`, which seems to be controlling `noStubFunctions` later down.

https://github.com/google/closure-compiler/blob/147b2073ba8534945390abae0648465be0fd0bc1/src/com/google/javascript/jscomp/CompilerOptions.java#L422-L429

It seems that the only thing that is missing is an appropriate code that exposes this via CLI flag (if everything works as documented).

Would you consider exposing it?

Such a flag would instruct the compiler that codes based on enumerating prototype methods won't be used, and allow the compiler to move prototype method declaration to a later chunks without leaving "stub methods". 

There is a similar flag `assume_static_inheritance_is_not_used`, which tells the compiler that certain code pattern won't be used, and will allow more optimizations.

**Comment by frigus02** [comment]
Discussed internally. We are open to exposing this as a command line flag.

Regarding the flag name: JSCompiler flag names historically didn't follow any particular naming scheme. We would like to fix this for new flags.:

- The name should be based on the assumptions the compiler needs to make.
- The name should be phrased as an additional, otherwise unknown fact, about the "world" that the compiler is operating on/or producing code for.
- The name doesn't necessarily need to be phrased as "assume x", as the in the case of "isolation mode" or "language out", but it is a good place to start. 

`assume_static_inheritance_is_not_used` is a good example. In this case we could go for something like `assume_no_prototype_method_enumeration`.

**Comment by theseanl** [comment]
Hi, I have created a PR. Could you please take a look?
