### ISSUE TITLE
Unshaded jar contains bogus "/" entry

### ISSUE THREAD

**Issue by DerGuteMoritz** [google/closure-compiler#4060]
The unshaded jar contains a bogus "/" directory entry. While this isn't a problem for using it, it does cause trouble with [DependencyCheck's](https://github.com/jeremylong/DependencyCheck) archive analyzer which fails with the following error when it runs into it:

    Archive contains a file (/) that would be extracted outside of the target directory.

**Comment by blickly** [comment]
Thanks for the report.

I doubt we'll get around to fixing this ourselves, but It looks like that's built by bazel defined here: https://github.com/google/closure-compiler/blob/master/BUILD.bazel#L39 in case anyone else wants to take a crack at fixing it.

**Comment by niloc132** [comment]
The link presently points to this block https://github.com/google/closure-compiler/blob/86708dabb6b492b704a4b0b984b4371f90663c3a/BUILD.bazel#L38-L45, which is about the shaded jar, rather than https://github.com/google/closure-compiler/blob/86708dabb6b492b704a4b0b984b4371f90663c3a/BUILD.bazel#L89-L96 which is the source of this bug.

This project is using an older version of rules_jvm_external. Updating from 4.2 to 4.5 (presently the latest) fixes this particular issue, but there are more recent changes in MergeJars.java, which correctly creates directories in the jar file before using them (see bazelbuild/rules_jvm_external#785).

This doesn't _appear_ to materially impact downstream jar consumers as far as I can tell, and was merged Nov 2022 but not tagged as a new release yet.

Proposed patch to update closure-compiler is at #4061.
