### ISSUE TITLE
refactor `IllegalStateException`: it is used for too many different things and so the type doesn't carry enough information about happening

### ISSUE THREAD

**Issue by KOLANICH** [google/closure-compiler#4063]

**Comment by brad4d** [comment]
`IllegalStateException` gets thrown by a bunch of methods calls like `checkState(someConditionThatShouldNotHappen, "description of the condition")` that we use to assert things that should always be true. That way the code doesn't just go forward working with a state we deem to be invalid, but stops instead. This is an intentional loud error to force us to notice that something is wrong here and avoid silently generating invalid output.

These errors aren't something our users can respond to. They represent the compiler's code behaving badly.
Otherwise, they would be normal error messages from the compiler.

I don't see how we could refactor this. Every situation in which we assert the program's state is unique. I don't see what benefit we would get by trying to classify them. In fact, I think we'd just waste brain power trying to come up with a classification system that we can all understand and apply consistently.

It is fair to say we could do a better job in many places of adding descriptions to the text generated, but I don't see how that would be something we could act on and "finish" to close an issue.

OTOH, if someone identifies a specific case where an `IllegalStateException` is thrown where a normal error message should be reported, it would be good to file an issue to get that fixed.

**Comment by KOLANICH** [comment]
Thanks for the info. Improving messages within exceptions is really a better solution for this problem.
