### ISSUE TITLE
JSC_BLOCK_SCOPED_DECL_MULTIPLY_DECLARED_ERROR on function redeclaration

### ISSUE THREAD

**Issue by ChesterEcwid** [google/closure-compiler#4094]
Hi! 

We use elm in pair with google-compiler to minify elm-compiled scripts. And there hides an issue: elm-lang/html contains Json module, it's compiled to JS with following part of the code:
```
function badIndex(index, nestedProblems)
{
	return { tag: 'index', index: index, rest: nestedProblems };
}

function badField(field, nestedProblems)
{
	return { tag: 'field', field: field, rest: nestedProblems };
}

function badIndex(index, nestedProblems)
{
	return { tag: 'index', index: index, rest: nestedProblems };
}
```

As you can see, there are two functions "badIndex". Google closure compiler is unable to minify such code starting from [this](https://github.com/google/closure-compiler/commit/f5e3ed7ab208248fded7416767e544b957abdfdd) fix.
```
ERROR - [JSC_BLOCK_SCOPED_DECL_MULTIPLY_DECLARED_ERROR] Duplicate let / const / class / function declaration in the same scope is not allowed.
  4383| function badIndex(index, nestedProblems)
```

But in JS such function redeclaration is valid. Shouldn't compiler be able to compile code with duplication functions? Is there a way to turn off duplicate functions check?

**Comment by brad4d** [comment]
Sorry, but there is definitely no way to turn off this check, because as far as closure-compiler is concerned a redeclaration like this is almost certainly a bug.

Function declarations are supposed to be "hoisted" to the top of the scope, so they're available for use before you actually reach their declaration in the code. If you have 2 declarations for the same name, then which one wins when there's a call before the first declaration?

Your example, as written, is clearly a bug. Why would it make any sense to have 2 declarations for the same function in the same scope?

If you have some functional reason to have `badIndex` refer to one function early in a scope, then a different function later, then you can easily do this by just declaring `badIndex` with `let` and a function expression like this.

```javascript
let badIndex = function badIndex(index, nestedProblems) {
	return { tag: 'index', index: index, rest: nestedProblems };
};

// ... presumably some code appears here that uses `badIndex()` as it is currently defined.

// Redefine badIndex() because ???
badIndex = function(index, nestedProblems) {
        // presumably this should actually be different from the definition above.
	return { tag: 'index', index: index, rest: nestedProblems };
};
```

**Comment by ChesterEcwid** [comment]
Unfortunately it's an elm Json package code, so we can't edit it, it's compiled as is.
