### ISSUE TITLE
A for loop compiles incorrectly in WHITESPACE_ONLY and SIMPLE_OPTIMIZATIONS

### ISSUE THREAD

**Issue by jplevene** [google/closure-compiler#4130]
A `for(const row of rows)` returns $jscomp and loads of junk JavaScript code that won't run.

**Comment by jplevene** [comment]
Even does this in WHITESPACE_ONLY that is not supposed to alter the code

**Comment by lauraharker** [comment]
This is caused by transpilation. See https://github.com/google/closure-compiler/issues/3856 and https://github.com/google/closure-compiler/issues/2007.

Compiler versions past https://github.com/google/closure-compiler/commit/ac3e3303617e23aed24eb7574e1d140565aa079a will default to not transpiling. If you're using an older version you can set `--language_out=ECMASCRIPT_NEXT`. If you're using a newer version, are you setting `--language_out` explicitly? You'd need to remove that.

**Comment by jplevene** [comment]
I spotted this bug in the Google online compiler https://closure-compiler.appspot.com/ which is managed by Google and no place to report the bugs.  So it is them that need to correct this.
By default, clicking "Whitespace only" should include the line // @language_out ECMASCRIPT_NEXT
