### ISSUE TITLE
Closure Compiler fails to properly remove comments from Pixi.js source files.

### ISSUE THREAD

**Issue by RubrikBonnier** [google/closure-compiler#769]
Hello. I've noticed very bizarre results from running Closure Compiler on my project using Pixi.js. I decided to make a couple of minimal tests to make sure it's not my fault. Here's what I ran:

java -jar compiler.jar --js pixi.js --js_output_file pixi-done.js --compilation_level ADVANCED_OPTIMIZATIONS
java -jar compiler.jar --js pixi.dev.js --js_output_file pixi.dev-done.js --compilation_level ADVANCED_OPTIMIZATIONS

The finished .js files, after going through CC, still contain comments, only with the asterisks on each row (inside the comments) removed. Basically, the way that Pixi.js (and possibly other libraries) style their JS comments seems to confuse CC.

Here are the actual files I am using:

https://raw.githubusercontent.com/GoodBoyDigital/pixi.js/master/bin/pixi.js
https://raw.githubusercontent.com/GoodBoyDigital/pixi.js/master/bin/pixi.dev.js

They each get slightly different results, and in my actual project, it even causes syntax errors (that could be somehow my fault, but it seems to be related to this).

Can somebody please tell me what's going on? Is this simply a bug in CC? Am I doing something horribly wrong? This is not my first time using CC; I've been using it for a few years now.

The only workaround I've found is to run the same CC command twice in a row (requires a bit of fiddling with the file names). However, it feels really silly and stupid. I don't like the feeling that CC isn't "doing all of its job in one go".

Since CC is an extremely advanced piece of software, coded by very smart people, something so simple as stripping out comments seems too stupid to be an actual bug. Still, who knows? It will be interesting to see what you say about this.

**Comment by MatrixFrog** [comment]
The first thing to do would be to make sure you're on the latest version: `java -jar compiler.jar -version` should give you "Version: v20141215"

When I try this locally I see the comment at the top being left in, but no others. The top comment is left intentionally because it has `@license` in it, meaning that it most likely needs to be kept there for legal reasons. Are you seeing just that one, or are all other comments being left in as well?

**Comment by RubrikBonnier** [comment]
Version: v20141023
Built on: 2014/10/24 10:20

Almost the latest version. I downloaded the latest one now and tried again. Same results in regards to the comments.

/**
 * @license
 * pixi.js - v2.2.0
 * Copyright (c) 2012-2014, Mat Groves
 * http://goodboydigital.com/
 *
 * Compiled: 2014-12-12
 *
 * pixi.js is licensed under the MIT License.
 * http://www.opensource.org/licenses/mit-license.php
 */

becomes:

/*

 pixi.js - v2.2.0
 Copyright (c) 2012-2014, Mat Groves
 http://goodboydigital.com/

 Compiled: 2014-12-12

 pixi.js is licensed under the MIT License.
 http://www.opensource.org/licenses/mit-license.php
*/

and:

(tons of comments go here)

turns into:

/*
 Mat Groves, Rovanion Luckey
*/

I find it rather odd, but I kinda get what you mean in regards to @license tags and whatnot. Can I force-remove those too? I will be giving due credits to the libraries I use. I just don't want their comments polluting my nice blob of mixed-together output JS.

**Comment by MatrixFrog** [comment]
It looks like we have this hard-coded at https://github.com/google/closure-compiler/blob/master/src%2Fcom%2Fgoogle%2Fjavascript%2Fjscomp%2FCompiler.java#L1823-1828 and I'm very hesitant to change that because it makes it too easily to accidentally violate an open-source license.

Of course you could make changes to your own copy of the compiler but then you'll have to make sure that you're doing whatever the license requires.

**Comment by ChadKillingsworth** [comment]
There was actually an old enhancement request (which I currently cannot find) to make comment blocks starting with `/*!` behave the same way as `@license`.

I didn't realize `@author` tags were being preserved.

**Comment by concavelenz** [comment]
@author tags should not be preserved
