### ISSUE TITLE
Missing extern for download attribute used in <a> and <area> nodes.

### ISSUE THREAD

**Issue by alexkowel** [google/closure-compiler#806]
Other attributes may be missing too, for more info check HTML5 spec: https://html.spec.whatwg.org/multipage/semantics.html#attr-hyperlink-download

**Comment by concavelenz** [comment]
Best to put together a pull request if you would like them added.

**Comment by acordex** [comment]
I'd just like to second alexkowel's request for adding the 'download' attribute. I spent a while tracking down a bug that was ultimately caused by doing "a.download", which was then minified.

Some other externals that would prevent lost time if added:

window.FileReaderSync
window.MozBlobBuilder
window.navigator.msSaveOrOpenBlob
window.mozRequestFileSystem

**Comment by chrismiddleton** [comment]
I don't have the time or know-how to put together a pull request at the moment, but I'd just like to second alexkowel's request for adding the 'download' attribute. I spent a while tracking down a bug that was ultimately caused by doing "a.download", which was then minified.

Some other externals that would prevent lost time if added:

window.FileReaderSync
window.MozBlobBuilder
window.navigator.msSaveOrOpenBlob
window.mozRequestFileSystem

**Comment by concavelenz** [comment]
@ChadKillingsworth would you be interested in putting together a PR for "download"?

**Comment by ChadKillingsworth** [comment]
Sure.

**Comment by ChadKillingsworth** [comment]
The other missing externs here should be their own issue. I plan to address them with a new environment for web and service workers.

**Comment by chrismiddleton** [comment]
Thanks, Chad. There are lot of externs to keep track of and I appreciate your dedication to this project.
