### ISSUE TITLE
Turning on the typed-based optimizations by default

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-compiler#812]
This seems to come up a lot. Unless you are well versed in the compiler project, the expectation is that type information would be used for renaming.

* http://stackoverflow.com/q/28318862/1211524
* http://stackoverflow.com/q/28196051/1211524
* http://stackoverflow.com/q/12671041/1211524

Is it time to turn on the type based optimizations by default?

**Comment by dimvar** [comment]
I'm fine with that. Unless sm has any objections, we can probably do that for the next release.

**Comment by concavelenz** [comment]
As I stated previously when this came up before, we should not do this.  Type based optimization rely on accurate type information.  "lies" through unknowns or otherwise generate will cause bad code to be generated.  This kinds of errors are very difficult to track down and can be a significant barrier to entry. If the have to turn it on, they will also know how to turn it off.  It isn't like we hide this option, it is in the FAQ, etc.  

 I think I cover this in more detail here:

https://github.com/google/closure-compiler/wiki/Experimental-Type-Based-Property-Renaming

I have spent several weeks of my life trying to track down the source of type information that cause these problems for various projects.

**Comment by ChadKillingsworth** [comment]
@concavelenz I've only once had an issue where incorrect type information caused that issue. I've always seen that as much less of a barrier than property renaming in general (which on it's own is hard to debug).

However maybe this can be addressed another way. 

What if we added a warning guard called `renamingReport` that was off by default.  I've long wanted information about what blocks a property from being renamed. The ambiguate/disambiguate passes have debugging information that can be turned on, but the messages are currently designed for maintainers and not a general audience.

I could add logging to the ambiguate properties pass (using the existing debugging messages as a guide) and add those to the new warning guard. I could also add a message to the standard rename properties pass to show when a property can't be renamed due to an extern, but also suggest it might be renameable with the type based optimizations.

While very noisy, this would give a developer feedback where there is currently none.
