### ISSUE TITLE
Out of date methods for Typed Arrays

### ISSUE THREAD

**Issue by isiahmeadows** [google/closure-compiler#820]
See [section 22.2 of the draft](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-typedarray-objects).

[These lines](https://github.com/google/closure-compiler/blob/master/externs/es6.js#L250-L615)  are missing about 80% of the methods for ES6 typed arrays. The static methods also don't exist.

**Comment by ChadKillingsworth** [comment]
We'd welcome a pull request.

**Comment by impinball** [comment]
I'm currently working on it. It'll take a few more days to get the rest of the API sorted out. Expect about 80% of the file to be replaced with new material.

What's sad is that I'm having to make a script to help me create the mass of JSDoc quicker. (Only the generated code will be included, since manual fine-tuning will be required.)

**Comment by Dominator008** [comment]
@isiahmeadows #1413 has added these. Closing for now.
