### ISSUE TITLE
not-null / const annotation not used when optimizing for inlining

### ISSUE THREAD

**Issue by dhai** [google/closure-compiler#825]
given the following function:

	/**
	 * @param {!Object} a
	 */
	function check(a) {
		if (a) {
			console.log('exists');
		} else {
			console.log('not exists');
		}
	}

When calling with a new expression or a 

	check({});
	// compiles to: console.log("exists");

	check(console);
	// compiles to: console ? console.log("exists") : console.log("not exists");

I checked the declaration of console, it and it's defined as {!Object}.  Shouldn't closure compiler be more aggressive here and use not null declarations as optimization points?

Test here: https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%2520%2540param%2520%257BObject%257D%2520a%250A%2520*%252F%250Afunction%2520check(a)%2520%257B%250A%2509if%2520(a)%2520%257B%250A%2509%2509console.log('exists')%253B%250A%2509%257D%2520else%2520%257B%250A%2509%2509console.log('not%2520exists')%253B%250A%2509%257D%250A%257D%250A%250A%252F%252F%2520check(%257B%257D)%253B%250Acheck(console)%253B%2520%252F%252F%2520this%2520should%2520also%26input1%26conformanceConfig%26externs%3D%252F**%250A%2520*%2520%2509%2540constructor%250A%2520*%2520%2509%2540extends%2520%257BObject%257D%250A%2520*%252F%250Afunction%2520Console()%2520%257B%257D%253B%250A%250A%252F**%250A%2520*%2520%2540param%2520%257B...*%257D%2520var_args%250A%2520*%252F%250AConsole.prototype.log%2520%253D%2520function(var_args)%2520%257B%257D%253B%250A%250A%252F**%250A%2520*%2520%2540const%250A%2520*%2520%2540type%2520%257B!Console%257D%250A%2520*%252F%250Avar%2520console%253B%26refasterjs-template%26AGGRESSIVE_VAR_CHECK%3D1%26CHECK_CONSTANTS%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_UNREACHABLE_CODE%3D1%26COLLAPSE_ANONYMOUS_FUNCTIONS%3D1%26COLLAPSE_PROPERTIES%3D1%26COLLAPSE_VARIABLE_DECLARATIONS%3D1%26COMPUTE_FUNCTION_SIDE_EFFECTS%3D1%26DEAD_ASSIGNMENT_ELIMINATION%3D1%26DEVIRTUALIZE_PROTOTYPE_METHODS%3D1%26DISAMBIGUATE_PROPERTIES%3D1%26EXTRACT_PROTOTYPE_MEMBER_DECLARATIONS%3D1%26FLOW_SENSITIVE_INLINE_VARIABLES%3D1%26FOLD_CONSTANTS%3D1%26INLINE_CONSTANTS%3D1%26INLINE_FUNCTIONS%3D1%26INLINE_GETTERS%3D1%26INLINE_VARIABLES%3D1%26LABEL_RENAMING%3D1%26MISSING_PROPERTIES%3D1%26MOVE_FUNCTION_DECLARATIONS%3D1%26OPTIMIZE_CALLS%3D1%26OPTIMIZE_PARAMETERS%3D1%26OPTIMIZE_RETURNS%3D1%26PRETTY_PRINT%3D1%26PROPERTY_RENAMING%3D1%26REMOVE_DEAD_CODE%3D1%26REMOVE_UNUSED_PROTOTYPE_PROPERTIES%3D1%26REMOVE_UNUSED_VARIABLES%3D1%26REWRITE_FUNCTION_EXPRESSIONS%3D1%26SMART_NAME_REMOVAL%3D1%26VARIABLE_RENAMING%3D1

**Comment by concavelenz** [comment]
Generally, these kinds of optimizations aren't safe when dealing with external entry points and values, nor does the type system distinguish between the internal and external types (nor is it possible in the general case).  It is possible to introduce security problems by removing necessary checks.

**Comment by dhai** [comment]
Fair enough -- wasn't that much of a a big deal anyhow.  You can close this if it's not relevant.

I have some general questions about the compiler -- where is the best place to ask these (such as the difference between * and ? types)

**Comment by dimvar** [comment]
Here: https://groups.google.com/forum/#!forum/closure-compiler-discuss

For * (top type) and ? (unknown type), the difference is that ? is not typechecked. You can use ? as any other type, and use any other type in a context that expects ?.

Top is a supertype of all types. This means that you can pass any type to a context that expects top. On the other hand, to use top as some other type, eg, number, you have to downcast, otherwise you'll get a warning.

Generally, top is not very useful, ? is what you want when you want to work around the type system.

**Comment by MatrixFrog** [comment]
per John's comment, it sounds like this is a "won't fix"?

**Comment by concavelenz** [comment]
In case this comes up again, I meant "internal and external VALUES" not types.  The types we know the origins of, the values sources.  I've mentioned previously, this requires "is only possible to be" rather than "is expected to be".  We could do some of this within a method (For "var x = -foo;", "x" must be a number) but our type systems doesn't track "expected to be" separately from "can only be".  Maybe, after the NTI is stable, I can convince an intern to take a whack at that.
