### ISSUE TITLE
Emit a lint warning if an extra goog.requires is present

### ISSUE THREAD

**Issue by nanaze** [google/closure-compiler#843]
Google Web Server team would like to move away from linting and to clang formatter. As such, we are filing feature requests on compiler for features that we currently rely on linter for.

Tagging our requests with hashtag #lintfix

**Comment by concavelenz** [comment]
Removing #lintfix adding label "lint"

**Comment by MatrixFrog** [comment]
So this is tricky. If a type is used *only* in JsDoc comments, you generally don't want to goog.require it. Except, occasionally you do want to goog.require it so that everything will be typechecked properly. So I'm thinking we should give an "extra require" warning only if it's not referenced anywhere, even JsDoc. So we'd have:

 * Type is referenced in code -> goog.require is required (missingRequires check fails if it's not there)
 * Type is referenced in an `@extends` -> goog.require is required (missingRequires check fails if it's not there)
 * Type is referenced in other JsDoc (`@type` etc) -> goog.require is optional (don't warn, regardless of if it is there)
 * Type is not referenced at all -> goog.require is forbidden (extraRequires check fails if it is there)
