### ISSUE TITLE
Add a simple command-line option for the environment the code is going to run in

### ISSUE THREAD

**Issue by MatrixFrog** [google/closure-compiler#966]
I think we've discussed this but I didn't see a bug filed. This would probably look something like --env=WEB or --env=NODEJS or maybe --env=MODERN_WEB (meaning, latest version or two of the major browsers) and you would automatically get the correct set of externs, instead of having to specify each externs file with the `--externs` flag.

This would also help a lot with making the compiler easier to use.

**Comment by si-robertson** [comment]
Seeing as #1032 has been closed, I would like to extend this issue by saying `--env` should also support workers, e.g. `--env=DEDICATED_WORKER`, and the object that the `self` keyword represents in JS should also change to match the specified environment (the global context).

**Comment by ChadKillingsworth** [comment]
@si-robertson yes that's the plan. `--language-in` should control the `ES#.js` externs to be included, but anything else should be specified via environment.

To my knowledge, no work has started on this yet though.

**Comment by ChadKillingsworth** [comment]
I've begun to plan for this change.

My initial plan is that sets of externs will be stored in folders. The biggest hurdle I see is accounting for dependencies between externs. Currently, the compiler has a [hard coded list of externs](https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/CommandLineRunner.java#L1226) to specify the dependency order. I'd like to move away from this type of hard coded list.

## Options
1. Text based dependency file to be stored in each folder.
2. Add synthetic `goog.require` and `goog.provide` calls to each extern and utilize the existing dependency management code.

I'm personally leaning towards option 1 as it seems the easiest to maintain.

**Comment by dimvar** [comment]
Remind me, what's bad about the hard-coded list? It seems easy to have a hard-code list for each different environment. I forget what downsides we mentioned during the meeting.

**Comment by ChadKillingsworth** [comment]
Mainly because the list of files is maintained in two separate places and the list must be equal. After looking again, I think I can improve the situation by assuming any file in the externs folder that is not in the list is assumed to depend on any file that is explicitly listed.

In this way, an extern could be added to a set without impacting the dependency list if no externs depend on it (it's a leaf node).

**Comment by si-robertson** [comment]
I'm just throwing my initial thought in here, so feel free to ignore it.

Manually dependency ordering is horrible but there doesn't seem to be a way of avoiding it at the moment, so instead of having multiple folders for multiple contexts, why not have a single file (maybe JSON or XML) that links contexts and externs. The compiler could simply load/parse that file and pull in the externs as needed.

````
<!-- default -->
<context type="window">
    <extern file="path/to/extern1.js" />
    <extern file="path/to/extern2.js" />
    <extern file="path/to/extern3.js" />
    <extern file="path/to/extern4.js" />
</context>

<!-- for all workers -->
<context type="worker">
    <extern file="path/to/another/extern1.js" />
    <extern file="path/to/another/extern2.js" />
</context>

<!-- for dedicated workers (extends the "worker" type above) -->
<context type="dedicated_worker">
    <extern file="path/to/another/extern3.js" />
    <extern file="path/to/another/extern4.js" />
</context>
````

Something along those lines anyway.

**Comment by dimvar** [comment]
> Mainly because the list of files is maintained in two separate places and the list must be equal.

What's the other place besides the hard-coded list?

**Comment by ChadKillingsworth** [comment]
1. enumerating the files in the `externs` folder.
2. hard coded immutable list of strings in CommandLineRunner.java.

I'll have something to review which lessens the burden of maintaining the immutable list soon without introducing a new file or syntax for dependencies.
