### ISSUE TITLE
Warn about placing @nocollapse on a prototype property

### ISSUE THREAD

**Issue by dimvar** [google/closure-compiler#984]
Folks at Google are starting to use nocollapse in their projects, and they are putting it in all sorts of places. The following should be a warning, that the annotation does nothing, since collapse-properties doesn't look at prototype properties anyway.

    /** @constructor */
    function Foo() {}
    
    /** @nocollapse */
    Foo.prototype.dprop = 234;
    
    var y = Foo.prototype.dprop;

**Comment by ChadKillingsworth** [comment]
This isn't as straight forward as I had hoped. Since the CollapseProperties pass uses the GlobalNamespace class, prototype properties are ignored.

I can try to shoe horn this into GlobalNamespace with a flag to indicate whether warnings should be emitted or not (since GlobalNamespace is used in multiple passes), or I can try to find another pass to issue the warning from.

Thoughts?

**Comment by blickly** [comment]
I'd prefer not to put more warnings into the optimizations phase. Especially not something like this that can just be checked syntactically regardless of whether the properties are actually being collapsed.

Maybe CheckJSDoc.java ?

**Comment by dimvar** [comment]
I was gonna suggest parsing/IRFactory.java, but I very much like the idea of CheckJSDoc.java.

It's good to have a pass that detects misplaced jsdocs. It is quite common that the passes who need a jsdoc annotation only look at the nodes that might have it, so they don't warn about the annotation placed on irrelevant nodes. It can be the first check in DefaultPassConfig#getChecks, always on (without a compiler option).

**Comment by ChadKillingsworth** [comment]
That's about where I had landed as well. I'll start work on the CheckJSDoc.java pass then.

**Comment by ChadKillingsworth** [comment]
Closed by #1006
